//#priority 349
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

val advancedtechstage as IItemStack[] = [
    <thermalfoundation:glass>,
    <thermalfoundation:glass:1>,
    <thermalfoundation:glass:2>,
    <thermalfoundation:glass:3>,
    <thermalfoundation:glass:4>,
    <thermalfoundation:glass:5>,
    <thermalfoundation:glass:6>,
    <thermalfoundation:glass:7>,
    <thermalfoundation:glass:8>,
    <thermalfoundation:glass_alloy>,
    <thermalfoundation:glass_alloy:1>,
    <thermalfoundation:glass_alloy:2>,
    <thermalfoundation:glass_alloy:3>,
    <thermalfoundation:glass_alloy:4>,
    <thermalfoundation:glass_alloy:5>,
    <thermalfoundation:glass_alloy:6>,
    <thermalfoundation:glass_alloy:7>,
    <thermalfoundation:rockwool>,
    <thermalfoundation:rockwool:1>,
    <thermalfoundation:rockwool:2>,
    <thermalfoundation:rockwool:3>,
    <thermalfoundation:rockwool:4>,
    <thermalfoundation:rockwool:5>,
    <thermalfoundation:rockwool:6>,
    <thermalfoundation:rockwool:7>,
    <thermalfoundation:rockwool:8>,
    <thermalfoundation:rockwool:9>,
    <thermalfoundation:rockwool:10>,
    <thermalfoundation:rockwool:11>,
    <thermalfoundation:rockwool:12>,
    <thermalfoundation:rockwool:13>,
    <thermalfoundation:rockwool:14>,
    <thermalfoundation:rockwool:15>,
    <thermalfoundation:upgrade:1>,
    <thermalfoundation:upgrade:2>,
    <thermalfoundation:upgrade:3>,
    <thermalfoundation:upgrade:33>,
    <thermalfoundation:upgrade:34>,
    <thermalfoundation:upgrade:35>,
    <thermalfoundation:upgrade:256>,
    <thermalfoundation:security>,
    <thermalfoundation:diagram_redprint>,
    <thermalfoundation:tome_experience>,
    <thermalfoundation:coin>,
    <thermalfoundation:coin:1>,
    <thermalfoundation:coin:64>,
    <thermalfoundation:coin:66>,
    <thermalfoundation:coin:67>,
    <thermalfoundation:coin:68>,
    <thermalfoundation:coin:69>,
    <thermalfoundation:coin:70>,
    <thermalfoundation:coin:71>,
    <thermalfoundation:coin:72>,
    <thermalfoundation:coin:96>,
    <thermalfoundation:coin:97>,
    <thermalfoundation:coin:98>,
    <thermalfoundation:coin:99>,
    <thermalfoundation:coin:100>,
    <thermalfoundation:coin:101>,
    <thermalfoundation:coin:102>,
    <thermalfoundation:coin:103>,
    <thermalfoundation:fertilizer>,
    <thermalfoundation:fertilizer:1>,
    <thermalfoundation:fertilizer:2>,
    <thermalfoundation:bait>,
    <thermalfoundation:bait:1>,
    <thermalfoundation:bait:2>,
    <thermalfoundation:material:513>,
    <thermalfoundation:material:514>,
    <thermalfoundation:material:515>,
    <thermalfoundation:material:640>,
    <thermalfoundation:material:656>,
    <thermalfoundation:material:657>,
    <thermalfoundation:material:1024>,
    <thermalfoundation:material:1025>,
    <thermalfoundation:material:1026>,
    <thermalfoundation:material:1027>,
    <thermalfoundation:material:1028>,
    <thermalexpansion:strongbox>,
    <thermalexpansion:strongbox>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 1 as byte}),
    <thermalexpansion:strongbox>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 3 as byte}),
    <thermalexpansion:strongbox>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 2 as byte}),
    <thermalexpansion:strongbox>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 4 as byte}),
    <thermalexpansion:machine>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:1>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [3, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:2>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [3, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:3>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [3, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:4>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [3, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:5>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:6>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:7>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 2, 3, 3, 3, 3] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:8>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [3, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:9>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:10>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [3, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:11>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:12>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:13>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:14>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:machine:15>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 0 as byte}),
    <thermalexpansion:device>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [0, 1, 0, 0, 0, 0] as byte[] as byte[]}),
    <thermalexpansion:device:1>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [0, 1, 1, 1, 1, 1] as byte[] as byte[]}),
    <thermalexpansion:device:2>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [0, 1, 1, 1, 1, 1] as byte[] as byte[]}),
    <thermalexpansion:device:3>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[]}),
    <thermalexpansion:device:4>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[]}),
    <thermalexpansion:device:5>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[]}),
    <thermalexpansion:device:6>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[]}),
    <thermalexpansion:device:7>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[]}),
    <thermalexpansion:device:8>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[]}),
    <thermalexpansion:device:9>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [0, 1, 1, 1, 1, 1] as byte[] as byte[]}),
    <thermalexpansion:device:10>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[]}),
    <thermalexpansion:device:11>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[]}),
    <thermalexpansion:device:12>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [0, 1, 0, 0, 0, 0] as byte[] as byte[]}),
    <thermalexpansion:dynamo>.withTag({RSControl: 0 as byte, Facing: 1 as byte, Energy: 0, Level: 0 as byte}),
    <thermalexpansion:dynamo:1>.withTag({RSControl: 0 as byte, Facing: 1 as byte, Energy: 0, Level: 0 as byte}),
    <thermalexpansion:dynamo:3>.withTag({RSControl: 0 as byte, Facing: 1 as byte, Energy: 0, Level: 0 as byte}),
    <thermalexpansion:dynamo:4>.withTag({RSControl: 0 as byte, Facing: 1 as byte, Energy: 0, Level: 0 as byte}),
    <thermalexpansion:dynamo:5>.withTag({RSControl: 0 as byte, Facing: 1 as byte, Energy: 0, Level: 0 as byte}),
    <thermalexpansion:cell>.withTag({Recv: 1000, RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Level: 0 as byte, Send: 1000}),
    <thermalexpansion:dynamo:2>.withTag({RSControl: 0 as byte, Facing: 1 as byte, Energy: 0, Level: 0 as byte}),
    <thermalexpansion:cache>.withTag({Facing: 3 as byte, Level: 0 as byte}),
    <thermalexpansion:capacitor>.withTag({Energy: 1000000}),
    <thermalexpansion:capacitor:1>.withTag({Energy: 4000000}),
    <thermalexpansion:capacitor:2>.withTag({Energy: 9000000}),
    <thermalexpansion:capacitor:3>.withTag({Energy: 16000000}),
    <thermalexpansion:capacitor:4>.withTag({Energy: 25000000}),
    <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}),
    <thermalexpansion:reservoir>.withTag({}),
    <thermalexpansion:reservoir:1>.withTag({}),
    <thermalexpansion:reservoir:2>.withTag({}),
    <thermalexpansion:reservoir:3>.withTag({}),
    <thermalexpansion:reservoir:4>.withTag({}),
    <thermalexpansion:reservoir:32000>.withTag({}),
    <thermalexpansion:frame>,
    <thermalexpansion:frame:64>,
    <thermalexpansion:frame:128>,
    <thermalexpansion:frame:129>,
    <thermalexpansion:frame:130>,
    <thermalexpansion:frame:131>,
    <thermalexpansion:frame:132>,
    <thermalexpansion:frame:146>,
    <thermalexpansion:frame:147>,
    <thermalexpansion:frame:148>,
    <thermalexpansion:augment:128>,
    <thermalexpansion:augment:129>,
    <thermalexpansion:augment:130>,
    <thermalexpansion:augment:256>,
    <thermalexpansion:augment:257>,
    <thermalexpansion:augment:258>,
    <thermalexpansion:augment:273>,
    <thermalexpansion:augment:288>,
    <thermalexpansion:augment:303>,
    <thermalexpansion:augment:304>,
    <thermalexpansion:augment:320>,
    <thermalexpansion:augment:323>,
    <thermalexpansion:augment:324>,
    <thermalexpansion:augment:336>,
    <thermalexpansion:augment:337>,
    <thermalexpansion:augment:352>,
    <thermalexpansion:augment:368>,
    <thermalexpansion:augment:369>,
    <thermalexpansion:augment:400>,
    <thermalexpansion:augment:401>,
    <thermalexpansion:augment:402>,
    <thermalexpansion:augment:416>,
    <thermalexpansion:augment:432>,
    <thermalexpansion:augment:433>,
    <thermalexpansion:augment:448>,
    <thermalexpansion:augment:496>,
    <thermalexpansion:augment:497>,
    <thermalexpansion:augment:512>,
    <thermalexpansion:augment:513>,
    <thermalexpansion:augment:514>,
    <thermalexpansion:augment:515>,
    <thermalexpansion:augment:576>,
    <thermalexpansion:augment:640>,
    <thermalexpansion:augment:656>,
    <thermalexpansion:augment:672>,
    <thermalexpansion:augment:673>,
    <thermalexpansion:augment:674>,
    <thermalexpansion:augment:688>,
    <thermalexpansion:augment:704>,
    <thermalexpansion:augment:720>,
    <thermalexpansion:florb>,
    <thermalexpansion:morb>,
    <thermaldynamics:duct_0>,
    <thermaldynamics:duct_0:1>,
    <thermaldynamics:duct_0:2>,
    <thermaldynamics:duct_0:3>,
    <thermaldynamics:duct_0:4>,
    <thermaldynamics:duct_0:5>,
    <thermaldynamics:duct_0:6>,
    <thermaldynamics:duct_0:7>,
    <thermaldynamics:duct_0:8>,
    <thermaldynamics:duct_0:9>,
    <thermaldynamics:duct_16>,
    <thermaldynamics:duct_16:1>,
    <thermaldynamics:duct_16:2>,
    <thermaldynamics:duct_16:3>,
    <thermaldynamics:duct_16:4>,
    <thermaldynamics:duct_16:5>,
    <thermaldynamics:duct_16:6>,
    <thermaldynamics:duct_16:7>,
    <thermaldynamics:duct_32>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32>,
    <thermaldynamics:duct_32:1>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:1>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:1>,
    <thermaldynamics:duct_32:2>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:2>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:2>,
    <thermaldynamics:duct_32:3>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:3>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:3>,
    <thermaldynamics:duct_32:4>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:4>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:4>,
    <thermaldynamics:duct_32:5>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:5>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:5>,
    <thermaldynamics:duct_32:6>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:6>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:6>,
    <thermaldynamics:duct_32:7>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:7>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:7>,
    <thermaldynamics:duct_48>,
    <thermaldynamics:duct_64>,
    <thermaldynamics:duct_64:1>,
    <thermaldynamics:duct_64:2>,
    <thermaldynamics:duct_64:3>,
    <thermaldynamics:servo>,
    <thermaldynamics:servo:1>,
    <thermaldynamics:servo:2>,
    <thermaldynamics:servo:3>,
    <thermaldynamics:servo:4>,
    <thermaldynamics:filter>,
    <thermaldynamics:filter:1>,
    <thermaldynamics:filter:2>,
    <thermaldynamics:filter:3>,
    <thermaldynamics:filter:4>,
    <thermaldynamics:retriever>,
    <thermaldynamics:retriever:1>,
    <thermaldynamics:retriever:2>,
    <thermaldynamics:retriever:3>,
    <thermaldynamics:retriever:4>,
    <thermaldynamics:relay>,
    <thermalcultivation:watering_can>.withTag({Water: 4000, Mode: 0}),
    <thermalcultivation:watering_can:1>.withTag({Water: 12000, Mode: 1}),
    <thermalcultivation:watering_can:2>.withTag({Water: 24000, Mode: 2}),
    <thermalcultivation:watering_can:3>.withTag({Water: 40000, Mode: 3}),
    <thermalcultivation:watering_can:4>.withTag({Water: 60000, Mode: 4}),
    <thermalcultivation:watering_can:32000>.withTag({Water: 60000, Mode: 4}),
    <thermalinnovation:drill>.withTag({Energy: 40000, Mode: 1}),
    <thermalinnovation:drill:1>.withTag({Energy: 120000, Mode: 2}),
    <thermalinnovation:drill:2>.withTag({Energy: 240000, Mode: 2}),
    <thermalinnovation:drill:3>.withTag({Energy: 400000, Mode: 3}),
    <thermalinnovation:drill:4>.withTag({Energy: 600000, Mode: 4}),
    <thermalinnovation:drill:32000>.withTag({Energy: 600000, Mode: 4}),
    <thermalinnovation:saw>.withTag({Energy: 40000, Mode: 1}),
    <thermalinnovation:saw:1>.withTag({Energy: 120000, Mode: 2}),
    <thermalinnovation:saw:2>.withTag({Energy: 240000, Mode: 2}),
    <thermalinnovation:saw:3>.withTag({Energy: 400000, Mode: 3}),
    <thermalinnovation:saw:4>.withTag({Energy: 600000, Mode: 4}),
    <thermalinnovation:saw:32000>.withTag({Energy: 600000, Mode: 4}),
    <thermalinnovation:magnet>.withTag({Energy: 40000}),
    <thermalinnovation:magnet:1>.withTag({Energy: 120000}),
    <thermalinnovation:magnet:2>.withTag({Energy: 240000}),
    <thermalinnovation:magnet:3>.withTag({Energy: 400000}),
    <thermalinnovation:magnet:4>.withTag({Energy: 600000}),
    <thermalinnovation:magnet:32000>.withTag({Energy: 600000}),
    <thermalinnovation:injector>.withTag({}),
    <thermalinnovation:injector:1>.withTag({}),
    <thermalinnovation:injector:2>.withTag({}),
    <thermalinnovation:injector:3>.withTag({}),
    <thermalinnovation:injector:4>.withTag({}),
    <thermalinnovation:injector:32000>.withTag({}),
    <thermalinnovation:quiver>.withTag({}),
    <thermalinnovation:quiver:1>.withTag({}),
    <thermalinnovation:quiver:2>.withTag({}),
    <thermalinnovation:quiver:3>.withTag({}),
    <thermalinnovation:quiver:4>.withTag({}),
    <thermalinnovation:quiver:32000>.withTag({}),
    <thermallogistics:requester>,
    <thermallogistics:requester:1>,
    <thermallogistics:requester:3>,
    <thermallogistics:requester:2>,
    <thermallogistics:requester:4>,
    <thermallogistics:crafter>,
    <thermallogistics:crafter:1>,
    <thermallogistics:crafter:2>,
    <thermallogistics:crafter:3>,
    <thermallogistics:crafter:4>,
    <thermallogistics:distributor>,
    <thermallogistics:distributor:1>,
    <thermallogistics:distributor:2>,
    <thermallogistics:distributor:3>,
    <thermallogistics:distributor:4>,
    <thermallogistics:manager>,
    <thermallogistics:terminal_item>,
//industrial foregoing
    <industrialforegoing:petrified_fuel_generator>,
    <industrialforegoing:enchantment_refiner>,
    <industrialforegoing:enchantment_extractor>,
    <industrialforegoing:enchantment_aplicator>,
    <industrialforegoing:mob_relocator>,
    <industrialforegoing:potion_enervator>,
    <industrialforegoing:animal_independence_selector>,
    <industrialforegoing:animal_stock_increaser>,
    <industrialforegoing:crop_sower>,
    <industrialforegoing:crop_enrich_material_injector>,
    <industrialforegoing:crop_recolector>,
    <industrialforegoing:black_hole_unit>,
    <industrialforegoing:water_condensator>,
    <industrialforegoing:water_resources_collector>,
    <industrialforegoing:animal_resource_harvester>,
    <industrialforegoing:mob_slaughter_factory>,
    <industrialforegoing:mob_duplicator>,
    <industrialforegoing:block_destroyer>,
    <industrialforegoing:block_placer>,
    <industrialforegoing:sewage_composter_solidifier>,
    <industrialforegoing:animal_byproduct_recolector>,
    <industrialforegoing:sludge_refiner>,
    <industrialforegoing:mob_detector>,
    <industrialforegoing:lava_fabricator>,
    <industrialforegoing:bioreactor>,
    <industrialforegoing:biofuel_generator>,
    <industrialforegoing:laser_base>,
    <industrialforegoing:laser_drill>,
    <industrialforegoing:ore_processor>,
    <industrialforegoing:black_hole_controller>,
    <industrialforegoing:dye_mixer>,
    <industrialforegoing:enchantment_invoker>,
    <industrialforegoing:spores_recreator>,
    <industrialforegoing:animal_growth_increaser>,
    <industrialforegoing:material_stonework_factory>,
    <industrialforegoing:black_hole_tank>,
    <industrialforegoing:resourceful_furnace>,
    <industrialforegoing:villager_trade_exchanger>,
    <industrialforegoing:energy_field_provider>,
    <industrialforegoing:oredictionary_converter>,
    <industrialforegoing:protein_reactor>,
    <industrialforegoing:protein_generator>,
    <industrialforegoing:hydrator>,
    <industrialforegoing:wither_builder>,
    <industrialforegoing:fluid_pump>,
    <industrialforegoing:fluid_crafter>,
    <industrialforegoing:plant_interactor>,
    <industrialforegoing:item_splitter>,
    <industrialforegoing:fluiddictionary_converter>,
    <industrialforegoing:froster>,
    <industrialforegoing:ore_washer>,
    <industrialforegoing:ore_fermenter>,
    <industrialforegoing:ore_sieve>,
    <industrialforegoing:pitiful_fuel_generator>,
    <industrialforegoing:plastic>,
    <industrialforegoing:fertilizer>,
    <industrialforegoing:meat_feeder>,
    <industrialforegoing:mob_imprisonment_tool>,
    <industrialforegoing:laser_lens>,
    <industrialforegoing:laser_lens:1>,
    <industrialforegoing:laser_lens:2>,
    <industrialforegoing:laser_lens:3>,
    <industrialforegoing:laser_lens:4>,
    <industrialforegoing:laser_lens:5>,
    <industrialforegoing:laser_lens:6>,
    <industrialforegoing:laser_lens:7>,
    <industrialforegoing:laser_lens:8>,
    <industrialforegoing:laser_lens:9>,
    <industrialforegoing:laser_lens:10>,
    <industrialforegoing:laser_lens:11>,
    <industrialforegoing:laser_lens:12>,
    <industrialforegoing:laser_lens:13>,
    <industrialforegoing:laser_lens:14>,
    <industrialforegoing:laser_lens:15>,
    <industrialforegoing:laser_lens_inverted>,
    <industrialforegoing:laser_lens_inverted:1>,
    <industrialforegoing:laser_lens_inverted:2>,
    <industrialforegoing:laser_lens_inverted:3>,
    <industrialforegoing:laser_lens_inverted:4>,
    <industrialforegoing:laser_lens_inverted:5>,
    <industrialforegoing:laser_lens_inverted:6>,
    <industrialforegoing:laser_lens_inverted:7>,
    <industrialforegoing:laser_lens_inverted:8>,
    <industrialforegoing:laser_lens_inverted:9>,
    <industrialforegoing:laser_lens_inverted:10>,
    <industrialforegoing:laser_lens_inverted:11>,
    <industrialforegoing:laser_lens_inverted:12>,
    <industrialforegoing:laser_lens_inverted:13>,
    <industrialforegoing:laser_lens_inverted:14>,
    <industrialforegoing:laser_lens_inverted:15>,
    <industrialforegoing:straw>,
    <industrialforegoing:conveyor_upgrade>,
    <industrialforegoing:conveyor_upgrade:1>,
    <industrialforegoing:conveyor_upgrade:2>,
    <industrialforegoing:conveyor_upgrade:3>,
    <industrialforegoing:conveyor_upgrade:4>,
    <industrialforegoing:conveyor_upgrade:5>,
    <industrialforegoing:conveyor_upgrade:6>,
    <industrialforegoing:pink_slime>,
    <industrialforegoing:book_manual>,
    <industrialforegoing:infinity_drill>.withTag({Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0}, Special: 0 as byte, Selected: "POOR"}),
    <industrialforegoing:infinity_drill>.withTag({Energy: 4000000 as long, Fluid: {FluidName: "biofuel", Amount: 0}, Special: 0 as byte, Selected: "COMMON"}),
    <industrialforegoing:infinity_drill>.withTag({Energy: 16000000 as long, Fluid: {FluidName: "biofuel", Amount: 0}, Special: 0 as byte, Selected: "UNCOMMON"}),
    <industrialforegoing:infinity_drill>.withTag({Energy: 80000000 as long, Fluid: {FluidName: "biofuel", Amount: 0}, Special: 0 as byte, Selected: "RARE"}),
    <industrialforegoing:infinity_drill>.withTag({Energy: 480000000 as long, Fluid: {FluidName: "biofuel", Amount: 0}, Special: 0 as byte, Selected: "EPIC"}),
    <industrialforegoing:infinity_drill>.withTag({Energy: 3360000000 as long, Fluid: {FluidName: "biofuel", Amount: 0}, Special: 0 as byte, Selected: "LEGENDARY"}),
    <industrialforegoing:infinity_drill>.withTag({Energy: 9223372036854775807 as long, Fluid: {FluidName: "biofuel", Amount: 0}, Special: 0 as byte, Selected: "ARTIFACT"}),
    <industrialforegoing:infinity_drill>.withTag({Energy: 9223372036854775807 as long, Fluid: {FluidName: "biofuel", Amount: 1000000}, Special: 1 as byte, Selected: "ARTIFACT"}),
    <industrialforegoing:adult_filter>,
    <industrialforegoing:range_addon>,
    <industrialforegoing:range_addon:1>,
    <industrialforegoing:range_addon:2>,
    <industrialforegoing:range_addon:3>,
    <industrialforegoing:range_addon:4>,
    <industrialforegoing:range_addon:5>,
    <industrialforegoing:range_addon:6>,
    <industrialforegoing:range_addon:7>,
    <industrialforegoing:range_addon:8>,
    <industrialforegoing:range_addon:9>,
    <industrialforegoing:range_addon:10>,
    <industrialforegoing:range_addon:11>,
    <industrialforegoing:energy_field_addon>,
    <industrialforegoing:leaf_shearing>,
    <industrialforegoing:itemstack_transfer_addon_pull>,
    <industrialforegoing:itemstack_transfer_addon_push>,
    <industrialforegoing:fluid_transfer_addon_pull>,
    <industrialforegoing:fluid_transfer_addon_push>,
    <industrialforegoing:fortune_addon>,
    <industrialforegoing:artificial_dye>,
    <industrialforegoing:artificial_dye:1>,
    <industrialforegoing:artificial_dye:2>,
    <industrialforegoing:artificial_dye:3>,
    <industrialforegoing:artificial_dye:4>,
    <industrialforegoing:artificial_dye:5>,
    <industrialforegoing:artificial_dye:6>,
    <industrialforegoing:artificial_dye:7>,
    <industrialforegoing:artificial_dye:8>,
    <industrialforegoing:artificial_dye:9>,
    <industrialforegoing:artificial_dye:10>,
    <industrialforegoing:artificial_dye:11>,
    <industrialforegoing:artificial_dye:12>,
    <industrialforegoing:artificial_dye:13>,
    <industrialforegoing:artificial_dye:14>,
    <industrialforegoing:artificial_dye:15>,
    <industrialforegoing:conveyor>,
    <industrialforegoing:conveyor:1>,
    <industrialforegoing:conveyor:2>,
    <industrialforegoing:conveyor:3>,
    <industrialforegoing:conveyor:4>,
    <industrialforegoing:conveyor:5>,
    <industrialforegoing:conveyor:6>,
    <industrialforegoing:conveyor:7>,
    <industrialforegoing:conveyor:8>,
    <industrialforegoing:conveyor:9>,
    <industrialforegoing:conveyor:10>,
    <industrialforegoing:conveyor:11>,
    <industrialforegoing:conveyor:12>,
    <industrialforegoing:conveyor:13>,
    <industrialforegoing:conveyor:14>,
    <industrialforegoing:conveyor:15>,
    <industrialforegoing:black_hole_label>,
    <industrialforegoing:black_hole_controller_reworked>,
//environmentaltech
    <environmentaltech:litherite>,
    <environmentaltech:litherite_paver>,
    <environmentaltech:litherite_bricks>,
    <environmentaltech:litherite_tiles>,
    <environmentaltech:litherite_stairs>,
    <environmentaltech:litherite_brick_stairs>,
    <environmentaltech:litherite_tile_stairs>,
    <environmentaltech:litherite_slab>,
    <environmentaltech:litherite_paver_slab>,
    <environmentaltech:litherite_brick_slab>,
    <environmentaltech:litherite_tile_slab>,
    <environmentaltech:erodium>,
    <environmentaltech:erodium_paver>,
    <environmentaltech:erodium_bricks>,
    <environmentaltech:erodium_tiles>,
    <environmentaltech:erodium_stairs>,
    <environmentaltech:erodium_brick_stairs>,
    <environmentaltech:erodium_tile_stairs>,
    <environmentaltech:erodium_slab>,
    <environmentaltech:erodium_paver_slab>,
    <environmentaltech:erodium_brick_slab>,
    <environmentaltech:erodium_tile_slab>,
    <environmentaltech:kyronite>,
    <environmentaltech:kyronite_paver>,
    <environmentaltech:kyronite_bricks>,
    <environmentaltech:kyronite_tiles>,
    <environmentaltech:kyronite_stairs>,
    <environmentaltech:kyronite_brick_stairs>,
    <environmentaltech:kyronite_tile_stairs>,
    <environmentaltech:kyronite_slab>,
    <environmentaltech:kyronite_paver_slab>,
    <environmentaltech:kyronite_brick_slab>,
    <environmentaltech:kyronite_tile_slab>,
    <environmentaltech:pladium>,
    <environmentaltech:pladium_paver>,
    <environmentaltech:pladium_bricks>,
    <environmentaltech:pladium_tiles>,
    <environmentaltech:pladium_stairs>,
    <environmentaltech:pladium_brick_stairs>,
    <environmentaltech:pladium_tile_stairs>,
    <environmentaltech:pladium_slab>,
    <environmentaltech:pladium_paver_slab>,
    <environmentaltech:pladium_brick_slab>,
    <environmentaltech:pladium_tile_slab>,
    <environmentaltech:ionite>,
    <environmentaltech:ionite_paver>,
    <environmentaltech:ionite_bricks>,
    <environmentaltech:ionite_tiles>,
    <environmentaltech:ionite_stairs>,
    <environmentaltech:ionite_brick_stairs>,
    <environmentaltech:ionite_tile_stairs>,
    <environmentaltech:ionite_slab>,
    <environmentaltech:ionite_paver_slab>,
    <environmentaltech:ionite_brick_slab>,
    <environmentaltech:ionite_tile_slab>,
    <environmentaltech:aethium>,
    <environmentaltech:aethium_paver>,
    <environmentaltech:aethium_bricks>,
    <environmentaltech:aethium_tiles>,
    <environmentaltech:aethium_stairs>,
    <environmentaltech:aethium_brick_stairs>,
    <environmentaltech:aethium_tile_stairs>,
    <environmentaltech:aethium_slab>,
    <environmentaltech:aethium_paver_slab>,
    <environmentaltech:aethium_brick_slab>,
    <environmentaltech:aethium_tile_slab>,
    <environmentaltech:lonsdaleite>,
    <environmentaltech:lonsdaleite_paver>,
    <environmentaltech:lonsdaleite_bricks>,
    <environmentaltech:lonsdaleite_tiles>,
    <environmentaltech:lonsdaleite_stairs>,
    <environmentaltech:lonsdaleite_brick_stairs>,
    <environmentaltech:lonsdaleite_tile_stairs>,
    <environmentaltech:lonsdaleite_slab>,
    <environmentaltech:lonsdaleite_paver_slab>,
    <environmentaltech:lonsdaleite_brick_slab>,
    <environmentaltech:lonsdaleite_tile_slab>,
    <environmentaltech:mica>,
    <environmentaltech:litherite_crystal>,
    <environmentaltech:erodium_crystal>,
    <environmentaltech:kyronite_crystal>,
    <environmentaltech:pladium_crystal>,
    <environmentaltech:ionite_crystal>,
    <environmentaltech:aethium_crystal>,
    <environmentaltech:lonsdaleite_crystal>,
    <environmentaltech:interconnect>,
    <environmentaltech:tool_multiblock_assembler>,
    <environmentaltech:connector>,
    <environmentaltech:modifier_null>,
    <environmentaltech:modifier_speed>,
    <environmentaltech:modifier_luck>,
    <environmentaltech:structure_frame_1>,
    <environmentaltech:structure_frame_2>,
    <environmentaltech:structure_frame_3>,
    <environmentaltech:structure_frame_4>,
    <environmentaltech:structure_frame_5>,
    <environmentaltech:structure_frame_6>,
    <environmentaltech:structure_panel>,
    <environmentaltech:structure_panel_clear>,
    <environmentaltech:lightning_rod>,
    <environmentaltech:lightning_rod_insulated>,
    <environmentaltech:lightning_cont_1>,
    <environmentaltech:lightning_cont_2>,
    <environmentaltech:lightning_cont_3>,
    <environmentaltech:lightning_cont_4>,
    <environmentaltech:lightning_cont_5>,
    <environmentaltech:lightning_cont_6>,
    <environmentaltech:solar_cont_1>,
    <environmentaltech:solar_cont_2>,
    <environmentaltech:solar_cont_3>,
    <environmentaltech:solar_cont_4>,
    <environmentaltech:solar_cont_5>,
    <environmentaltech:solar_cont_6>,
    <environmentaltech:solar_cell_litherite>,
    <environmentaltech:solar_cell_erodium>,
    <environmentaltech:solar_cell_kyronite>,
    <environmentaltech:solar_cell_pladium>,
    <environmentaltech:solar_cell_ionite>,
    <environmentaltech:solar_cell_aethium>,
    <environmentaltech:modifier_piezo>,
    <environmentaltech:photovoltaic_cell>,
    <environmentaltech:thermal_cell>,
    <environmentaltech:laser_core>,
    <environmentaltech:laser_lens>,
    <environmentaltech:laser_lens_crystal>,
    <environmentaltech:modifier_accuracy>,
    <environmentaltech:diode>,
    <environmentaltech:void_ore_miner_cont_1>,
    <environmentaltech:void_ore_miner_cont_2>,
    <environmentaltech:void_ore_miner_cont_3>,
    <environmentaltech:void_ore_miner_cont_4>,
    <environmentaltech:void_ore_miner_cont_5>,
    <environmentaltech:void_ore_miner_cont_6>,
    <environmentaltech:void_res_miner_cont_1>,
    <environmentaltech:void_res_miner_cont_2>,
    <environmentaltech:void_res_miner_cont_3>,
    <environmentaltech:void_res_miner_cont_4>,
    <environmentaltech:void_res_miner_cont_5>,
    <environmentaltech:void_res_miner_cont_6>,
    <environmentaltech:void_botanic_miner_cont_1>,
    <environmentaltech:void_botanic_miner_cont_2>,
    <environmentaltech:void_botanic_miner_cont_3>,
    <environmentaltech:void_botanic_miner_cont_4>,
    <environmentaltech:void_botanic_miner_cont_5>,
    <environmentaltech:void_botanic_miner_cont_6>,
    <environmentaltech:modifier_haste>,
    <environmentaltech:modifier_strength>,
    <environmentaltech:modifier_jump_boost>,
    <environmentaltech:modifier_regeneration>,
    <environmentaltech:modifier_resistance>,
    <environmentaltech:modifier_fire_resistance>,
    <environmentaltech:modifier_water_breathing>,
    <environmentaltech:modifier_invisibility>,
    <environmentaltech:modifier_night_vision>,
    <environmentaltech:modifier_health_boost>,
    <environmentaltech:modifier_absorption>,
    <environmentaltech:modifier_saturation>,
    <environmentaltech:modifier_glowing>,
    <environmentaltech:nano_cont_ranged_1>,
    <environmentaltech:nano_cont_ranged_2>,
    <environmentaltech:nano_cont_ranged_3>,
    <environmentaltech:nano_cont_ranged_4>,
    <environmentaltech:nano_cont_ranged_5>,
    <environmentaltech:nano_cont_ranged_6>,
    <environmentaltech:nano_cont_personal_1>,
    <environmentaltech:nano_cont_personal_2>,
    <environmentaltech:nano_cont_personal_3>,
    <environmentaltech:nano_cont_personal_4>,
    <environmentaltech:nano_cont_personal_5>,
    <environmentaltech:nano_cont_personal_6>,
    <environmentaltech:laser_lens_colored>,
    <environmentaltech:laser_lens_colored:1>,
    <environmentaltech:laser_lens_colored:2>,
    <environmentaltech:laser_lens_colored:3>,
    <environmentaltech:laser_lens_colored:4>,
    <environmentaltech:laser_lens_colored:5>,
    <environmentaltech:laser_lens_colored:6>,
    <environmentaltech:laser_lens_colored:7>,
    <environmentaltech:laser_lens_colored:8>,
    <environmentaltech:laser_lens_colored:9>,
    <environmentaltech:laser_lens_colored:10>,
    <environmentaltech:laser_lens_colored:11>,
    <environmentaltech:laser_lens_colored:12>,
    <environmentaltech:laser_lens_colored:13>,
    <environmentaltech:laser_lens_colored:14>,
    <environmentaltech:laser_lens_colored:15>,
    <valkyrielib:modifier_component>,
    <valkyrielib:modifier_speed>,

//compactmachines
    <compactmachines3:wallbreakable>,
    <compactmachines3:machine>,
    <compactmachines3:machine:1>,
    <compactmachines3:machine:2>,
    <compactmachines3:machine:3>,
    <compactmachines3:machine:4>,
    <compactmachines3:machine:5>,
    <compactmachines3:fieldprojector>,
    <compactmachines3:psd>,
    <compactmachines3:tunneltool>,
    <compactmachines3:redstonetunneltool>,
//rftools
    <rftoolspower:power_core1>,
    <rftoolspower:power_core2>,
    <rftoolspower:power_core3>,
    <rftoolspower:cell1>,
    <rftoolspower:cell2>,
    <rftoolspower:cell3>,
    <rftools:smartwrench>,
    <rftools:rftools_manual>,
    <rftools:rftools_shape_manual>,
    <rftools:dimensional_shard>,
    <rftools:shard_wand>,
    <rftools:infused_diamond>,
    <rftools:infused_enderpearl>,
    <rftools:syringe>,
    <rftools:peace_essence>,
    <rftools:developers_delight>,
    <rftools:network_monitor>,
    <rftools:modifier_module>,
    <rftools:storage_module_tablet>,
    <rftools:storage_module>,
    <rftools:storage_module:1>,
    <rftools:storage_module:2>,
    <rftools:storage_module:6>,
    <rftools:oredict_module>,
    <rftools:generic_module>,
    <rftools:filter_module>,
    <rftools:teleport_probe>,
    <rftools:charged_porter>,
    <rftools:advanced_charged_porter>,
    <rftools:text_module>,
    <rftools:inventory_module>,
    <rftools:inventoryplus_module>,
    <rftools:energy_module>,
    <rftools:energyplus_module>,
    <rftools:clock_module>,
    <rftools:fluid_module>,
    <rftools:fluidplus_module>,
    <rftools:machineinformation_module>,
    <rftools:computer_module>,
    <rftools:button_module>,
    <rftools:elevator_button_module>,
    <rftools:redstone_module>,
    <rftools:counter_module>,
    <rftools:counterplus_module>,
    <rftools:storage_control_module>,
    <rftools:dump_module>,
    <rftools:space_chamber_card>,
    <rftools:shape_card>,
    <rftools:shape_card:1>,
    <rftools:shape_card:2>,
    <rftools:shape_card:3>,
    <rftools:shape_card:3>,
    <rftools:shape_card:4>,
    <rftools:shape_card:5>,
    <rftools:shape_card:6>,
    <rftools:shape_card:7>,
    <rftools:shape_card:8>,
    <rftools:shape_card:9>,
    <rftools:shape_card:10>,
    <rftools:powercell_card>,
    <rftools:regeneration_module>,
    <rftools:regenerationplus_module>,
    <rftools:speed_module>,
    <rftools:speedplus_module>,
    <rftools:haste_module>,
    <rftools:hasteplus_module>,
    <rftools:saturation_module>,
    <rftools:saturationplus_module>,
    <rftools:featherfalling_module>,
    <rftools:featherfallingplus_module>,
    <rftools:peaceful_module>,
    <rftools:waterbreathing_module>,
    <rftools:nightvision_module>,
    <rftools:blindness_module>,
    <rftools:weakness_module>,
    <rftools:poison_module>,
    <rftools:slowness_module>,
    <rftools:glowing_module>,
    <rftools:luck_module>,
    <rftools:noteleport_module>,
    <rftools:orphaning_card>,
    <rftools:security_card>,
    <rftools:machine_frame>,
    <rftools:machine_base>,
    <rftools:dimensional_shard_ore:1>,
    <rftools:dimensional_shard_ore:2>,
    <rftools:coalgenerator>,
    <rftools:crafter1>,
    <rftools:crafter2>,
    <rftools:crafter3>,
    <rftools:modular_storage>,
    <rftools:remote_storage>,
    <rftools:matter_transmitter>,
    <rftools:matter_receiver>,
    <rftools:dialing_device>,
    <rftools:destination_analyzer>,
    <rftools:matter_booster>,
    <rftools:screen>,
    <rftools:creative_screen>,
    <rftools:screen_controller>,
    <rftools:redstone_transmitter_block>,
    <rftools:redstone_receiver_block>,
    <rftools:sequencer_block>,
    <rftools:counter_block>,
    <rftools:logic_block>,
    <rftools:invchecker_block>,
    <rftools:sensor_block>,
    <rftools:analog_block>,
    <rftools:digit_block>,
    <rftools:wire_block>,
    <rftools:timer_block>,
    <rftools:machine_infuser>,
    <rftools:space_chamber>,
    <rftools:space_chamber_controller>,
    <rftools:support_block>,
    <rftools:builder>,
    <rftools:composer>,
    <rftools:locator>,
    <rftools:projector>,
    <rftools:scanner>,
    <rftools:remote_scanner>,
    <rftools:powercell>,
    <rftools:powercell_advanced>,
    <rftools:powercell_creative>,
    <rftools:powercell_simple>,
    <rftools:relay>,
    <rftools:rf_monitor>,
    <rftools:liquid_monitor>,
    <rftools:shield_block1>,
    <rftools:shield_block2>,
    <rftools:shield_block3>,
    <rftools:shield_block4>,
    <rftools:shield_template_block>,
    <rftools:shield_template_block:1>,
    <rftools:shield_template_block:2>,
    <rftools:shield_template_block:3>,
    <rftools:environmental_controller>,
    <rftools:spawner>,
    <rftools:matter_beamer>,
    <rftools:block_protector>,
    <rftools:item_filter>,
    <rftools:security_manager>,
    <rftools:endergenic>,
    <rftools:pearl_injector>,
    <rftools:ender_monitor>,
    <rftools:storage_scanner>,
    <rftools:elevator>,
    <rftools:booster>,
    <rftools:storage_terminal>,
    <rftools:level_emitter>,
    <rftools:simple_dialer>,
    <rftoolscontrol:rftoolscontrol_manual>,
    <rftoolscontrol:program_card>,
    <rftoolscontrol:cpu_core_500>,
    <rftoolscontrol:cpu_core_1000>,
    <rftoolscontrol:cpu_core_2000>,
    <rftoolscontrol:ram_chip>,
    <rftoolscontrol:network_card>,
    <rftoolscontrol:advanced_network_card>,
    <rftoolscontrol:card_base>,
    <rftoolscontrol:crafting_card>,
    <rftoolscontrol:token>,
    <rftoolscontrol:network_identifier>,
    <rftoolscontrol:graphics_card>,
    <rftoolscontrol:variable_module>,
    <rftoolscontrol:interaction_module>,
    <rftoolscontrol:console_module>,
    <rftoolscontrol:vectorart_module>,
    <rftoolscontrol:programmer>,
    <rftoolscontrol:processor>,
    <rftoolscontrol:node>,
    <rftoolscontrol:craftingstation>,
    <rftoolscontrol:workbench>,
    <rftoolscontrol:tank>,
    <rftoolspower:information_screen>,
//xnet
    <xnet:xnet_manual>,
    <xnet:connector_upgrade>,
    <xnet:facade>,
    <xnet:redstone_proxy>,
    <xnet:redstone_proxy_upd>,
    <xnet:netcable>.withTag({display: {LocName: "tile.xnet.netcable_blue.name"}}),
    <xnet:netcable:1>.withTag({display: {LocName: "tile.xnet.netcable_red.name"}}),
    <xnet:netcable:2>.withTag({display: {LocName: "tile.xnet.netcable_yellow.name"}}),
    <xnet:netcable:3>.withTag({display: {LocName: "tile.xnet.netcable_green.name"}}),
    <xnet:netcable:4>.withTag({display: {LocName: "tile.xnet.netcable_routing.name"}}),
    <xnet:connector>.withTag({display: {LocName: "tile.xnet.connector_blue.name"}}),
    <xnet:connector:1>.withTag({display: {LocName: "tile.xnet.connector_red.name"}}),
    <xnet:connector:2>.withTag({display: {LocName: "tile.xnet.connector_yellow.name"}}),
    <xnet:connector:3>.withTag({display: {LocName: "tile.xnet.connector_green.name"}}),
    <xnet:connector:4>.withTag({display: {LocName: "tile.xnet.connector_routing.name"}}),
    <xnet:advanced_connector>.withTag({display: {LocName: "tile.xnet.advanced_connector_blue.name"}}),
    <xnet:advanced_connector:1>.withTag({display: {LocName: "tile.xnet.advanced_connector_red.name"}}),
    <xnet:advanced_connector:2>.withTag({display: {LocName: "tile.xnet.advanced_connector_yellow.name"}}),
    <xnet:advanced_connector:3>.withTag({display: {LocName: "tile.xnet.advanced_connector_green.name"}}),
    <xnet:controller>,
    <xnet:router>,
    <xnet:wireless_router>,
    <xnet:antenna>,
    <xnet:antenna_base>,
    <xnet:antenna_dish>,
//ex2
    <extrautils2:snowglobe>,
    <extrautils2:itembuilderswand>,
    <extrautils2:itemdestructionwand>,
    <extrautils2:decorativesolidwood>,
    <extrautils2:decorativesolidwood:2>,
    <extrautils2:angelblock>,
    <extrautils2:passivegenerator>,
    <extrautils2:passivegenerator:1>,
    <extrautils2:passivegenerator:2>,
    <extrautils2:passivegenerator:3>,
    <extrautils2:passivegenerator:4>,
    <extrautils2:passivegenerator:5>,
    <extrautils2:passivegenerator:7>,
    <extrautils2:passivegenerator:8>,
    <extrautils2:redstoneclock>,
    <extrautils2:glasscutter>,
    <extrautils2:endershard>,
    <extrautils2:poweroverload>,
    <extrautils2:resonator>,
    <extrautils2:suncrystal>,
    <extrautils2:suncrystal:250>,
    <extrautils2:screen>,
    <extrautils2:ingredients:1>,
    <extrautils2:ingredients:2>,
    <extrautils2:ingredients:6>,
    <extrautils2:ingredients:7>,
    <extrautils2:ingredients:8>,
    <extrautils2:ingredients:15>,
    <extrautils2:ingredients:16>,
    <extrautils2:chickenring>,
    <extrautils2:chickenring:1>,
    <extrautils2:powermanager>,
    <extrautils2:bagofholding>,
    <extrautils2:pipe>,
    <extrautils2:playerchest>,
    <extrautils2:wrench>,
    <extrautils2:boomerang>,
    <extrautils2:book>,
    <extrautils2:contract>,
    <extrautils2:chunkloader>,
    <extrautils2:filter>,
    <extrautils2:filterfluids>,
    <extrautils2:grocket>,
    <extrautils2:grocket:1>,
    <extrautils2:grocket:2>,
    <extrautils2:grocket:3>,
    <extrautils2:grocket:4>,
    <extrautils2:grocket:5>,
    <extrautils2:grocket:6>,
    <extrautils2:indexer>,
    <extrautils2:indexerremote>,
    <extrautils2:crafter>,
    <extrautils2:scanner>,
    <extrautils2:miner>,
    <extrautils2:user>,
    <extrautils2:klein>,
    <extrautils2:drum>,
    <extrautils2:drum:1>,
    <extrautils2:drum:2>,
    <extrautils2:drum:3>,
    <extrautils2:machine>.withTag({Type:"extrautils2:furnace"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:crusher"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:enchanter"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_survival"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_culinary"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_lava"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_redstone"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_ender"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_potion"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_pink"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_overclock"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_tnt"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_netherstar"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_dragonsbreath"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_ice"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_death"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_enchant"}),
    <extrautils2:machine>.withTag({Type:"extrautils2:generator_slime"}),
    <extrautils2:teleporter:1>,
    <extrautils2:powertransmitter>,
    <extrautils2:powerbattery>,
    <extrautils2:spike_wood>,
    <extrautils2:spike_stone>,
    <extrautils2:spike_iron>,
    <extrautils2:spike_gold>,
    <extrautils2:spike_diamond>,
    <extrautils2:redstonelantern>,
    <extrautils2:rainbowgenerator>,
    <extrautils2:rainbowgenerator:1>,
    <extrautils2:rainbowgenerator:2>,
    <extrautils2:magicapple>,
    <extrautils2:trowel>,
    <extrautils2:biomemarker>,
    <extrautils2:terraformer>,
    <extrautils2:terraformer:1>,
    <extrautils2:terraformer:2>,
    <extrautils2:terraformer:3>,
    <extrautils2:terraformer:4>,
    <extrautils2:terraformer:5>,
    <extrautils2:terraformer:6>,
    <extrautils2:terraformer:7>,
    <extrautils2:terraformer:8>,
    <extrautils2:terraformer:9>,
    <extrautils2:opinium>,
    <extrautils2:opinium:1>,
    <extrautils2:opinium:2>,
    <extrautils2:opinium:3>,
    <extrautils2:opinium:4>,
    <extrautils2:opinium:5>,
    <extrautils2:opinium:6>,
    <extrautils2:opinium:7>,
    <extrautils2:opinium:8>,
    <extrautils2:lawsword>,
    <extrautils2:flattransfernode>,
    <extrautils2:flattransfernode:1>,
    <extrautils2:analogcrafter>,
    <extrautils2:compoundbow>,
    <extrautils2:fireaxe>,
    <extrautils2:interactionproxy>,
    <extrautils2:luxsaber:*>,
//rftoolsdim
    <rftoolsdim:dimlet_base>,
    <rftoolsdim:dimlet_control_circuit>,
    <rftoolsdim:dimlet_control_circuit:1>,
    <rftoolsdim:dimlet_control_circuit:2>,
    <rftoolsdim:dimlet_control_circuit:3>,
    <rftoolsdim:dimlet_control_circuit:4>,
    <rftoolsdim:dimlet_control_circuit:5>,
    <rftoolsdim:dimlet_control_circuit:6>,
    <rftoolsdim:dimlet_energy_module>,
    <rftoolsdim:dimlet_energy_module:1>,
    <rftoolsdim:dimlet_energy_module:2>,
    <rftoolsdim:dimlet_memory_unit>,
    <rftoolsdim:dimlet_memory_unit:1>,
    <rftoolsdim:dimlet_memory_unit:2>,
    <rftoolsdim:dimlet_type_controller>,
    <rftoolsdim:dimlet_type_controller:1>,
    <rftoolsdim:dimlet_type_controller:2>,
    <rftoolsdim:dimlet_type_controller:3>,
    <rftoolsdim:dimlet_type_controller:4>,
    <rftoolsdim:dimlet_type_controller:5>,
    <rftoolsdim:dimlet_type_controller:6>,
    <rftoolsdim:dimlet_type_controller:7>,
    <rftoolsdim:dimlet_type_controller:8>,
    <rftoolsdim:dimlet_type_controller:9>,
    <rftoolsdim:dimlet_type_controller:10>,
    <rftoolsdim:dimlet_type_controller:11>,
    <rftoolsdim:dimlet_type_controller:12>,
    <rftoolsdim:dimlet_type_controller:13>,
    <rftoolsdim:dimlet_type_controller:14>,
    <rftoolsdim:structure_essence>,
    <rftoolsdim:structure_essence:1>,
    <rftoolsdim:structure_essence:2>,
    <rftoolsdim:structure_essence:3>,
    <rftoolsdim:structure_essence:4>,
    <rftoolsdim:structure_essence:5>,
    <rftoolsdim:structure_essence:6>,
    <rftoolsdim:structure_essence:7>,
    <rftoolsdim:structure_essence:8>,
    <rftoolsdim:structure_essence:9>,
    <rftoolsdim:structure_essence:10>,
    <rftoolsdim:structure_essence:11>,
    <rftoolsdim:known_dimlet:10>.withTag({dkey: "None"}),
    <rftoolsdim:known_dimlet:8>.withTag({dkey: "Normal"}),
    <rftoolsdim:known_dimlet:3>.withTag({dkey: "Default"}),
    <rftoolsdim:known_dimlet:4>.withTag({dkey: "normal.night"}),
    <rftoolsdim:known_dimlet:6>.withTag({dkey: "Void"}),
    <rftoolsdim:known_dimlet:12>.withTag({dkey: "Default"}),
    <rftoolsdim:known_dimlet:6>.withTag({dkey: "Flat"}),
    <rftoolsdim:known_dimlet:12>.withTag({dkey: "Single"}),
    <rftoolsdim:known_dimlet:13>.withTag({dkey: "Default"}),
    <rftoolsdim:known_dimlet:5>.withTag({dkey: "None"}),
    <rftoolsdim:known_dimlet:9>.withTag({dkey: "0"}),
    <rftoolsdim:known_dimlet:9>.withTag({dkey: "2"}),
    <rftoolsdim:known_dimlet:9>.withTag({dkey: "1"}),
    <rftoolsdim:known_dimlet:9>.withTag({dkey: "4"}),
    <rftoolsdim:known_dimlet:9>.withTag({dkey: "3"}),
    <rftoolsdim:known_dimlet:9>.withTag({dkey: "6"}),
    <rftoolsdim:known_dimlet:9>.withTag({dkey: "5"}),
    <rftoolsdim:known_dimlet:2>.withTag({dkey: "minecraft:stone@0"}),
    <rftoolsdim:known_dimlet:9>.withTag({dkey: "8"}),
    <rftoolsdim:known_dimlet:9>.withTag({dkey: "7"}),
    <rftoolsdim:known_dimlet:4>.withTag({dkey: "normal"}),
    <rftoolsdim:known_dimlet:4>.withTag({dkey: "normal.day"}),
    <rftoolsdim:known_dimlet:9>.withTag({dkey: "9"}),
    <rftoolsdim:known_dimlet:7>.withTag({dkey: "None"}),
    <rftoolsdim:known_dimlet:1>.withTag({dkey: "minecraft:water@0"}),
    <rftoolsdim:efficiency_essence>,
    <rftoolsdim:mediocre_efficiency_essence>,
    <rftoolsdim:empty_dimension_tab>,
    <rftoolsdim:dimlet_template>,
    <rftoolsdim:dimlet_parcel>,
    <rftoolsdim:rftoolsdim_manual>,
    <rftoolsdim:dimension_monitor>,
    <rftoolsdim:dimension_module>,
    <rftoolsdim:phased_field_generator>,
    <rftoolsdim:dimensional_blank_block>,
    <rftoolsdim:dimensional_block>,
    <rftoolsdim:dimensional_cross2_block>,
    <rftoolsdim:dimensional_cross_block>,
    <rftoolsdim:dimensional_pattern1_block>,
    <rftoolsdim:dimensional_pattern2_block>,
    <rftoolsdim:dimensional_small_blocks>,
    <rftoolsdim:dimension_enscriber>,
    <rftoolsdim:dimension_builder>,
    <rftoolsdim:dimension_editor>,
    <rftoolsdim:dimlet_workbench>,
    <rftoolsdim:activity_probe>,
    <rftoolsdim:energy_extractor>,
    <rftoolsdim:material_absorber>,
    <rftoolsdim:liquid_absorber>,
    <rftoolsdim:biome_absorber>,
    <rftoolsdim:terrain_absorber>,
    <rftoolsdim:feature_absorber>,
    <rftoolsdim:time_absorber>,
    <rftoolsdim:fake_water>,
    <rftoolsdim:fake_gravel>,
    <rftoolsdim:fake_sand>,
// tesla core lib
    <teslacorelib:base_addon>,
    <teslacorelib:energy_tier1>,
    <teslacorelib:energy_tier2>,
    <teslacorelib:machine_case>,
    <teslacorelib:speed_tier1>,
    <teslacorelib:speed_tier2>,
    <teslacorelib:wrench>

];

for item in advancedtechstage {
    mods.recipestages.Recipes.setRecipeStage("advancedtech", item);
    mods.ItemStages.addItemStage("advancedtech", item);
}