//#priority 349
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

val conarmstage as IItemStack[] = [
    <conarm:resist_mat>,
    <conarm:invisible_ink>,
    <conarm:resist_mat_fire>,
    <conarm:resist_mat_proj>,
    <conarm:resist_mat_blast>,
    <conarm:gauntlet_mat>,
    <conarm:gauntlet_mat_speed>,
    <conarm:gauntlet_mat_attack>,
    <conarm:gauntlet_mat_reach>,
    <conarm:frosty_soles>,
    <conarm:travel_belt_base>,
    <conarm:travel_belt>,
    <conarm:travel_sack>,
    <conarm:travel_goggles_base>,
    <conarm:travel_goggles>,
    <conarm:travel_night>,
    <conarm:travel_cloak>,
    <conarm:travel_sneak>,
    <conarm:travel_slowfall>,
    <conarm:travel_soul>,
    <conarm:armorstation>,
    <conarm:travel_potion>,
    <conarm:armorforge>.withTag({textureBlock: {id: "minecraft:iron_block", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:helmet_core>.withTag({Material: "stone"}),
    <conarm:helmet_core>.withTag({Material: "flint"}),
    <conarm:helmet_core>.withTag({Material: "cactus"}),
    <conarm:helmet_core>.withTag({Material: "bone"}),
    <conarm:helmet_core>.withTag({Material: "obsidian"}),
    <conarm:helmet_core>.withTag({Material: "prismarine"}),
    <conarm:helmet_core>.withTag({Material: "endstone"}),
    <conarm:helmet_core>.withTag({Material: "paper"}),
    <conarm:helmet_core>.withTag({Material: "sponge"}),
    <conarm:helmet_core>.withTag({Material: "nickel"}),
    <conarm:helmet_core>.withTag({Material: "alumite"}),
    <conarm:helmet_core>.withTag({Material: "chocolate"}),
    <conarm:helmet_core>.withTag({Material: "magnesium"}),
    <conarm:helmet_core>.withTag({Material: "uranium"}),
    <conarm:helmet_core>.withTag({Material: "thorium"}),
    <conarm:helmet_core>.withTag({Material: "boron_nitride"}),
    <conarm:helmet_core>.withTag({Material: "hard_carbon"}),
    <conarm:helmet_core>.withTag({Material: "tough"}),
    <conarm:helmet_core>.withTag({Material: "ardite"}),
    <conarm:helmet_core>.withTag({Material: "manyullyn"}),
    <conarm:helmet_core>.withTag({Material: "copper"}),
    <conarm:helmet_core>.withTag({Material: "bronze"}),
    <conarm:helmet_core>.withTag({Material: "lead"}),
    <conarm:helmet_core>.withTag({Material: "silver"}),
    <conarm:helmet_core>.withTag({Material: "electrum"}),
    <conarm:helmet_core>.withTag({Material: "steel"}),
    <conarm:helmet_core>.withTag({Material: "boron"}),
    <conarm:helmet_core>.withTag({Material: "cobalt"}),
    <conarm:helmet_core>.withTag({Material: "netherrack"}),
    <conarm:helmet_core>.withTag({Material: "magmaslime"}),
    <conarm:helmet_core>.withTag({Material: "blueslime"}),
    <conarm:helmet_core>.withTag({Material: "slime"}),
    <conarm:helmet_core>.withTag({Material: "knightslime"}),
    <conarm:helmet_core>.withTag({Material: "pigiron"}),
    <conarm:helmet_core>.withTag({Material: "iron"}),
    <conarm:helmet_core>.withTag({Material: "firewood"}),
    <conarm:helmet_core>.withTag({Material: "invar"}),
    <conarm:helmet_core>.withTag({Material: "iridium"}),
    <conarm:helmet_core>.withTag({Material: "sapphire"}),
    <conarm:helmet_core>.withTag({Material: "ruby"}),
    <conarm:helmet_core>.withTag({Material: "peridot"}),
    <conarm:helmet_core>.withTag({Material: "emerald_plustic"}),
    <conarm:helmet_core>.withTag({Material: "wood"}),
    <conarm:armor_trim>.withTag({Material: "stone"}),
    <conarm:armor_trim>.withTag({Material: "flint"}),
    <conarm:armor_trim>.withTag({Material: "cactus"}),
    <conarm:armor_trim>.withTag({Material: "bone"}),
    <conarm:armor_trim>.withTag({Material: "obsidian"}),
    <conarm:armor_trim>.withTag({Material: "prismarine"}),
    <conarm:armor_trim>.withTag({Material: "endstone"}),
    <conarm:armor_trim>.withTag({Material: "paper"}),
    <conarm:armor_trim>.withTag({Material: "sponge"}),
    <conarm:armor_trim>.withTag({Material: "firewood"}),
    <conarm:armor_trim>.withTag({Material: "iron"}),
    <conarm:armor_trim>.withTag({Material: "pigiron"}),
    <conarm:armor_trim>.withTag({Material: "knightslime"}),
    <conarm:armor_trim>.withTag({Material: "slime"}),
    <conarm:armor_trim>.withTag({Material: "blueslime"}),
    <conarm:armor_trim>.withTag({Material: "magmaslime"}),
    <conarm:armor_trim>.withTag({Material: "netherrack"}),
    <conarm:armor_trim>.withTag({Material: "cobalt"}),
    <conarm:armor_trim>.withTag({Material: "ardite"}),
    <conarm:armor_trim>.withTag({Material: "manyullyn"}),
    <conarm:armor_trim>.withTag({Material: "copper"}),
    <conarm:armor_trim>.withTag({Material: "bronze"}),
    <conarm:armor_trim>.withTag({Material: "lead"}),
    <conarm:armor_trim>.withTag({Material: "silver"}),
    <conarm:armor_trim>.withTag({Material: "electrum"}),
    <conarm:armor_trim>.withTag({Material: "steel"}),
    <conarm:armor_trim>.withTag({Material: "boron"}),
    <conarm:armor_trim>.withTag({Material: "tough"}),
    <conarm:armor_trim>.withTag({Material: "hard_carbon"}),
    <conarm:armor_trim>.withTag({Material: "boron_nitride"}),
    <conarm:armor_trim>.withTag({Material: "thorium"}),
    <conarm:armor_trim>.withTag({Material: "uranium"}),
    <conarm:armor_trim>.withTag({Material: "magnesium"}),
    <conarm:armor_trim>.withTag({Material: "chocolate"}),
    <conarm:armor_trim>.withTag({Material: "alumite"}),
    <conarm:armor_trim>.withTag({Material: "nickel"}),
    <conarm:armor_trim>.withTag({Material: "invar"}),
    <conarm:armor_trim>.withTag({Material: "iridium"}),
    <conarm:armor_trim>.withTag({Material: "sapphire"}),
    <conarm:armor_trim>.withTag({Material: "ruby"}),
    <conarm:armor_trim>.withTag({Material: "peridot"}),
    <conarm:armor_trim>.withTag({Material: "emerald_plustic"}),
    <conarm:armor_trim>.withTag({Material: "wood"}),
    <conarm:armor_plate>.withTag({Material: "stone"}),
    <conarm:armor_plate>.withTag({Material: "flint"}),
    <conarm:armor_plate>.withTag({Material: "cactus"}),
    <conarm:armor_plate>.withTag({Material: "bone"}),
    <conarm:armor_plate>.withTag({Material: "obsidian"}),
    <conarm:armor_plate>.withTag({Material: "prismarine"}),
    <conarm:armor_plate>.withTag({Material: "endstone"}),
    <conarm:armor_plate>.withTag({Material: "paper"}),
    <conarm:armor_plate>.withTag({Material: "sponge"}),
    <conarm:armor_plate>.withTag({Material: "firewood"}),
    <conarm:armor_plate>.withTag({Material: "iron"}),
    <conarm:armor_plate>.withTag({Material: "pigiron"}),
    <conarm:armor_plate>.withTag({Material: "knightslime"}),
    <conarm:armor_plate>.withTag({Material: "slime"}),
    <conarm:armor_plate>.withTag({Material: "blueslime"}),
    <conarm:armor_plate>.withTag({Material: "magmaslime"}),
    <conarm:armor_plate>.withTag({Material: "netherrack"}),
    <conarm:armor_plate>.withTag({Material: "cobalt"}),
    <conarm:armor_plate>.withTag({Material: "ardite"}),
    <conarm:armor_plate>.withTag({Material: "manyullyn"}),
    <conarm:armor_plate>.withTag({Material: "copper"}),
    <conarm:armor_plate>.withTag({Material: "bronze"}),
    <conarm:armor_plate>.withTag({Material: "lead"}),
    <conarm:armor_plate>.withTag({Material: "silver"}),
    <conarm:armor_plate>.withTag({Material: "electrum"}),
    <conarm:armor_plate>.withTag({Material: "steel"}),
    <conarm:armor_plate>.withTag({Material: "boron"}),
    <conarm:armor_plate>.withTag({Material: "tough"}),
    <conarm:armor_plate>.withTag({Material: "hard_carbon"}),
    <conarm:armor_plate>.withTag({Material: "boron_nitride"}),
    <conarm:armor_plate>.withTag({Material: "thorium"}),
    <conarm:armor_plate>.withTag({Material: "uranium"}),
    <conarm:armor_plate>.withTag({Material: "magnesium"}),
    <conarm:armor_plate>.withTag({Material: "chocolate"}),
    <conarm:armor_plate>.withTag({Material: "alumite"}),
    <conarm:armor_plate>.withTag({Material: "nickel"}),
    <conarm:armor_plate>.withTag({Material: "invar"}),
    <conarm:armor_plate>.withTag({Material: "iridium"}),
    <conarm:armor_plate>.withTag({Material: "sapphire"}),
    <conarm:armor_plate>.withTag({Material: "ruby"}),
    <conarm:armor_plate>.withTag({Material: "peridot"}),
    <conarm:armor_plate>.withTag({Material: "emerald_plustic"}),
    <conarm:armor_plate>.withTag({Material: "wood"}),
    <conarm:chest_core>.withTag({Material: "stone"}),
    <conarm:chest_core>.withTag({Material: "flint"}),
    <conarm:chest_core>.withTag({Material: "cactus"}),
    <conarm:chest_core>.withTag({Material: "bone"}),
    <conarm:chest_core>.withTag({Material: "obsidian"}),
    <conarm:chest_core>.withTag({Material: "prismarine"}),
    <conarm:chest_core>.withTag({Material: "endstone"}),
    <conarm:chest_core>.withTag({Material: "paper"}),
    <conarm:chest_core>.withTag({Material: "sponge"}),
    <conarm:chest_core>.withTag({Material: "firewood"}),
    <conarm:chest_core>.withTag({Material: "iron"}),
    <conarm:chest_core>.withTag({Material: "pigiron"}),
    <conarm:chest_core>.withTag({Material: "knightslime"}),
    <conarm:chest_core>.withTag({Material: "slime"}),
    <conarm:chest_core>.withTag({Material: "blueslime"}),
    <conarm:chest_core>.withTag({Material: "magmaslime"}),
    <conarm:chest_core>.withTag({Material: "netherrack"}),
    <conarm:chest_core>.withTag({Material: "cobalt"}),
    <conarm:chest_core>.withTag({Material: "ardite"}),
    <conarm:chest_core>.withTag({Material: "manyullyn"}),
    <conarm:chest_core>.withTag({Material: "copper"}),
    <conarm:chest_core>.withTag({Material: "bronze"}),
    <conarm:chest_core>.withTag({Material: "lead"}),
    <conarm:chest_core>.withTag({Material: "silver"}),
    <conarm:chest_core>.withTag({Material: "electrum"}),
    <conarm:chest_core>.withTag({Material: "steel"}),
    <conarm:chest_core>.withTag({Material: "boron"}),
    <conarm:chest_core>.withTag({Material: "tough"}),
    <conarm:chest_core>.withTag({Material: "hard_carbon"}),
    <conarm:chest_core>.withTag({Material: "boron_nitride"}),
    <conarm:chest_core>.withTag({Material: "thorium"}),
    <conarm:chest_core>.withTag({Material: "uranium"}),
    <conarm:chest_core>.withTag({Material: "magnesium"}),
    <conarm:chest_core>.withTag({Material: "chocolate"}),
    <conarm:chest_core>.withTag({Material: "alumite"}),
    <conarm:chest_core>.withTag({Material: "nickel"}),
    <conarm:leggings_core>.withTag({Material: "stone"}),
    <conarm:leggings_core>.withTag({Material: "flint"}),
    <conarm:leggings_core>.withTag({Material: "cactus"}),
    <conarm:leggings_core>.withTag({Material: "bone"}),
    <conarm:leggings_core>.withTag({Material: "obsidian"}),
    <conarm:leggings_core>.withTag({Material: "prismarine"}),
    <conarm:leggings_core>.withTag({Material: "endstone"}),
    <conarm:leggings_core>.withTag({Material: "paper"}),
    <conarm:leggings_core>.withTag({Material: "sponge"}),
    <conarm:leggings_core>.withTag({Material: "firewood"}),
    <conarm:leggings_core>.withTag({Material: "iron"}),
    <conarm:leggings_core>.withTag({Material: "pigiron"}),
    <conarm:leggings_core>.withTag({Material: "knightslime"}),
    <conarm:leggings_core>.withTag({Material: "slime"}),
    <conarm:leggings_core>.withTag({Material: "blueslime"}),
    <conarm:leggings_core>.withTag({Material: "magmaslime"}),
    <conarm:leggings_core>.withTag({Material: "netherrack"}),
    <conarm:leggings_core>.withTag({Material: "cobalt"}),
    <conarm:leggings_core>.withTag({Material: "ardite"}),
    <conarm:leggings_core>.withTag({Material: "manyullyn"}),
    <conarm:leggings_core>.withTag({Material: "copper"}),
    <conarm:leggings_core>.withTag({Material: "bronze"}),
    <conarm:leggings_core>.withTag({Material: "lead"}),
    <conarm:leggings_core>.withTag({Material: "silver"}),
    <conarm:leggings_core>.withTag({Material: "electrum"}),
    <conarm:leggings_core>.withTag({Material: "steel"}),
    <conarm:leggings_core>.withTag({Material: "boron"}),
    <conarm:leggings_core>.withTag({Material: "tough"}),
    <conarm:leggings_core>.withTag({Material: "hard_carbon"}),
    <conarm:leggings_core>.withTag({Material: "boron_nitride"}),
    <conarm:leggings_core>.withTag({Material: "thorium"}),
    <conarm:leggings_core>.withTag({Material: "uranium"}),
    <conarm:leggings_core>.withTag({Material: "magnesium"}),
    <conarm:leggings_core>.withTag({Material: "chocolate"}),
    <conarm:leggings_core>.withTag({Material: "alumite"}),
    <conarm:leggings_core>.withTag({Material: "nickel"}),
    <conarm:leggings_core>.withTag({Material: "invar"}),
    <conarm:leggings_core>.withTag({Material: "iridium"}),
    <conarm:leggings_core>.withTag({Material: "sapphire"}),
    <conarm:leggings_core>.withTag({Material: "ruby"}),
    <conarm:leggings_core>.withTag({Material: "peridot"}),
    <conarm:leggings_core>.withTag({Material: "emerald_plustic"}),
    <conarm:leggings_core>.withTag({Material: "wood"}),
    <conarm:boots_core>.withTag({Material: "stone"}),
    <conarm:boots_core>.withTag({Material: "flint"}),
    <conarm:boots_core>.withTag({Material: "cactus"}),
    <conarm:boots_core>.withTag({Material: "bone"}),
    <conarm:boots_core>.withTag({Material: "obsidian"}),
    <conarm:boots_core>.withTag({Material: "prismarine"}),
    <conarm:boots_core>.withTag({Material: "endstone"}),
    <conarm:boots_core>.withTag({Material: "paper"}),
    <conarm:boots_core>.withTag({Material: "sponge"}),
    <conarm:boots_core>.withTag({Material: "firewood"}),
    <conarm:boots_core>.withTag({Material: "iron"}),
    <conarm:boots_core>.withTag({Material: "pigiron"}),
    <conarm:boots_core>.withTag({Material: "knightslime"}),
    <conarm:boots_core>.withTag({Material: "slime"}),
    <conarm:boots_core>.withTag({Material: "blueslime"}),
    <conarm:boots_core>.withTag({Material: "magmaslime"}),
    <conarm:boots_core>.withTag({Material: "netherrack"}),
    <conarm:boots_core>.withTag({Material: "cobalt"}),
    <conarm:boots_core>.withTag({Material: "ardite"}),
    <conarm:boots_core>.withTag({Material: "manyullyn"}),
    <conarm:boots_core>.withTag({Material: "copper"}),
    <conarm:boots_core>.withTag({Material: "bronze"}),
    <conarm:boots_core>.withTag({Material: "lead"}),
    <conarm:boots_core>.withTag({Material: "silver"}),
    <conarm:boots_core>.withTag({Material: "electrum"}),
    <conarm:boots_core>.withTag({Material: "steel"}),
    <conarm:boots_core>.withTag({Material: "boron"}),
    <conarm:boots_core>.withTag({Material: "tough"}),
    <conarm:boots_core>.withTag({Material: "hard_carbon"}),
    <conarm:boots_core>.withTag({Material: "boron_nitride"}),
    <conarm:boots_core>.withTag({Material: "thorium"}),
    <conarm:boots_core>.withTag({Material: "uranium"}),
    <conarm:boots_core>.withTag({Material: "magnesium"}),
    <conarm:boots_core>.withTag({Material: "chocolate"}),
    <conarm:boots_core>.withTag({Material: "alumite"}),
    <conarm:boots_core>.withTag({Material: "nickel"}),
    <conarm:boots_core>.withTag({Material: "invar"}),
    <conarm:boots_core>.withTag({Material: "iridium"}),
    <conarm:boots_core>.withTag({Material: "sapphire"}),
    <conarm:boots_core>.withTag({Material: "ruby"}),
    <conarm:boots_core>.withTag({Material: "peridot"}),
    <conarm:boots_core>.withTag({Material: "emerald_plustic"}),
    <conarm:boots_core>.withTag({Material: "wood"}),
    <conarm:polishing_kit>.withTag({Material: "stone"}),
    <conarm:polishing_kit>.withTag({Material: "flint"}),
    <conarm:polishing_kit>.withTag({Material: "cactus"}),
    <conarm:polishing_kit>.withTag({Material: "bone"}),
    <conarm:polishing_kit>.withTag({Material: "obsidian"}),
    <conarm:polishing_kit>.withTag({Material: "prismarine"}),
    <conarm:polishing_kit>.withTag({Material: "endstone"}),
    <conarm:polishing_kit>.withTag({Material: "paper"}),
    <conarm:polishing_kit>.withTag({Material: "sponge"}),
    <conarm:polishing_kit>.withTag({Material: "firewood"}),
    <conarm:polishing_kit>.withTag({Material: "iron"}),
    <conarm:polishing_kit>.withTag({Material: "pigiron"}),
    <conarm:polishing_kit>.withTag({Material: "knightslime"}),
    <conarm:polishing_kit>.withTag({Material: "slime"}),
    <conarm:polishing_kit>.withTag({Material: "blueslime"}),
    <conarm:polishing_kit>.withTag({Material: "magmaslime"}),
    <conarm:polishing_kit>.withTag({Material: "netherrack"}),
    <conarm:polishing_kit>.withTag({Material: "cobalt"}),
    <conarm:polishing_kit>.withTag({Material: "ardite"}),
    <conarm:polishing_kit>.withTag({Material: "manyullyn"}),
    <conarm:polishing_kit>.withTag({Material: "copper"}),
    <conarm:polishing_kit>.withTag({Material: "bronze"}),
    <conarm:polishing_kit>.withTag({Material: "lead"}),
    <conarm:polishing_kit>.withTag({Material: "silver"}),
    <conarm:polishing_kit>.withTag({Material: "electrum"}),
    <conarm:polishing_kit>.withTag({Material: "steel"}),
    <conarm:polishing_kit>.withTag({Material: "boron"}),
    <conarm:polishing_kit>.withTag({Material: "tough"}),
    <conarm:polishing_kit>.withTag({Material: "hard_carbon"}),
    <conarm:polishing_kit>.withTag({Material: "boron_nitride"}),
    <conarm:polishing_kit>.withTag({Material: "thorium"}),
    <conarm:polishing_kit>.withTag({Material: "uranium"}),
    <conarm:polishing_kit>.withTag({Material: "magnesium"}),
    <conarm:polishing_kit>.withTag({Material: "chocolate"}),
    <conarm:polishing_kit>.withTag({Material: "alumite"}),
    <conarm:polishing_kit>.withTag({Material: "nickel"}),
    <conarm:polishing_kit>.withTag({Material: "invar"}),
    <conarm:polishing_kit>.withTag({Material: "iridium"}),
    <conarm:polishing_kit>.withTag({Material: "sapphire"}),
    <conarm:polishing_kit>.withTag({Material: "ruby"}),
    <conarm:polishing_kit>.withTag({Material: "peridot"}),
    <conarm:polishing_kit>.withTag({Material: "emerald_plustic"}),
    <conarm:polishing_kit>.withTag({Material: "wood"}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 1 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 2 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 3 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 4 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 5 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 6 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 7 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 8 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 9 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 1 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 2 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 3 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 4 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 5 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 6 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "tconstruct:metal", Count: 1 as byte, Damage: 4 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "tconstruct:metal", Count: 1 as byte, Damage: 3 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "tconstruct:metal", Count: 1 as byte, Damage: 5 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "chisel:blockcobalt", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "tconstruct:metal", Count: 1 as byte, Damage: 1 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "tconstruct:metal", Count: 1 as byte, Damage: 2 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 3 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 3 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 2 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 1 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "minecraft:gold_block", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "techreborn:storage", Count: 1 as byte, Damage: 5 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 1 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 5 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "techreborn:storage", Count: 1 as byte, Damage: 8 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 4 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "nuclearcraft:ingot_block", Count: 1 as byte, Damage: 5 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "nuclearcraft:ingot_block", Count: 1 as byte, Damage: 3 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "immersiveengineering:storage", Count: 1 as byte, Damage: 5 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "nuclearcraft:ingot_block", Count: 1 as byte, Damage: 7 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 4 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "plustic:alumiteblock", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 2 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 7 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "mekanism:basicblock", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "mekanism:basicblock", Count: 1 as byte, Damage: 2 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "nuclearcraft:ingot_block", Count: 1 as byte, Damage: 11 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "minecraft:glowstone", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "minecraft:redstone_block", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "plustic:osgloglasblock", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "mekanism:basicblock", Count: 1 as byte, Damage: 4 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "plustic:osmiridiumblock", Count: 1 as byte, Damage: 0 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 6 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 5 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 6 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 7 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "avaritia:block_resource", Count: 1 as byte, Damage: 1 as short}}),
    <conarm:armorforge>.withTag({textureBlock: {id: "nuclearcraft:ingot_block", Count: 1 as byte, Damage: 9 as short}}),
    <conarm:chest_core>.withTag({Material: "invar"}),
    <conarm:chest_core>.withTag({Material: "iridium"}),
    <conarm:chest_core>.withTag({Material: "sapphire"}),
    <conarm:chest_core>.withTag({Material: "ruby"}),
    <conarm:chest_core>.withTag({Material: "peridot"}),
    <conarm:chest_core>.withTag({Material: "emerald_plustic"}),
    <conarm:chest_core>.withTag({Material: "wood"})

];
for item in conarmstage {
    mods.recipestages.Recipes.setRecipeStage("conarm", item);
    mods.ItemStages.addItemStage("conarm", item);
}