//#priority 349
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

val iestage as IItemStack[] = [
    <immersiveengineering:storage_slab:2>,
    <immersiveengineering:storage_slab:3>,
    <immersiveengineering:storage_slab:4>,
    <immersiveengineering:storage_slab:5>,
    <immersiveengineering:storage_slab:6>,
    <immersiveengineering:storage_slab:7>,
    <immersiveengineering:storage_slab:8>,
    <immersiveengineering:stone_decoration>,
    <immersiveengineering:stone_decoration:1>,
    <immersiveengineering:stone_decoration_slab:1>,
    <immersiveengineering:stone_decoration_slab>,
    <immersiveengineering:stone_decoration:10>,
    <immersiveengineering:stone_decoration:8>,
    <immersiveengineering:stone_decoration:7>,
    <immersiveengineering:stone_decoration:6>,
    <immersiveengineering:stone_decoration:5>,
    <immersiveengineering:stone_decoration:4>,
    <immersiveengineering:stone_decoration_slab:2>,
    <immersiveengineering:stone_decoration_slab:4>,
    <immersiveengineering:stone_decoration_slab:5>,
    <immersiveengineering:stone_decoration_slab:6>,
    <immersiveengineering:stone_decoration_slab:7>,
    <immersiveengineering:stone_decoration_slab:10>,
    <immersiveengineering:stone_decoration_stairs_hempcrete>,
    <immersiveengineering:stone_decoration_stairs_concrete>,
    <immersiveengineering:stone_decoration_stairs_concrete_tile>,
    <immersiveengineering:storage_slab:1>,
    <immersiveengineering:storage_slab>,
    <immersiveengineering:stone_decoration:2>,
    <immersiveengineering:stone_decoration_stairs_concrete_leaded>,
    <immersiveengineering:treated_wood>,
    <immersiveengineering:treated_wood:1>,
    <immersiveengineering:treated_wood:2>,
    <immersiveengineering:treated_wood_slab>,
    <immersiveengineering:treated_wood_slab:1>,
    <immersiveengineering:treated_wood_slab:2>,
    <immersiveengineering:treated_wood_stairs0>,
    <immersiveengineering:treated_wood_stairs1>,
    <immersiveengineering:treated_wood_stairs2>,
    <immersiveengineering:wooden_decoration>,
    <immersiveengineering:wooden_decoration:1>,
    <immersiveengineering:wooden_device0>,
    <immersiveengineering:wooden_device0:1>,
    <immersiveengineering:wooden_device0:2>,
    <immersiveengineering:wooden_device0:3>,
    <immersiveengineering:wooden_device0:4>,
    <immersiveengineering:wooden_device0:5>,
    <immersiveengineering:wooden_device0:6>,
    <immersiveengineering:wooden_device0:7>,
    <immersiveengineering:wooden_device1>,
    <immersiveengineering:wooden_device1:1>,
    <immersiveengineering:wooden_device1:3>,
    <immersiveengineering:wooden_device1:4>,
    <immersiveengineering:cloth_device>,
    <immersiveengineering:cloth_device:1>,
    <immersiveengineering:cloth_device:2>,
    <immersiveengineering:sheetmetal>,
    <immersiveengineering:sheetmetal:1>,
    <immersiveengineering:sheetmetal:2>,
    <immersiveengineering:sheetmetal:3>,
    <immersiveengineering:sheetmetal:4>,
    <immersiveengineering:sheetmetal:5>,
    <immersiveengineering:sheetmetal:6>,
    <immersiveengineering:sheetmetal:7>,
    <immersiveengineering:sheetmetal:8>,
    <immersiveengineering:sheetmetal:9>,
    <immersiveengineering:sheetmetal:10>,
    <immersiveengineering:sheetmetal_slab>,
    <immersiveengineering:sheetmetal_slab:1>,
    <immersiveengineering:sheetmetal_slab:2>,
    <immersiveengineering:sheetmetal_slab:3>,
    <immersiveengineering:sheetmetal_slab:4>,
    <immersiveengineering:sheetmetal_slab:5>,
    <immersiveengineering:sheetmetal_slab:6>,
    <immersiveengineering:sheetmetal_slab:7>,
    <immersiveengineering:sheetmetal_slab:8>,
    <immersiveengineering:sheetmetal_slab:9>,
    <immersiveengineering:sheetmetal_slab:10>,
    <immersiveengineering:metal_decoration0>,
    <immersiveengineering:metal_decoration0:1>,
    <immersiveengineering:metal_decoration0:2>,
    <immersiveengineering:metal_decoration0:3>,
    <immersiveengineering:metal_decoration0:4>,
    <immersiveengineering:metal_decoration0:5>,
    <immersiveengineering:metal_decoration0:6>,
    <immersiveengineering:metal_decoration0:7>,
    <immersiveengineering:metal_decoration1>,
    <immersiveengineering:metal_decoration1:1>,
    <immersiveengineering:metal_decoration1:2>,
    <immersiveengineering:metal_decoration1:3>,
    <immersiveengineering:metal_decoration1:4>,
    <immersiveengineering:metal_decoration1:5>,
    <immersiveengineering:metal_decoration1:6>,
    <immersiveengineering:metal_decoration1:7>,
    <immersiveengineering:metal_decoration2>,
    <immersiveengineering:metal_decoration2:1>,
    <immersiveengineering:metal_decoration2:2>,
    <immersiveengineering:metal_decoration2:3>,
    <immersiveengineering:metal_decoration2:4>,
    <immersiveengineering:metal_decoration2:5>,
    <immersiveengineering:metal_decoration2:7>,
    <immersiveengineering:metal_decoration2:8>,
    <immersiveengineering:metal_decoration1_slab:1>,
    <immersiveengineering:metal_decoration1_slab:2>,
    <immersiveengineering:metal_decoration1_slab:3>,
    <immersiveengineering:metal_decoration1_slab:5>,
    <immersiveengineering:metal_decoration1_slab:6>,
    <immersiveengineering:metal_decoration1_slab:7>,
    <immersiveengineering:steel_scaffolding_stairs0>,
    <immersiveengineering:steel_scaffolding_stairs1>,
    <immersiveengineering:steel_scaffolding_stairs2>,
    <immersiveengineering:aluminum_scaffolding_stairs0>,
    <immersiveengineering:aluminum_scaffolding_stairs1>,
    <immersiveengineering:aluminum_scaffolding_stairs2>,
    <immersiveengineering:metal_ladder>,
    <immersiveengineering:metal_ladder:1>,
    <immersiveengineering:metal_ladder:2>,
    <immersiveengineering:connector>,
    <immersiveengineering:connector:1>,
    <immersiveengineering:connector:2>,
    <immersiveengineering:connector:3>,
    <immersiveengineering:connector:4>,
    <immersiveengineering:connector:5>,
    <immersiveengineering:connector:6>,
    <immersiveengineering:connector:7>,
    <immersiveengineering:connector:8>,
    <immersiveengineering:connector:9>,
    <immersiveengineering:connector:10>,
    <immersiveengineering:connector:11>,
    <immersiveengineering:connector:12>,
    <immersiveengineering:connector:13>,
    <immersiveengineering:metal_device0>,
    <immersiveengineering:metal_device0:1>,
    <immersiveengineering:metal_device0:2>,
    <immersiveengineering:metal_device0:3>,
    <immersiveengineering:metal_device0:4>,
    <immersiveengineering:metal_device0:5>,
    <immersiveengineering:metal_device0:6>,
    <immersiveengineering:metal_device1>,
    <immersiveengineering:metal_device1:1>,
    <immersiveengineering:metal_device1:2>,
    <immersiveengineering:metal_device1:3>,
    <immersiveengineering:metal_device1:4>,
    <immersiveengineering:metal_device1:5>,
    <immersiveengineering:metal_device1:6>,
    <immersiveengineering:metal_device1:7>,
    <immersiveengineering:metal_device1:8>,
    <immersiveengineering:metal_device1:9>,
    <immersiveengineering:metal_device1:10>,
    <immersiveengineering:metal_device1:11>,
    <immersiveengineering:metal_device1:13>,
    <immersiveengineering:conveyor>,
    <immersiveengineering:material>,
    <immersiveengineering:material:1>,
    <immersiveengineering:material:2>,
    <immersiveengineering:material:3>,
    <immersiveengineering:material:5>,
    <immersiveengineering:material:6>,
    <immersiveengineering:material:7>,
    <immersiveengineering:material:8>,
    <immersiveengineering:material:9>,
    <immersiveengineering:material:10>,
    <immersiveengineering:material:11>,
    <immersiveengineering:material:12>,
    <immersiveengineering:material:13>,
    <immersiveengineering:material:14>,
    <immersiveengineering:material:15>,
    <immersiveengineering:material:16>,
    <immersiveengineering:material:17>,
    <immersiveengineering:material:18>,
    <immersiveengineering:material:20>,
    <immersiveengineering:material:21>,
    <immersiveengineering:material:22>,
    <immersiveengineering:material:23>,
    <immersiveengineering:material:24>,
    <immersiveengineering:material:26>,
    <immersiveengineering:material:27>,
    <immersiveengineering:metal:14>,
    <immersiveengineering:metal:35>,
    <immersiveengineering:tool>,
    <immersiveengineering:tool:1>,
    <immersiveengineering:tool:2>,
    <immersiveengineering:tool:3>,
    <immersiveengineering:pickaxe_steel>,
    <immersiveengineering:shovel_steel>,
    <immersiveengineering:axe_steel>,
    <immersiveengineering:sword_steel>,
    <immersiveengineering:toolbox>,
    <immersiveengineering:wirecoil>,
    <immersiveengineering:wirecoil:1>,
    <immersiveengineering:wirecoil:2>,
    <immersiveengineering:wirecoil:3>,
    <immersiveengineering:wirecoil:4>,
    <immersiveengineering:wirecoil:5>,
    <immersiveengineering:wirecoil:6>,
    <immersiveengineering:wirecoil:7>,
    <immersiveengineering:drill>,
    <immersiveengineering:mold:6>,
    <immersiveengineering:mold:7>,
    <immersiveengineering:blueprint>,
    <immersiveengineering:blueprint>,
    <immersiveengineering:blueprint>,
    <immersiveengineering:blueprint>,
    <immersiveengineering:blueprint>,
    <immersiveengineering:revolver>,
    <immersiveengineering:speedloader>,
    <immersiveengineering:drillhead>,
    <immersiveengineering:drillhead:1>,
    <immersiveengineering:jerrycan>,
    <immersiveengineering:mold>,
    <immersiveengineering:mold:1>,
    <immersiveengineering:mold:2>,
    <immersiveengineering:mold:3>,
    <immersiveengineering:mold:4>,
    <immersiveengineering:mold:5>,
    <immersiveengineering:bullet>,
    <immersiveengineering:bullet:2>,
    <immersiveengineering:chemthrower>,
    <immersiveengineering:railgun>,
    <immersiveengineering:skyhook>,
    <immersiveengineering:toolupgrade>,
    <immersiveengineering:toolupgrade:1>,
    <immersiveengineering:toolupgrade:2>,
    <immersiveengineering:toolupgrade:3>,
    <immersiveengineering:toolupgrade:4>,
    <immersiveengineering:toolupgrade:5>,
    <immersiveengineering:toolupgrade:6>,
    <immersiveengineering:toolupgrade:7>,
    <immersiveengineering:toolupgrade:8>,
    <immersiveengineering:toolupgrade:9>,
    <immersiveengineering:toolupgrade:10>,
    <immersiveengineering:toolupgrade:11>,
    <immersiveengineering:toolupgrade:12>,
    <immersiveengineering:toolupgrade:13>,
    <immersiveengineering:earmuffs>,
    <immersiveengineering:coresample>,
    <immersiveengineering:graphite_electrode>,
    <immersiveengineering:faraday_suit_feet>,
    <immersiveengineering:faraday_suit_legs>,
    <immersiveengineering:faraday_suit_chest>,
    <immersiveengineering:faraday_suit_head>,
    <immersiveengineering:fluorescent_tube>,
    <immersiveengineering:powerpack>,
    <immersiveengineering:shield>,
    <immersiveengineering:maintenance_kit>,
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:conveyor"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:uncontrolled"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:dropper"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:vertical"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:splitter"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:covered"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:verticalcovered"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:extract"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:extractcovered"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "casull"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "armor_piercing"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "buckshot"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "he"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "silver"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "dragonsbreath"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "potion"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "flare"}),
    <immersiveengineering:steel_armor_head>,
    <immersiveengineering:steel_armor_chest>,
    <immersiveengineering:steel_armor_legs>,
    <immersiveengineering:steel_armor_feet>,
    <immersiveengineering:shader_bag>.withTag({rarity: "COMMON"}),
    <immersiveengineering:shader_bag>.withTag({rarity: "UNCOMMON"}),
    <immersiveengineering:shader_bag>.withTag({rarity: "RARE"}),
    <immersiveengineering:shader_bag>.withTag({rarity: "EPIC"}),
    <immersiveengineering:shader_bag>.withTag({rarity: "IE:MASTERWORK"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:droppercovered"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:chute_iron"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:chute_steel"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:chute_copper"}),
    <immersiveengineering:shader>.withTag({shader_name: "Argo"}),
    <immersiveengineering:shader>.withTag({shader_name: "Sunstrike"}),
    <immersiveengineering:shader>.withTag({shader_name: "Locus"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:chute_aluminum"}),
    <immersiveengineering:shader>.withTag({shader_name: "Rosequartz"}),
    <immersiveengineering:shader>.withTag({shader_name: "Felix"}),
    <immersiveengineering:shader>.withTag({shader_name: "Sharkface"}),
    <immersiveengineering:shader>.withTag({shader_name: "Dragon's Breath"}),
    <immersiveengineering:shader>.withTag({shader_name: "Hawk"}),
    <immersiveengineering:shader>.withTag({shader_name: "Eyas"}),
    <immersiveengineering:shader>.withTag({shader_name: "Magnum"}),
    <immersiveengineering:shader>.withTag({shader_name: "Fox"}),
    <immersiveengineering:shader>.withTag({shader_name: "Vault-Tec"}),
    <immersiveengineering:shader>.withTag({shader_name: "Sponsor"}),
    <immersiveengineering:shader>.withTag({shader_name: "Mass Fusion"}),
    <immersiveengineering:shader>.withTag({shader_name: "StormFlower"}),
    <immersiveengineering:shader>.withTag({shader_name: "Miló"}),
    <immersiveengineering:shader>.withTag({shader_name: "Trident"}),
    <immersiveengineering:shader>.withTag({shader_name: "Chloris"}),
    <immersiveengineering:shader>.withTag({shader_name: "Crescent Rose"}),
    <immersiveengineering:shader>.withTag({shader_name: "Qrow"}),
    <immersiveengineering:shader>.withTag({shader_name: "Lusus Naturae"}),
    <immersiveengineering:shader>.withTag({shader_name: "Vanguard"}),
    <immersiveengineering:shader>.withTag({shader_name: "Regal"}),
    <immersiveengineering:shader>.withTag({shader_name: "Harrowed"}),
    <immersiveengineering:shader>.withTag({shader_name: "Taken"}),
    <immersiveengineering:shader>.withTag({shader_name: "IKELOS"}),
    <immersiveengineering:shader>.withTag({shader_name: "Angel's Thesis"}),
    <immersiveengineering:shader>.withTag({shader_name: "Sutherland"}),
    <immersiveengineering:shader>.withTag({shader_name: "Exia"}),
    <immersiveengineering:shader>.withTag({shader_name: "Crimson Lotus"}),
    <immersiveengineering:shader>.withTag({shader_name: "Dominator"}),
    <immersiveengineering:shader>.withTag({shader_name: "Microshark"}),
    <immersiveengineering:shader>.withTag({shader_name: "N7"}),
    <immersiveengineering:shader>.withTag({shader_name: "Normandy"}),
    <immersiveengineering:shader>.withTag({shader_name: "OmniTool"}),
    <immersiveengineering:shader>.withTag({shader_name: "The Kindled"}),
    <immersiveengineering:shader>.withTag({shader_name: "Dark Fire"}),
    <immersiveengineering:shader>.withTag({shader_name: "Erruption"}),
    <immersiveengineering:shader>.withTag({shader_name: "WAAAGH!"}),
    <immersiveengineering:shader>.withTag({shader_name: "Warbird"}),
    <immersiveengineering:shader>.withTag({shader_name: "Matrix"}),
    <immersiveengineering:shader>.withTag({shader_name: "Twili"}),
    <immersiveengineering:shader>.withTag({shader_name: "Usurper"}),
    <immersiveengineering:shader>.withTag({shader_name: "Ancient"}),
    <immersiveengineering:shader>.withTag({shader_name: "Glacis"}),
    <immersiveengineering:shader>.withTag({shader_name: "Phoenix"}),
    <immersiveengineering:shader>.withTag({shader_name: "Radiant"}),
    <immersiveengineering:shader>.withTag({shader_name: "Hollow"}),

//Tech Reborn
    <techreborn:thermal_generator>,
    <techreborn:quantum_tank>,
    <techreborn:creative_quantum_tank>,
    <techreborn:quantum_chest>,
    <techreborn:creative_quantum_chest>,
    <techreborn:digital_chest>,
    <techreborn:industrial_centrifuge>,
    <techreborn:rolling_machine>,
    <techreborn:industrial_blast_furnace>,
    <techreborn:storage2>,
    <techreborn:alloy_smelter>,
    <techreborn:industrial_grinder>,
    <techreborn:implosion_compressor>,
    <techreborn:matter_fabricator>,
    <techreborn:chunk_loader>,
    <techreborn:charge_o_mat>,
    <techreborn:player_detector>,
    <techreborn:player_detector:1>,
    <techreborn:player_detector:2>,
    <techreborn:cable>,
    <techreborn:cable:1>,
    <techreborn:cable:2>,
    <techreborn:cable:3>,
    <techreborn:cable:4>,
    <techreborn:cable:5>,
    <techreborn:cable:6>,
    <techreborn:cable:7>,
    <techreborn:cable:8>,
    <techreborn:machine_casing>,
    <techreborn:machine_casing:1>,
    <techreborn:machine_casing:2>,
    <techreborn:dragon_egg_syphon>,
    <techreborn:magic_energy_converter>,
    <techreborn:assembling_machine>,
    <techreborn:diesel_generator>,
    <techreborn:industrial_electrolyzer>,
    <techreborn:magic_energy_absorber>,
    <techreborn:solar_panel:4>,
    <techreborn:solar_panel:3>,
    <techreborn:solar_panel:2>,
    <techreborn:solar_panel:1>,
    <techreborn:solar_panel>,
    <techreborn:electric_furnace>,
    <techreborn:compressor>,
    <techreborn:extractor>,
    <techreborn:solid_fuel_generator>,
    <techreborn:vacuum_freezer>,
    <techreborn:fusion_control_computer>,
    <techreborn:fusion_coil>,
    <techreborn:lightning_rod>,
    <techreborn:industrial_sawmill>,
    <techreborn:machine_frame>,
    <techreborn:machine_frame:1>,
    <techreborn:machine_frame:2>,
    <techreborn:grinder>,
    <techreborn:distillation_tower>,
    <techreborn:lsu_storage>,
    <techreborn:lapotronic_su>,
    <techreborn:adjustable_su>,
    <techreborn:interdimensional_su>,
    <techreborn:chemical_reactor>,
    <techreborn:iron_alloy_furnace>,
    <techreborn:gas_turbine>,
    <techreborn:semi_fluid_generator>,
    <techreborn:creative_solar_panel>,
    <techreborn:water_mill>,
    <techreborn:wind_mill>,
    <techreborn:refined_iron_fence>,
    <techreborn:reinforced_glass>,
    <techreborn:recycler>,
    <techreborn:low_voltage_su>,
    <techreborn:medium_voltage_su>,
    <techreborn:high_voltage_su>,
    <techreborn:lv_transformer>,
    <techreborn:mv_transformer>,
    <techreborn:hv_transformer>,
    <techreborn:auto_crafting_table>,
    <techreborn:iron_furnace>,
    <techreborn:nuke>,
    <techreborn:scrapboxinator>,
    <techreborn:computer_cube>,
    <techreborn:plasma_generator>,
    <techreborn:lamp_incandescent>,
    <techreborn:lamp_led>,
    <techreborn:alarm>,
    <techreborn:fluid_replicator>,
    <techreborn:dust>,
    <techreborn:dust:2>,
    <techreborn:dust:3>,
    <techreborn:dust:4>,
    <techreborn:dust:6>,
    <techreborn:dust:8>,
    <techreborn:dust:9>,
    <techreborn:dust:10>,
    <techreborn:dust:12>,
    <techreborn:dust:15>,
    <techreborn:dust:16>,
    <techreborn:dust:18>,
    <techreborn:dust:19>,
    <techreborn:dust:20>,
    <techreborn:dust:21>,
    <techreborn:dust:22>,
    <techreborn:dust:23>,
    <techreborn:dust:25>,
    <techreborn:dust:28>,
    <techreborn:dust:30>,
    <techreborn:dust:31>,
    <techreborn:dust:59>,
    <techreborn:dust:61>,
    <techreborn:dust:62>,
    <techreborn:dust:63>,
    <techreborn:dust:58>,
    <techreborn:dust:56>,
    <techreborn:dust:55>,
    <techreborn:dust:54>,
    <techreborn:dust:49>,
    <techreborn:dust:46>,
    <techreborn:dust:45>,
    <techreborn:dust:32>,
    <techreborn:dust:33>,
    <techreborn:dust:36>,
    <techreborn:dust:37>,
    <techreborn:dust:40>,
    <techreborn:dust:41>,
    <techreborn:dust:43>,
    <techreborn:dust:44>,
    <techreborn:part>,
    <techreborn:part:1>,
    <techreborn:part:2>,
    <techreborn:part:3>,
    <techreborn:part:4>,
    <techreborn:part:5>,
    <techreborn:part:6>,
    <techreborn:part:7>,
    <techreborn:part:8>,
    <techreborn:part:9>,
    <techreborn:part:10>,
    <techreborn:part:11>,
    <techreborn:part:12>,
    <techreborn:part:13>,
    <techreborn:part:14>,
    <techreborn:part:15>,
    <techreborn:part:17>,
    <techreborn:part:18>,
    <techreborn:part:19>,
    <techreborn:part:20>,
    <techreborn:part:21>,
    <techreborn:part:22>,
    <techreborn:part:23>,
    <techreborn:part:24>,
    <techreborn:part:25>,
    <techreborn:part:26>,
    <techreborn:part:27>,
    <techreborn:part:28>,
    <techreborn:part:29>,
    <techreborn:part:30>,
    <techreborn:part:31>,
    <techreborn:part:32>,
    <techreborn:part:33>,
    <techreborn:part:34>,
    <techreborn:plates:36>,
    <techreborn:part:35>,
    <techreborn:part:36>,
    <techreborn:part:37>,
    <techreborn:part:38>,
    <techreborn:part:39>,
    <techreborn:plates:2>,
    <techreborn:plates:3>,
    <techreborn:plates:4>,
    <techreborn:plates:5>,
    <techreborn:plates:6>,
    <techreborn:plates:8>,
    <techreborn:plates:9>,
    <techreborn:plates:10>,
    <techreborn:plates:11>,
    <techreborn:plates:12>,
    <techreborn:plates:13>,
    <techreborn:plates:14>,
    <techreborn:plates:15>,
    <techreborn:plates:19>,
    <techreborn:plates:30>,
    <techreborn:plates:31>,
    <techreborn:plates:32>,
    <techreborn:plates:33>,
    <techreborn:plates:34>,
    <techreborn:plates:35>,
    <techreborn:plates:17>,
    <techreborn:plates:37>,
    <techreborn:smalldust>,
    <techreborn:smalldust:1>,
    <techreborn:smalldust:2>,
    <techreborn:smalldust:3>,
    <techreborn:smalldust:4>,
    <techreborn:smalldust:6>,
    <techreborn:smalldust:7>,
    <techreborn:smalldust:34>,
    <techreborn:smalldust:33>,
    <techreborn:smalldust:32>,
    <techreborn:smalldust:31>,
    <techreborn:smalldust:30>,
    <techreborn:smalldust:29>,
    <techreborn:smalldust:28>,
    <techreborn:smalldust:27>,
    <techreborn:smalldust:26>,
    <techreborn:smalldust:17>,
    <techreborn:smalldust:18>,
    <techreborn:smalldust:19>,
    <techreborn:smalldust:20>,
    <techreborn:smalldust:21>,
    <techreborn:smalldust:22>,
    <techreborn:smalldust:23>,
    <techreborn:smalldust:24>,
    <techreborn:smalldust:25>,
    <techreborn:smalldust:16>,
    <techreborn:smalldust:15>,
    <techreborn:smalldust:14>,
    <techreborn:smalldust:13>,
    <techreborn:smalldust:12>,
    <techreborn:smalldust:10>,
    <techreborn:smalldust:9>,
    <techreborn:smalldust:8>,
    <techreborn:smalldust:35>,
    <techreborn:smalldust:36>,
    <techreborn:smalldust:37>,
    <techreborn:smalldust:38>,
    <techreborn:smalldust:40>,
    <techreborn:smalldust:41>,
    <techreborn:smalldust:43>,
    <techreborn:smalldust:44>,
    <techreborn:smalldust:45>,
    <techreborn:smalldust:46>,
    <techreborn:smalldust:47>,
    <techreborn:smalldust:49>,
    <techreborn:smalldust:51>,
    <techreborn:smalldust:52>,
    <techreborn:smalldust:53>,
    <techreborn:smalldust:54>,
    <techreborn:smalldust:55>,
    <techreborn:smalldust:56>,
    <techreborn:smalldust:58>,
    <techreborn:smalldust:59>,
    <techreborn:smalldust:61>,
    <techreborn:smalldust:62>,
    <techreborn:smalldust:63>,
    <techreborn:smalldust:64>,
    <techreborn:smalldust:65>,
    <techreborn:uumatter>,
    <techreborn:cloakingdevice>.withTag({energy: 0}),
    <techreborn:cloakingdevice>.withTag({energy: 40000000}),
    <techreborn:lapotronpack>.withTag({energy: 0}),
    <techreborn:lapotronpack>.withTag({energy: 400000000}),
    <techreborn:lithiumbatpack>.withTag({energy: 0}),
    <techreborn:lithiumbatpack>.withTag({energy: 16000000}),
    <techreborn:energycrystal>.withTag({energy: 0}),
    <techreborn:energycrystal>.withTag({energy: 4000000}),
    <techreborn:lapotroncrystal>.withTag({energy: 0}),
    <techreborn:lapotroncrystal>.withTag({energy: 40000000}),
    <techreborn:lapotronicorb>.withTag({energy: 0}),
    <techreborn:lapotronicorb>.withTag({energy: 400000000}),
    <techreborn:lithiumbattery>.withTag({energy: 0}),
    <techreborn:lithiumbattery>.withTag({energy: 400000}),
    <techreborn:rebattery>.withTag({energy: 0}),
    <techreborn:rebattery>.withTag({energy: 40000}),
    <techreborn:advancedchainsaw>.withTag({energy: 0}),
    <techreborn:advancedchainsaw>.withTag({energy: 4000000}),
    <techreborn:advanceddrill>.withTag({energy: 0}),
    <techreborn:advanceddrill>.withTag({energy: 4000000}),
    <techreborn:ironjackhammer>.withTag({energy: 4000000}),
    <techreborn:ironjackhammer>.withTag({energy: 0}),
    <techreborn:debug>,
    <techreborn:diamondchainsaw>.withTag({energy: 0}),
    <techreborn:diamondchainsaw>.withTag({energy: 400000}),
    <techreborn:diamonddrill>.withTag({energy: 0}),
    <techreborn:diamonddrill>.withTag({energy: 400000}),
    <techreborn:diamondjackhammer>.withTag({energy: 0}),
    <techreborn:diamondjackhammer>.withTag({energy: 400000}),
    <techreborn:electrictreetap>.withTag({energy: 0}),
    <techreborn:electrictreetap>.withTag({energy: 10000}),
    <techreborn:nanosaber>.withTag({isActive: 0 as byte}),
    <techreborn:nanosaber>.withTag({isActive: 0 as byte, energy: 640000}),
    <techreborn:nanosaber>.withTag({isActive: 1 as byte, energy: 640000}),
    <techreborn:omnitool>.withTag({energy: 0}),
    <techreborn:omnitool>.withTag({energy: 20000}),
    <techreborn:rockcutter>.withTag({ench: [{lvl: 1 as short, id: 33 as short}], energy: 0}),
    <techreborn:rockcutter>.withTag({ench: [{lvl: 1 as short, id: 33 as short}], energy: 400000}),
    <techreborn:ironchainsaw>.withTag({energy: 0}),
    <techreborn:ironchainsaw>.withTag({energy: 40000}),
    <techreborn:irondrill>.withTag({energy: 0}),
    <techreborn:irondrill>.withTag({energy: 40000}),
    <techreborn:steeljackhammer>.withTag({energy: 0}),
    <techreborn:dynamiccell>,
    <techreborn:frequencytransmitter>,
    <techreborn:techmanuel>,
    <techreborn:scrapbox>,
    <techreborn:upgrades>,
    <techreborn:upgrades:1>,
    <techreborn:upgrades:2>,
    <techreborn:upgrades:3>,
    <techreborn:steeljackhammer>.withTag({energy: 40000}),
    <techreborn:wrench>,
    <techreborn:treetap>,
    <techreborn:plate_bending_machine>,
    <techreborn:wire_mill>,
    <techreborn:pump>,
    <techreborn:ev_transformer>,
    <techreborn:storage2:1>,
    <techreborn:storage2:2>,
    <techreborn:solid_canning_machine>,
    <techreborn:ingot:21>,
    <techreborn:ingot:22>,
    <techreborn:part:40>,
    <techreborn:part:41>,
    <techreborn:part:42>,
    <techreborn:part:43>,
    <techreborn:part:44>,
    <techreborn:part:45>,
    <techreborn:iridiumneutronreflector>,
    <techreborn:depletedquadthoriumfuelrod>,
    <techreborn:depleteddualthoriumfuelrod>,
    <techreborn:depletedsinglethoriumfuelrod>,
    <techreborn:quadthoriumfuelrod>,
    <techreborn:singlethoriumfuelrod>,
    <techreborn:dualthoriumfuelrod>,
    <techreborn:plates:16>,
    <techreborn:plates:18>,
    <techreborn:plates:20>,
    <techreborn:plates:38>
];

for item in iestage {
    mods.recipestages.Recipes.setRecipeStage("industrial", item);
    mods.ItemStages.addItemStage("industrial", item);
}