//#priority 349
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

val tcstage as IItemStack[] = [
    <tconstruct:soil>,
    <tconstruct:soil:1>,
    <tconstruct:soil:2>,
    <tconstruct:soil:3>,
    <tconstruct:soil:4>,
    <tconstruct:soil:5>,
    <tconstruct:slime>,
    <tconstruct:slime:1>,
    <tconstruct:slime:2>,
    <tconstruct:ore:1>,
    <tconstruct:ore>,
    <tconstruct:slime:4>,
    <tconstruct:slime:3>,
    <tconstruct:firewood>,
    <tconstruct:firewood:1>,
    <tconstruct:deco_ground>,
    <tconstruct:clear_glass>,
    <tconstruct:clear_stained_glass>,
    <tconstruct:clear_stained_glass:1>,
    <tconstruct:clear_stained_glass:2>,
    <tconstruct:clear_stained_glass:3>,
    <tconstruct:clear_stained_glass:4>,
    <tconstruct:wooden_hopper>,
    <tconstruct:fancy_frame:6>,
    <tconstruct:fancy_frame:5>,
    <tconstruct:fancy_frame:4>,
    <tconstruct:fancy_frame:3>,
    <tconstruct:fancy_frame:2>,
    <tconstruct:fancy_frame:1>,
    <tconstruct:fancy_frame>,
    <tconstruct:clear_stained_glass:14>,
    <tconstruct:clear_stained_glass:15>,
    <tconstruct:deco_ground_slab>,
    <tconstruct:firewood_slab>,
    <tconstruct:firewood_slab:1>,
    <tconstruct:mudbrick_stairs>,
    <tconstruct:firewood_stairs>,
    <tconstruct:lavawood_stairs>,
    <tconstruct:clear_stained_glass:5>,
    <tconstruct:clear_stained_glass:6>,
    <tconstruct:clear_stained_glass:7>,
    <tconstruct:clear_stained_glass:8>,
    <tconstruct:clear_stained_glass:9>,
    <tconstruct:clear_stained_glass:10>,
    <tconstruct:clear_stained_glass:11>,
    <tconstruct:clear_stained_glass:12>,
    <tconstruct:clear_stained_glass:13>,
    <tconstruct:materials>,
    <tconstruct:materials:1>,
    <tconstruct:materials:2>,
    <tconstruct:materials:9>,
    <tconstruct:materials:10>,
    <tconstruct:materials:11>,
    <tconstruct:materials:12>,
    <tconstruct:edible:3>,
    <tconstruct:edible:10>,
    <tconstruct:edible:11>,
    <tconstruct:edible:12>,
    <tconstruct:edible:13>,
    <tconstruct:edible:14>,
    <tconstruct:materials:13>,
    <tconstruct:materials:14>,
    <tconstruct:materials:15>,
    <tconstruct:materials:16>,
    <tconstruct:materials:17>,
    <tconstruct:materials:18>,
    <tconstruct:materials:19>,
    <tconstruct:materials:50>,
    <tconstruct:edible>,
    <tconstruct:edible:15>,
    <tconstruct:edible:20>,
    <tconstruct:edible:21>,
    <tconstruct:edible:22>,
    <tconstruct:edible:23>,
    <tconstruct:edible:30>,
    <tconstruct:edible:31>,
    <tconstruct:edible:32>,
    <tconstruct:edible:33>,
    <tconstruct:edible:34>,
    <tconstruct:slime_dirt>,
    <tconstruct:slime_dirt:1>,
    <tconstruct:slime_dirt:2>,
    <tconstruct:slime_dirt:3>,
    <tconstruct:slime_grass>,
    <tconstruct:slime_grass:1>,
    <tconstruct:slime_grass:2>,
    <tconstruct:slime_grass:3>,
    <tconstruct:slime_grass:4>,
    <tconstruct:slime_grass:5>,
    <tconstruct:slime_grass:6>,
    <tconstruct:slime_grass:7>,
    <tconstruct:slime_grass:8>,
    <tconstruct:slime_grass:10>,
    <tconstruct:slime_grass:11>,
    <tconstruct:slime_grass:12>,
    <tconstruct:slime_grass:13>,
    <tconstruct:slime_grass:14>,
    <tconstruct:slime_leaves>,
    <tconstruct:slime_leaves:1>,
    <tconstruct:slime_leaves:2>,
    <tconstruct:slime_grass_tall>,
    <tconstruct:slime_grass_tall:4>,
    <tconstruct:slime_grass_tall:8>,
    <tconstruct:slime_grass_tall:1>,
    <tconstruct:slime_grass_tall:5>,
    <tconstruct:slime_grass_tall:9>,
    <tconstruct:slime_sapling>,
    <tconstruct:slime_sapling:1>,
    <tconstruct:slime_sapling:2>,
    <tconstruct:slime_vine_blue_end>,
    <tconstruct:slime_vine_blue_mid>,
    <tconstruct:slime_vine_blue>,
    <tconstruct:slime_vine_purple_end>,
    <tconstruct:slime_vine_purple_mid>,
    <tconstruct:slime_vine_purple>,
    <tconstruct:pattern>,
    <tconstruct:tooltables>,
    <tconstruct:tooltables:1>,
    <tconstruct:tooltables:4>,
    <tconstruct:tooltables:2>,
    <tconstruct:tooltables:5>,
    <tconstruct:tooltables:3>,
    <tconstruct:toolforge>,
    <tconstruct:seared>,
    <tconstruct:seared:1>,
    <tconstruct:seared:2>,
    <tconstruct:seared:3>,
    <tconstruct:seared:4>,
    <tconstruct:seared:5>,
    <tconstruct:seared:6>,
    <tconstruct:seared:7>,
    <tconstruct:seared:8>,
    <tconstruct:seared:9>,
    <tconstruct:seared:10>,
    <tconstruct:seared:11>,
    <tconstruct:smeltery_controller>,
    <tconstruct:seared_tank>,
    <tconstruct:seared_tank:1>,
    <tconstruct:seared_tank:2>,
    <tconstruct:faucet>,
    <tconstruct:channel>,
    <tconstruct:casting>,
    <tconstruct:casting:1>,
    <tconstruct:smeltery_io>,
    <tconstruct:seared_glass>,
    <tconstruct:seared_furnace_controller>,
    <tconstruct:tinker_tank_controller>,
    <tconstruct:seared_slab>,
    <tconstruct:seared_slab:1>,
    <tconstruct:seared_slab:2>,
    <tconstruct:seared_slab:3>,
    <tconstruct:seared_slab:4>,
    <tconstruct:seared_slab:5>,
    <tconstruct:seared_slab:6>,
    <tconstruct:seared_slab:7>,
    <tconstruct:seared_slab2>,
    <tconstruct:seared_slab2:1>,
    <tconstruct:seared_slab2:2>,
    <tconstruct:seared_slab2:3>,
    <tconstruct:seared_stairs_stone>,
    <tconstruct:seared_stairs_cobble>,
    <tconstruct:seared_stairs_paver>,
    <tconstruct:seared_stairs_brick>,
    <tconstruct:seared_stairs_brick_cracked>,
    <tconstruct:seared_stairs_brick_fancy>,
    <tconstruct:seared_stairs_brick_square>,
    <tconstruct:seared_stairs_brick_triangle>,
    <tconstruct:seared_stairs_brick_small>,
    <tconstruct:seared_stairs_road>,
    <tconstruct:seared_stairs_tile>,
    <tconstruct:seared_stairs_creeper>,
    <tconstruct:cast>,
    <tconstruct:cast_custom>,
    <tconstruct:cast_custom:1>,
    <tconstruct:cast_custom:2>,
    <tconstruct:cast_custom:3>,
    <tconstruct:cast_custom:4>,
    <tconstruct:clay_cast>,
    <tconstruct:stone_ladder>,
    <tconstruct:punji>,
    <tconstruct:rack>,
    <tconstruct:rack:1>,
    <tconstruct:wood_rail>,
    <tconstruct:wood_rail_trapdoor>,
    <tconstruct:slime_channel>,
    <tconstruct:slime_channel:1>,
    <tconstruct:slime_channel:2>,
    <tconstruct:slime_channel:3>,
    <tconstruct:slime_channel:4>,
    <tconstruct:dried_clay>,
    <tconstruct:dried_clay:1>,
    <tconstruct:dried_clay_slab>,
    <tconstruct:dried_clay_slab:1>,
    <tconstruct:dried_clay_stairs>,
    <tconstruct:dried_brick_stairs>,
    <tconstruct:brownstone>,
    <tconstruct:brownstone:1>,
    <tconstruct:brownstone:2>,
    <tconstruct:brownstone:3>,
    <tconstruct:brownstone:4>,
    <tconstruct:brownstone:5>,
    <tconstruct:brownstone:6>,
    <tconstruct:brownstone:7>,
    <tconstruct:brownstone:8>,
    <tconstruct:brownstone:9>,
    <tconstruct:brownstone:10>,
    <tconstruct:brownstone:11>,
    <tconstruct:brownstone_slab>,
    <tconstruct:brownstone_slab:1>,
    <tconstruct:brownstone_slab:2>,
    <tconstruct:brownstone_slab:3>,
    <tconstruct:brownstone_slab:4>,
    <tconstruct:brownstone_slab:5>,
    <tconstruct:brownstone_slab:6>,
    <tconstruct:brownstone_slab:7>,
    <tconstruct:brownstone_slab2>,
    <tconstruct:brownstone_slab2:1>,
    <tconstruct:brownstone_slab2:2>,
    <tconstruct:brownstone_slab2:3>,
    <tconstruct:brownstone_stairs_smooth>,
    <tconstruct:brownstone_stairs_rough>,
    <tconstruct:brownstone_stairs_paver>,
    <tconstruct:brownstone_stairs_brick>,
    <tconstruct:brownstone_stairs_brick_cracked>,
    <tconstruct:brownstone_stairs_brick_fancy>,
    <tconstruct:brownstone_stairs_brick_square>,
    <tconstruct:brownstone_stairs_brick_triangle>,
    <tconstruct:brownstone_stairs_brick_small>,
    <tconstruct:brownstone_stairs_road>,
    <tconstruct:brownstone_stairs_tile>,
    <tconstruct:brownstone_stairs_creeper>,
    <tconstruct:slimesling>,
    <tconstruct:slimesling:1>,
    <tconstruct:slimesling:2>,
    <tconstruct:slimesling:3>,
    <tconstruct:slimesling:4>,
    <tconstruct:slime_boots>,
    <tconstruct:slime_boots:1>,
    <tconstruct:slime_boots:2>,
    <tconstruct:slime_boots:3>,
    <tconstruct:slime_boots:4>,
    <tconstruct:piggybackpack>,
    <tconstruct:throwball>,
    <tconstruct:throwball:1>,
    <tconstruct:spaghetti>,
    <tconstruct:moms_spaghetti>,
    <tconstruct:slime_grass:9>,
    <tconstruct:pattern>.withTag({PartType: "conarm:helmet_core"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:arrow_shaft"}),
    <tconstruct:pattern>.withTag({PartType: "conarm:polishing_kit"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:binding"}),
    <tconstruct:pattern>.withTag({PartType: "conarm:leggings_core"}),
    <tconstruct:pattern>.withTag({PartType: "conarm:armor_trim"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:sword_blade"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:excavator_head"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:kama_head"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:tough_binding"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:large_sword_blade"}),
    <tconstruct:pattern>.withTag({PartType: "plustic:laser_medium"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:bow_string"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:hand_guard"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:bow_limb"}),
    <tconstruct:pattern>.withTag({PartType: "plustic:pipe_piece"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:pick_head"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:shard"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:large_plate"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:knife_blade"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:fletching"}),
    <tconstruct:pattern>.withTag({PartType: "plustic:battery_cell"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:arrow_head"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:hammer_head"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:sharpening_kit"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:cross_guard"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:axe_head"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:broad_axe_head"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:sign_head"}),
    <tconstruct:pattern>.withTag({PartType: "conarm:chest_core"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:tough_tool_rod"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:scythe_head"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:wide_guard"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:tool_rod"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:pan_head"}),
    <tconstruct:pattern>.withTag({PartType: "conarm:boots_core"}),
    <tconstruct:pattern>.withTag({PartType: "conarm:armor_plate"}),
    <tconstruct:pattern>.withTag({PartType: "tconstruct:shovel_head"}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "minecraft:planks", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:2>.withTag({textureBlock: {id: "minecraft:log", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "minecraft:iron_block", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:cast>.withTag({PartType: "conarm:helmet_core"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:arrow_shaft"}),
    <tconstruct:cast>.withTag({PartType: "conarm:polishing_kit"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:binding"}),
    <tconstruct:cast>.withTag({PartType: "conarm:leggings_core"}),
    <tconstruct:cast>.withTag({PartType: "conarm:armor_trim"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:sword_blade"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:tool_rod"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:excavator_head"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:kama_head"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:tough_binding"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:large_sword_blade"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:bow_string"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:hand_guard"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:bow_limb"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:pick_head"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:shard"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:large_plate"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:knife_blade"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:fletching"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:arrow_head"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:hammer_head"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:sharpening_kit"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:cross_guard"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:axe_head"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:broad_axe_head"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:sign_head"}),
    <tconstruct:cast>.withTag({PartType: "conarm:chest_core"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:tough_tool_rod"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:scythe_head"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:wide_guard"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:pan_head"}),
    <tconstruct:cast>.withTag({PartType: "conarm:boots_core"}),
    <tconstruct:cast>.withTag({PartType: "conarm:armor_plate"}),
    <tconstruct:cast>.withTag({PartType: "tconstruct:shovel_head"}),
    <tconstruct:clay_cast>.withTag({PartType: "conarm:helmet_core"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:arrow_shaft"}),
    <tconstruct:clay_cast>.withTag({PartType: "conarm:polishing_kit"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:binding"}),
    <tconstruct:clay_cast>.withTag({PartType: "conarm:leggings_core"}),
    <tconstruct:clay_cast>.withTag({PartType: "conarm:armor_trim"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:sword_blade"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:tool_rod"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:excavator_head"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:kama_head"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:tough_binding"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:large_sword_blade"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:bow_string"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:hand_guard"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:bow_limb"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:pick_head"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:shard"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:large_plate"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:knife_blade"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:fletching"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:arrow_head"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:hammer_head"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:sharpening_kit"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:cross_guard"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:axe_head"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:broad_axe_head"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:sign_head"}),
    <tconstruct:clay_cast>.withTag({PartType: "conarm:chest_core"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:tough_tool_rod"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:scythe_head"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:wide_guard"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:pan_head"}),
    <tconstruct:clay_cast>.withTag({PartType: "conarm:boots_core"}),
    <tconstruct:clay_cast>.withTag({PartType: "conarm:armor_plate"}),
    <tconstruct:clay_cast>.withTag({PartType: "tconstruct:shovel_head"}),
    <tconstruct:rack>.withTag({textureBlock: {id: "minecraft:wooden_slab", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:rack:1>.withTag({textureBlock: {id: "minecraft:wooden_slab", Count: 1 as byte, Damage: 0 as short}}),
    <culinaryconstruct:sandwich_station>,
    <culinaryconstruct:sandwich>.withTag({Size: 5, Saturation: 1.0 as float, Ingredients: {Items: [{Slot: 0 as byte, id: "minecraft:nether_star", Count: 1 as byte, Damage: 0 as short}, {Slot: 1 as byte, id: "minecraft:nether_star", Count: 1 as byte, Damage: 0 as short}, {Slot: 2 as byte, id: "minecraft:nether_star", Count: 1 as byte, Damage: 0 as short}, {Slot: 3 as byte, id: "minecraft:nether_star", Count: 1 as byte, Damage: 0 as short}, {Slot: 4 as byte, id: "minecraft:nether_star", Count: 1 as byte, Damage: 0 as short}, {Slot: 5 as byte, id: "minecraft:bread", Count: 1 as byte, Damage: 0 as short}]}, Bonus: 2, Depth: 0, Food: 20}),
    <tconstruct:metal:6>,
    <tconstruct:shard>.withTag({Material: "electrical_steel"}),
    <tconstruct:shard>.withTag({Material: "energetic_alloy"}),
    <tconstruct:shard>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:shard>.withTag({Material: "redstone_alloy"}),
    <tconstruct:shard>.withTag({Material: "conductive_iron"}),
    <tconstruct:shard>.withTag({Material: "pulsating_iron"}),
    <tconstruct:shard>.withTag({Material: "dark_steel"}),
    <tconstruct:shard>.withTag({Material: "soularium"}),
    <tconstruct:shard>.withTag({Material: "end_steel"}),
    <tconstruct:shard>.withTag({Material: "construction_alloy"}),
    <tconstruct:shard>.withTag({Material: "stone"}),
    <tconstruct:shard>.withTag({Material: "flint"}),
    <tconstruct:shard>.withTag({Material: "cactus"}),
    <tconstruct:shard>.withTag({Material: "bone"}),
    <tconstruct:shard>.withTag({Material: "obsidian"}),
    <tconstruct:shard>.withTag({Material: "prismarine"}),
    <tconstruct:shard>.withTag({Material: "endstone"}),
    <tconstruct:shard>.withTag({Material: "paper"}),
    <tconstruct:shard>.withTag({Material: "sponge"}),
    <tconstruct:shard>.withTag({Material: "firewood"}),
    <tconstruct:shard>.withTag({Material: "iron"}),
    <tconstruct:shard>.withTag({Material: "pigiron"}),
    <tconstruct:shard>.withTag({Material: "knightslime"}),
    <tconstruct:shard>.withTag({Material: "slime"}),
    <tconstruct:shard>.withTag({Material: "blueslime"}),
    <tconstruct:shard>.withTag({Material: "magmaslime"}),
    <tconstruct:shard>.withTag({Material: "netherrack"}),
    <tconstruct:shard>.withTag({Material: "cobalt"}),
    <tconstruct:shard>.withTag({Material: "ardite"}),
    <tconstruct:shard>.withTag({Material: "manyullyn"}),
    <tconstruct:shard>.withTag({Material: "copper"}),
    <tconstruct:shard>.withTag({Material: "bronze"}),
    <tconstruct:shard>.withTag({Material: "lead"}),
    <tconstruct:shard>.withTag({Material: "silver"}),
    <tconstruct:shard>.withTag({Material: "electrum"}),
    <tconstruct:shard>.withTag({Material: "steel"}),
    <tconstruct:shard>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:shard>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:shard>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:shard>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:shard>.withTag({Material: "boron"}),
    <tconstruct:shard>.withTag({Material: "tough"}),
    <tconstruct:shard>.withTag({Material: "hard_carbon"}),
    <tconstruct:shard>.withTag({Material: "boron_nitride"}),
    <tconstruct:shard>.withTag({Material: "thorium"}),
    <tconstruct:shard>.withTag({Material: "uranium"}),
    <tconstruct:shard>.withTag({Material: "magnesium"}),
    <tconstruct:shard>.withTag({Material: "chocolate"}),
    <tconstruct:shard>.withTag({Material: "treatedwood"}),
    <tconstruct:shard>.withTag({Material: "constantan"}),
    <tconstruct:shard>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:shard>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:shard>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:shard>.withTag({Material: "alumite"}),
    <tconstruct:shard>.withTag({Material: "nickel"}),
    <tconstruct:shard>.withTag({Material: "invar"}),
    <tconstruct:shard>.withTag({Material: "iridium"}),
    <tconstruct:shard>.withTag({Material: "sapphire"}),
    <tconstruct:shard>.withTag({Material: "ruby"}),
    <tconstruct:shard>.withTag({Material: "peridot"}),
    <tconstruct:shard>.withTag({Material: "osmium"}),
    <tconstruct:shard>.withTag({Material: "refinedobsidian"}),
    <tconstruct:shard>.withTag({Material: "refinedglowstone"}),
    <tconstruct:shard>.withTag({Material: "osgloglas"}),
    <tconstruct:shard>.withTag({Material: "osmiridium"}),
    <tconstruct:shard>.withTag({Material: "lumium_plustic"}),
    <tconstruct:shard>.withTag({Material: "signalum_plustic"}),
    <tconstruct:shard>.withTag({Material: "platinum_plustic"}),
    <tconstruct:shard>.withTag({Material: "enderium_plustic"}),
    <tconstruct:shard>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:shard>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:shard>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:shard>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:shard>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:shard>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:shard>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:shard>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:shard>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:shard>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:shard>.withTag({Material: "mica"}),
    <tconstruct:shard>.withTag({Material: "litherite"}),
    <tconstruct:shard>.withTag({Material: "erodium"}),
    <tconstruct:shard>.withTag({Material: "kyronite"}),
    <tconstruct:shard>.withTag({Material: "pladium"}),
    <tconstruct:shard>.withTag({Material: "ionite"}),
    <tconstruct:shard>.withTag({Material: "aethium"}),
    <tconstruct:shard>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:shard>.withTag({Material: "awakened_plustic"}),
    <tconstruct:shard>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:shard>.withTag({Material: "darkmatter"}),
    <tconstruct:shard>.withTag({Material: "redmatter"}),
    <tconstruct:shard>.withTag({Material: "emerald_plustic"}),
    <tconstruct:shard>.withTag({Material: "wood"}),
    <tconstruct:sharpening_kit>.withTag({Material: "electrical_steel"}),
    <tconstruct:sharpening_kit>.withTag({Material: "energetic_alloy"}),
    <tconstruct:sharpening_kit>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:sharpening_kit>.withTag({Material: "redstone_alloy"}),
    <tconstruct:sharpening_kit>.withTag({Material: "conductive_iron"}),
    <tconstruct:sharpening_kit>.withTag({Material: "pulsating_iron"}),
    <tconstruct:sharpening_kit>.withTag({Material: "dark_steel"}),
    <tconstruct:sharpening_kit>.withTag({Material: "soularium"}),
    <tconstruct:sharpening_kit>.withTag({Material: "end_steel"}),
    <tconstruct:sharpening_kit>.withTag({Material: "construction_alloy"}),
    <tconstruct:sharpening_kit>.withTag({Material: "stone"}),
    <tconstruct:sharpening_kit>.withTag({Material: "flint"}),
    <tconstruct:sharpening_kit>.withTag({Material: "cactus"}),
    <tconstruct:sharpening_kit>.withTag({Material: "bone"}),
    <tconstruct:sharpening_kit>.withTag({Material: "obsidian"}),
    <tconstruct:sharpening_kit>.withTag({Material: "prismarine"}),
    <tconstruct:sharpening_kit>.withTag({Material: "endstone"}),
    <tconstruct:sharpening_kit>.withTag({Material: "paper"}),
    <tconstruct:sharpening_kit>.withTag({Material: "sponge"}),
    <tconstruct:sharpening_kit>.withTag({Material: "firewood"}),
    <tconstruct:sharpening_kit>.withTag({Material: "iron"}),
    <tconstruct:sharpening_kit>.withTag({Material: "pigiron"}),
    <tconstruct:sharpening_kit>.withTag({Material: "knightslime"}),
    <tconstruct:sharpening_kit>.withTag({Material: "slime"}),
    <tconstruct:sharpening_kit>.withTag({Material: "blueslime"}),
    <tconstruct:sharpening_kit>.withTag({Material: "magmaslime"}),
    <tconstruct:sharpening_kit>.withTag({Material: "netherrack"}),
    <tconstruct:sharpening_kit>.withTag({Material: "cobalt"}),
    <tconstruct:sharpening_kit>.withTag({Material: "ardite"}),
    <tconstruct:sharpening_kit>.withTag({Material: "manyullyn"}),
    <tconstruct:sharpening_kit>.withTag({Material: "copper"}),
    <tconstruct:sharpening_kit>.withTag({Material: "bronze"}),
    <tconstruct:sharpening_kit>.withTag({Material: "lead"}),
    <tconstruct:sharpening_kit>.withTag({Material: "silver"}),
    <tconstruct:sharpening_kit>.withTag({Material: "electrum"}),
    <tconstruct:sharpening_kit>.withTag({Material: "steel"}),
    <tconstruct:sharpening_kit>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:sharpening_kit>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:sharpening_kit>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:sharpening_kit>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:sharpening_kit>.withTag({Material: "boron"}),
    <tconstruct:sharpening_kit>.withTag({Material: "tough"}),
    <tconstruct:sharpening_kit>.withTag({Material: "hard_carbon"}),
    <tconstruct:sharpening_kit>.withTag({Material: "boron_nitride"}),
    <tconstruct:sharpening_kit>.withTag({Material: "thorium"}),
    <tconstruct:sharpening_kit>.withTag({Material: "uranium"}),
    <tconstruct:sharpening_kit>.withTag({Material: "magnesium"}),
    <tconstruct:sharpening_kit>.withTag({Material: "chocolate"}),
    <tconstruct:sharpening_kit>.withTag({Material: "treatedwood"}),
    <tconstruct:sharpening_kit>.withTag({Material: "constantan"}),
    <tconstruct:sharpening_kit>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:sharpening_kit>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:sharpening_kit>.withTag({Material: "alumite"}),
    <tconstruct:sharpening_kit>.withTag({Material: "nickel"}),
    <tconstruct:sharpening_kit>.withTag({Material: "invar"}),
    <tconstruct:sharpening_kit>.withTag({Material: "iridium"}),
    <tconstruct:sharpening_kit>.withTag({Material: "sapphire"}),
    <tconstruct:sharpening_kit>.withTag({Material: "ruby"}),
    <tconstruct:sharpening_kit>.withTag({Material: "peridot"}),
    <tconstruct:sharpening_kit>.withTag({Material: "osmium"}),
    <tconstruct:sharpening_kit>.withTag({Material: "refinedobsidian"}),
    <tconstruct:sharpening_kit>.withTag({Material: "refinedglowstone"}),
    <tconstruct:sharpening_kit>.withTag({Material: "osgloglas"}),
    <tconstruct:sharpening_kit>.withTag({Material: "osmiridium"}),
    <tconstruct:sharpening_kit>.withTag({Material: "lumium_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "signalum_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "platinum_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "enderium_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "mica"}),
    <tconstruct:sharpening_kit>.withTag({Material: "litherite"}),
    <tconstruct:sharpening_kit>.withTag({Material: "erodium"}),
    <tconstruct:sharpening_kit>.withTag({Material: "kyronite"}),
    <tconstruct:sharpening_kit>.withTag({Material: "pladium"}),
    <tconstruct:sharpening_kit>.withTag({Material: "ionite"}),
    <tconstruct:sharpening_kit>.withTag({Material: "aethium"}),
    <tconstruct:sharpening_kit>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "awakened_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "darkmatter"}),
    <tconstruct:sharpening_kit>.withTag({Material: "redmatter"}),
    <tconstruct:sharpening_kit>.withTag({Material: "emerald_plustic"}),
    <tconstruct:sharpening_kit>.withTag({Material: "wood"}),
    <tconstruct:pick_head>.withTag({Material: "electrical_steel"}),
    <tconstruct:pick_head>.withTag({Material: "energetic_alloy"}),
    <tconstruct:pick_head>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:pick_head>.withTag({Material: "redstone_alloy"}),
    <tconstruct:pick_head>.withTag({Material: "conductive_iron"}),
    <tconstruct:pick_head>.withTag({Material: "pulsating_iron"}),
    <tconstruct:pick_head>.withTag({Material: "dark_steel"}),
    <tconstruct:pick_head>.withTag({Material: "soularium"}),
    <tconstruct:pick_head>.withTag({Material: "end_steel"}),
    <tconstruct:pick_head>.withTag({Material: "construction_alloy"}),
    <tconstruct:pick_head>.withTag({Material: "stone"}),
    <tconstruct:pick_head>.withTag({Material: "flint"}),
    <tconstruct:pick_head>.withTag({Material: "cactus"}),
    <tconstruct:pick_head>.withTag({Material: "bone"}),
    <tconstruct:pick_head>.withTag({Material: "obsidian"}),
    <tconstruct:pick_head>.withTag({Material: "prismarine"}),
    <tconstruct:pick_head>.withTag({Material: "endstone"}),
    <tconstruct:pick_head>.withTag({Material: "paper"}),
    <tconstruct:pick_head>.withTag({Material: "sponge"}),
    <tconstruct:pick_head>.withTag({Material: "firewood"}),
    <tconstruct:pick_head>.withTag({Material: "iron"}),
    <tconstruct:pick_head>.withTag({Material: "pigiron"}),
    <tconstruct:pick_head>.withTag({Material: "knightslime"}),
    <tconstruct:pick_head>.withTag({Material: "slime"}),
    <tconstruct:pick_head>.withTag({Material: "blueslime"}),
    <tconstruct:pick_head>.withTag({Material: "magmaslime"}),
    <tconstruct:pick_head>.withTag({Material: "netherrack"}),
    <tconstruct:pick_head>.withTag({Material: "cobalt"}),
    <tconstruct:pick_head>.withTag({Material: "ardite"}),
    <tconstruct:pick_head>.withTag({Material: "manyullyn"}),
    <tconstruct:pick_head>.withTag({Material: "copper"}),
    <tconstruct:pick_head>.withTag({Material: "bronze"}),
    <tconstruct:pick_head>.withTag({Material: "lead"}),
    <tconstruct:pick_head>.withTag({Material: "silver"}),
    <tconstruct:pick_head>.withTag({Material: "electrum"}),
    <tconstruct:pick_head>.withTag({Material: "steel"}),
    <tconstruct:pick_head>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:pick_head>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:pick_head>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:pick_head>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:pick_head>.withTag({Material: "boron"}),
    <tconstruct:pick_head>.withTag({Material: "tough"}),
    <tconstruct:pick_head>.withTag({Material: "hard_carbon"}),
    <tconstruct:pick_head>.withTag({Material: "boron_nitride"}),
    <tconstruct:pick_head>.withTag({Material: "thorium"}),
    <tconstruct:pick_head>.withTag({Material: "uranium"}),
    <tconstruct:pick_head>.withTag({Material: "magnesium"}),
    <tconstruct:pick_head>.withTag({Material: "chocolate"}),
    <tconstruct:pick_head>.withTag({Material: "treatedwood"}),
    <tconstruct:pick_head>.withTag({Material: "constantan"}),
    <tconstruct:pick_head>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:pick_head>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:pick_head>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:pick_head>.withTag({Material: "alumite"}),
    <tconstruct:pick_head>.withTag({Material: "nickel"}),
    <tconstruct:pick_head>.withTag({Material: "invar"}),
    <tconstruct:pick_head>.withTag({Material: "iridium"}),
    <tconstruct:pick_head>.withTag({Material: "sapphire"}),
    <tconstruct:pick_head>.withTag({Material: "ruby"}),
    <tconstruct:pick_head>.withTag({Material: "peridot"}),
    <tconstruct:pick_head>.withTag({Material: "osmium"}),
    <tconstruct:pick_head>.withTag({Material: "refinedobsidian"}),
    <tconstruct:pick_head>.withTag({Material: "refinedglowstone"}),
    <tconstruct:pick_head>.withTag({Material: "osgloglas"}),
    <tconstruct:pick_head>.withTag({Material: "osmiridium"}),
    <tconstruct:pick_head>.withTag({Material: "lumium_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "signalum_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "platinum_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "enderium_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "mica"}),
    <tconstruct:pick_head>.withTag({Material: "litherite"}),
    <tconstruct:pick_head>.withTag({Material: "erodium"}),
    <tconstruct:pick_head>.withTag({Material: "kyronite"}),
    <tconstruct:pick_head>.withTag({Material: "pladium"}),
    <tconstruct:pick_head>.withTag({Material: "ionite"}),
    <tconstruct:pick_head>.withTag({Material: "aethium"}),
    <tconstruct:pick_head>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "awakened_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "darkmatter"}),
    <tconstruct:pick_head>.withTag({Material: "redmatter"}),
    <tconstruct:pick_head>.withTag({Material: "emerald_plustic"}),
    <tconstruct:pick_head>.withTag({Material: "wood"}),
    <tconstruct:shovel_head>.withTag({Material: "energetic_alloy"}),
    <tconstruct:shovel_head>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:shovel_head>.withTag({Material: "redstone_alloy"}),
    <tconstruct:shovel_head>.withTag({Material: "conductive_iron"}),
    <tconstruct:shovel_head>.withTag({Material: "pulsating_iron"}),
    <tconstruct:shovel_head>.withTag({Material: "dark_steel"}),
    <tconstruct:shovel_head>.withTag({Material: "soularium"}),
    <tconstruct:shovel_head>.withTag({Material: "end_steel"}),
    <tconstruct:shovel_head>.withTag({Material: "electrical_steel"}),
    <tconstruct:shovel_head>.withTag({Material: "construction_alloy"}),
    <tconstruct:shovel_head>.withTag({Material: "stone"}),
    <tconstruct:shovel_head>.withTag({Material: "flint"}),
    <tconstruct:shovel_head>.withTag({Material: "cactus"}),
    <tconstruct:shovel_head>.withTag({Material: "bone"}),
    <tconstruct:shovel_head>.withTag({Material: "obsidian"}),
    <tconstruct:shovel_head>.withTag({Material: "prismarine"}),
    <tconstruct:shovel_head>.withTag({Material: "endstone"}),
    <tconstruct:shovel_head>.withTag({Material: "paper"}),
    <tconstruct:shovel_head>.withTag({Material: "netherrack"}),
    <tconstruct:shovel_head>.withTag({Material: "magmaslime"}),
    <tconstruct:shovel_head>.withTag({Material: "blueslime"}),
    <tconstruct:shovel_head>.withTag({Material: "slime"}),
    <tconstruct:shovel_head>.withTag({Material: "knightslime"}),
    <tconstruct:shovel_head>.withTag({Material: "pigiron"}),
    <tconstruct:shovel_head>.withTag({Material: "iron"}),
    <tconstruct:shovel_head>.withTag({Material: "firewood"}),
    <tconstruct:shovel_head>.withTag({Material: "sponge"}),
    <tconstruct:shovel_head>.withTag({Material: "cobalt"}),
    <tconstruct:shovel_head>.withTag({Material: "ardite"}),
    <tconstruct:shovel_head>.withTag({Material: "manyullyn"}),
    <tconstruct:shovel_head>.withTag({Material: "copper"}),
    <tconstruct:shovel_head>.withTag({Material: "bronze"}),
    <tconstruct:shovel_head>.withTag({Material: "lead"}),
    <tconstruct:shovel_head>.withTag({Material: "silver"}),
    <tconstruct:shovel_head>.withTag({Material: "electrum"}),
    <tconstruct:shovel_head>.withTag({Material: "steel"}),
    <tconstruct:shovel_head>.withTag({Material: "thorium"}),
    <tconstruct:shovel_head>.withTag({Material: "boron_nitride"}),
    <tconstruct:shovel_head>.withTag({Material: "hard_carbon"}),
    <tconstruct:shovel_head>.withTag({Material: "tough"}),
    <tconstruct:shovel_head>.withTag({Material: "boron"}),
    <tconstruct:shovel_head>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:shovel_head>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:shovel_head>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:shovel_head>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:shovel_head>.withTag({Material: "uranium"}),
    <tconstruct:shovel_head>.withTag({Material: "magnesium"}),
    <tconstruct:shovel_head>.withTag({Material: "chocolate"}),
    <tconstruct:shovel_head>.withTag({Material: "treatedwood"}),
    <tconstruct:shovel_head>.withTag({Material: "constantan"}),
    <tconstruct:shovel_head>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:shovel_head>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:shovel_head>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:shovel_head>.withTag({Material: "alumite"}),
    <tconstruct:shovel_head>.withTag({Material: "refinedglowstone"}),
    <tconstruct:shovel_head>.withTag({Material: "refinedobsidian"}),
    <tconstruct:shovel_head>.withTag({Material: "osmium"}),
    <tconstruct:shovel_head>.withTag({Material: "peridot"}),
    <tconstruct:shovel_head>.withTag({Material: "iridium"}),
    <tconstruct:shovel_head>.withTag({Material: "invar"}),
    <tconstruct:shovel_head>.withTag({Material: "nickel"}),
    <tconstruct:shovel_head>.withTag({Material: "sapphire"}),
    <tconstruct:shovel_head>.withTag({Material: "ruby"}),
    <tconstruct:shovel_head>.withTag({Material: "osgloglas"}),
    <tconstruct:shovel_head>.withTag({Material: "osmiridium"}),
    <tconstruct:shovel_head>.withTag({Material: "lumium_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "signalum_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "platinum_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "enderium_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "mica"}),
    <tconstruct:shovel_head>.withTag({Material: "litherite"}),
    <tconstruct:shovel_head>.withTag({Material: "erodium"}),
    <tconstruct:shovel_head>.withTag({Material: "kyronite"}),
    <tconstruct:shovel_head>.withTag({Material: "pladium"}),
    <tconstruct:shovel_head>.withTag({Material: "ionite"}),
    <tconstruct:shovel_head>.withTag({Material: "aethium"}),
    <tconstruct:shovel_head>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "awakened_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:shovel_head>.withTag({Material: "darkmatter"}),
    <tconstruct:shovel_head>.withTag({Material: "wood"}),
    <tconstruct:shovel_head>.withTag({Material: "redmatter"}),
    <tconstruct:shovel_head>.withTag({Material: "emerald_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "electrical_steel"}),
    <tconstruct:axe_head>.withTag({Material: "energetic_alloy"}),
    <tconstruct:axe_head>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:axe_head>.withTag({Material: "redstone_alloy"}),
    <tconstruct:axe_head>.withTag({Material: "conductive_iron"}),
    <tconstruct:axe_head>.withTag({Material: "pulsating_iron"}),
    <tconstruct:axe_head>.withTag({Material: "dark_steel"}),
    <tconstruct:axe_head>.withTag({Material: "soularium"}),
    <tconstruct:axe_head>.withTag({Material: "end_steel"}),
    <tconstruct:axe_head>.withTag({Material: "construction_alloy"}),
    <tconstruct:axe_head>.withTag({Material: "stone"}),
    <tconstruct:axe_head>.withTag({Material: "flint"}),
    <tconstruct:axe_head>.withTag({Material: "cactus"}),
    <tconstruct:axe_head>.withTag({Material: "bone"}),
    <tconstruct:axe_head>.withTag({Material: "obsidian"}),
    <tconstruct:axe_head>.withTag({Material: "prismarine"}),
    <tconstruct:axe_head>.withTag({Material: "endstone"}),
    <tconstruct:axe_head>.withTag({Material: "paper"}),
    <tconstruct:axe_head>.withTag({Material: "sponge"}),
    <tconstruct:axe_head>.withTag({Material: "firewood"}),
    <tconstruct:axe_head>.withTag({Material: "iron"}),
    <tconstruct:axe_head>.withTag({Material: "pigiron"}),
    <tconstruct:axe_head>.withTag({Material: "knightslime"}),
    <tconstruct:axe_head>.withTag({Material: "slime"}),
    <tconstruct:axe_head>.withTag({Material: "blueslime"}),
    <tconstruct:axe_head>.withTag({Material: "magmaslime"}),
    <tconstruct:axe_head>.withTag({Material: "netherrack"}),
    <tconstruct:axe_head>.withTag({Material: "cobalt"}),
    <tconstruct:axe_head>.withTag({Material: "ardite"}),
    <tconstruct:axe_head>.withTag({Material: "manyullyn"}),
    <tconstruct:axe_head>.withTag({Material: "copper"}),
    <tconstruct:axe_head>.withTag({Material: "bronze"}),
    <tconstruct:axe_head>.withTag({Material: "lead"}),
    <tconstruct:axe_head>.withTag({Material: "silver"}),
    <tconstruct:axe_head>.withTag({Material: "electrum"}),
    <tconstruct:axe_head>.withTag({Material: "steel"}),
    <tconstruct:axe_head>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:axe_head>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:axe_head>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:axe_head>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:axe_head>.withTag({Material: "boron"}),
    <tconstruct:axe_head>.withTag({Material: "tough"}),
    <tconstruct:axe_head>.withTag({Material: "hard_carbon"}),
    <tconstruct:axe_head>.withTag({Material: "boron_nitride"}),
    <tconstruct:axe_head>.withTag({Material: "thorium"}),
    <tconstruct:axe_head>.withTag({Material: "uranium"}),
    <tconstruct:axe_head>.withTag({Material: "magnesium"}),
    <tconstruct:axe_head>.withTag({Material: "chocolate"}),
    <tconstruct:axe_head>.withTag({Material: "treatedwood"}),
    <tconstruct:axe_head>.withTag({Material: "constantan"}),
    <tconstruct:axe_head>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:axe_head>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:axe_head>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:axe_head>.withTag({Material: "alumite"}),
    <tconstruct:axe_head>.withTag({Material: "refinedglowstone"}),
    <tconstruct:axe_head>.withTag({Material: "refinedobsidian"}),
    <tconstruct:axe_head>.withTag({Material: "osmium"}),
    <tconstruct:axe_head>.withTag({Material: "peridot"}),
    <tconstruct:axe_head>.withTag({Material: "ruby"}),
    <tconstruct:axe_head>.withTag({Material: "sapphire"}),
    <tconstruct:axe_head>.withTag({Material: "iridium"}),
    <tconstruct:axe_head>.withTag({Material: "invar"}),
    <tconstruct:axe_head>.withTag({Material: "nickel"}),
    <tconstruct:axe_head>.withTag({Material: "osgloglas"}),
    <tconstruct:axe_head>.withTag({Material: "osmiridium"}),
    <tconstruct:axe_head>.withTag({Material: "lumium_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "signalum_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "platinum_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "enderium_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "mica"}),
    <tconstruct:axe_head>.withTag({Material: "litherite"}),
    <tconstruct:axe_head>.withTag({Material: "erodium"}),
    <tconstruct:axe_head>.withTag({Material: "kyronite"}),
    <tconstruct:axe_head>.withTag({Material: "pladium"}),
    <tconstruct:axe_head>.withTag({Material: "ionite"}),
    <tconstruct:axe_head>.withTag({Material: "aethium"}),
    <tconstruct:axe_head>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "awakened_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "darkmatter"}),
    <tconstruct:axe_head>.withTag({Material: "redmatter"}),
    <tconstruct:axe_head>.withTag({Material: "emerald_plustic"}),
    <tconstruct:axe_head>.withTag({Material: "wood"}),
    <tconstruct:broad_axe_head>.withTag({Material: "electrical_steel"}),
    <tconstruct:broad_axe_head>.withTag({Material: "energetic_alloy"}),
    <tconstruct:broad_axe_head>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:broad_axe_head>.withTag({Material: "redstone_alloy"}),
    <tconstruct:broad_axe_head>.withTag({Material: "conductive_iron"}),
    <tconstruct:broad_axe_head>.withTag({Material: "pulsating_iron"}),
    <tconstruct:broad_axe_head>.withTag({Material: "dark_steel"}),
    <tconstruct:broad_axe_head>.withTag({Material: "soularium"}),
    <tconstruct:broad_axe_head>.withTag({Material: "end_steel"}),
    <tconstruct:broad_axe_head>.withTag({Material: "construction_alloy"}),
    <tconstruct:broad_axe_head>.withTag({Material: "stone"}),
    <tconstruct:broad_axe_head>.withTag({Material: "flint"}),
    <tconstruct:broad_axe_head>.withTag({Material: "cactus"}),
    <tconstruct:broad_axe_head>.withTag({Material: "bone"}),
    <tconstruct:broad_axe_head>.withTag({Material: "obsidian"}),
    <tconstruct:broad_axe_head>.withTag({Material: "prismarine"}),
    <tconstruct:broad_axe_head>.withTag({Material: "endstone"}),
    <tconstruct:broad_axe_head>.withTag({Material: "paper"}),
    <tconstruct:broad_axe_head>.withTag({Material: "sponge"}),
    <tconstruct:broad_axe_head>.withTag({Material: "firewood"}),
    <tconstruct:broad_axe_head>.withTag({Material: "iron"}),
    <tconstruct:broad_axe_head>.withTag({Material: "pigiron"}),
    <tconstruct:broad_axe_head>.withTag({Material: "knightslime"}),
    <tconstruct:broad_axe_head>.withTag({Material: "slime"}),
    <tconstruct:broad_axe_head>.withTag({Material: "blueslime"}),
    <tconstruct:broad_axe_head>.withTag({Material: "magmaslime"}),
    <tconstruct:broad_axe_head>.withTag({Material: "netherrack"}),
    <tconstruct:broad_axe_head>.withTag({Material: "cobalt"}),
    <tconstruct:broad_axe_head>.withTag({Material: "ardite"}),
    <tconstruct:broad_axe_head>.withTag({Material: "manyullyn"}),
    <tconstruct:broad_axe_head>.withTag({Material: "copper"}),
    <tconstruct:broad_axe_head>.withTag({Material: "bronze"}),
    <tconstruct:broad_axe_head>.withTag({Material: "lead"}),
    <tconstruct:broad_axe_head>.withTag({Material: "silver"}),
    <tconstruct:broad_axe_head>.withTag({Material: "electrum"}),
    <tconstruct:broad_axe_head>.withTag({Material: "steel"}),
    <tconstruct:broad_axe_head>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:broad_axe_head>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:broad_axe_head>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:broad_axe_head>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:broad_axe_head>.withTag({Material: "boron"}),
    <tconstruct:broad_axe_head>.withTag({Material: "tough"}),
    <tconstruct:broad_axe_head>.withTag({Material: "hard_carbon"}),
    <tconstruct:broad_axe_head>.withTag({Material: "boron_nitride"}),
    <tconstruct:broad_axe_head>.withTag({Material: "thorium"}),
    <tconstruct:broad_axe_head>.withTag({Material: "uranium"}),
    <tconstruct:broad_axe_head>.withTag({Material: "magnesium"}),
    <tconstruct:broad_axe_head>.withTag({Material: "chocolate"}),
    <tconstruct:broad_axe_head>.withTag({Material: "treatedwood"}),
    <tconstruct:broad_axe_head>.withTag({Material: "constantan"}),
    <tconstruct:broad_axe_head>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:broad_axe_head>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:broad_axe_head>.withTag({Material: "alumite"}),
    <tconstruct:broad_axe_head>.withTag({Material: "nickel"}),
    <tconstruct:broad_axe_head>.withTag({Material: "invar"}),
    <tconstruct:broad_axe_head>.withTag({Material: "iridium"}),
    <tconstruct:broad_axe_head>.withTag({Material: "sapphire"}),
    <tconstruct:broad_axe_head>.withTag({Material: "ruby"}),
    <tconstruct:broad_axe_head>.withTag({Material: "peridot"}),
    <tconstruct:broad_axe_head>.withTag({Material: "osmium"}),
    <tconstruct:broad_axe_head>.withTag({Material: "refinedobsidian"}),
    <tconstruct:broad_axe_head>.withTag({Material: "refinedglowstone"}),
    <tconstruct:broad_axe_head>.withTag({Material: "osgloglas"}),
    <tconstruct:broad_axe_head>.withTag({Material: "osmiridium"}),
    <tconstruct:broad_axe_head>.withTag({Material: "lumium_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "signalum_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "platinum_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "enderium_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "mica"}),
    <tconstruct:broad_axe_head>.withTag({Material: "litherite"}),
    <tconstruct:broad_axe_head>.withTag({Material: "erodium"}),
    <tconstruct:broad_axe_head>.withTag({Material: "kyronite"}),
    <tconstruct:broad_axe_head>.withTag({Material: "pladium"}),
    <tconstruct:broad_axe_head>.withTag({Material: "ionite"}),
    <tconstruct:broad_axe_head>.withTag({Material: "aethium"}),
    <tconstruct:broad_axe_head>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "awakened_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "darkmatter"}),
    <tconstruct:broad_axe_head>.withTag({Material: "redmatter"}),
    <tconstruct:broad_axe_head>.withTag({Material: "emerald_plustic"}),
    <tconstruct:broad_axe_head>.withTag({Material: "wood"}),
    <tconstruct:sword_blade>.withTag({Material: "electrical_steel"}),
    <tconstruct:sword_blade>.withTag({Material: "energetic_alloy"}),
    <tconstruct:sword_blade>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:sword_blade>.withTag({Material: "redstone_alloy"}),
    <tconstruct:sword_blade>.withTag({Material: "conductive_iron"}),
    <tconstruct:sword_blade>.withTag({Material: "pulsating_iron"}),
    <tconstruct:sword_blade>.withTag({Material: "dark_steel"}),
    <tconstruct:sword_blade>.withTag({Material: "soularium"}),
    <tconstruct:sword_blade>.withTag({Material: "end_steel"}),
    <tconstruct:sword_blade>.withTag({Material: "construction_alloy"}),
    <tconstruct:sword_blade>.withTag({Material: "stone"}),
    <tconstruct:sword_blade>.withTag({Material: "flint"}),
    <tconstruct:sword_blade>.withTag({Material: "cactus"}),
    <tconstruct:sword_blade>.withTag({Material: "bone"}),
    <tconstruct:sword_blade>.withTag({Material: "obsidian"}),
    <tconstruct:sword_blade>.withTag({Material: "prismarine"}),
    <tconstruct:sword_blade>.withTag({Material: "endstone"}),
    <tconstruct:sword_blade>.withTag({Material: "paper"}),
    <tconstruct:sword_blade>.withTag({Material: "sponge"}),
    <tconstruct:sword_blade>.withTag({Material: "firewood"}),
    <tconstruct:sword_blade>.withTag({Material: "iron"}),
    <tconstruct:sword_blade>.withTag({Material: "pigiron"}),
    <tconstruct:sword_blade>.withTag({Material: "knightslime"}),
    <tconstruct:sword_blade>.withTag({Material: "slime"}),
    <tconstruct:sword_blade>.withTag({Material: "blueslime"}),
    <tconstruct:sword_blade>.withTag({Material: "magmaslime"}),
    <tconstruct:sword_blade>.withTag({Material: "netherrack"}),
    <tconstruct:sword_blade>.withTag({Material: "cobalt"}),
    <tconstruct:sword_blade>.withTag({Material: "ardite"}),
    <tconstruct:sword_blade>.withTag({Material: "manyullyn"}),
    <tconstruct:sword_blade>.withTag({Material: "copper"}),
    <tconstruct:sword_blade>.withTag({Material: "bronze"}),
    <tconstruct:sword_blade>.withTag({Material: "lead"}),
    <tconstruct:sword_blade>.withTag({Material: "silver"}),
    <tconstruct:sword_blade>.withTag({Material: "electrum"}),
    <tconstruct:sword_blade>.withTag({Material: "steel"}),
    <tconstruct:sword_blade>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:sword_blade>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:sword_blade>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:sword_blade>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:sword_blade>.withTag({Material: "boron"}),
    <tconstruct:sword_blade>.withTag({Material: "tough"}),
    <tconstruct:sword_blade>.withTag({Material: "hard_carbon"}),
    <tconstruct:sword_blade>.withTag({Material: "boron_nitride"}),
    <tconstruct:sword_blade>.withTag({Material: "thorium"}),
    <tconstruct:sword_blade>.withTag({Material: "uranium"}),
    <tconstruct:sword_blade>.withTag({Material: "magnesium"}),
    <tconstruct:sword_blade>.withTag({Material: "chocolate"}),
    <tconstruct:sword_blade>.withTag({Material: "treatedwood"}),
    <tconstruct:sword_blade>.withTag({Material: "constantan"}),
    <tconstruct:sword_blade>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:sword_blade>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:sword_blade>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:sword_blade>.withTag({Material: "alumite"}),
    <tconstruct:sword_blade>.withTag({Material: "nickel"}),
    <tconstruct:sword_blade>.withTag({Material: "invar"}),
    <tconstruct:sword_blade>.withTag({Material: "iridium"}),
    <tconstruct:sword_blade>.withTag({Material: "sapphire"}),
    <tconstruct:sword_blade>.withTag({Material: "ruby"}),
    <tconstruct:sword_blade>.withTag({Material: "peridot"}),
    <tconstruct:sword_blade>.withTag({Material: "osmium"}),
    <tconstruct:sword_blade>.withTag({Material: "refinedobsidian"}),
    <tconstruct:sword_blade>.withTag({Material: "refinedglowstone"}),
    <tconstruct:sword_blade>.withTag({Material: "osgloglas"}),
    <tconstruct:sword_blade>.withTag({Material: "osmiridium"}),
    <tconstruct:sword_blade>.withTag({Material: "lumium_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "signalum_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "platinum_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "enderium_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "mica"}),
    <tconstruct:sword_blade>.withTag({Material: "litherite"}),
    <tconstruct:sword_blade>.withTag({Material: "erodium"}),
    <tconstruct:sword_blade>.withTag({Material: "kyronite"}),
    <tconstruct:sword_blade>.withTag({Material: "pladium"}),
    <tconstruct:sword_blade>.withTag({Material: "ionite"}),
    <tconstruct:sword_blade>.withTag({Material: "aethium"}),
    <tconstruct:sword_blade>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "awakened_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "darkmatter"}),
    <tconstruct:sword_blade>.withTag({Material: "redmatter"}),
    <tconstruct:sword_blade>.withTag({Material: "emerald_plustic"}),
    <tconstruct:sword_blade>.withTag({Material: "wood"}),
    <tconstruct:large_sword_blade>.withTag({Material: "electrical_steel"}),
    <tconstruct:large_sword_blade>.withTag({Material: "energetic_alloy"}),
    <tconstruct:large_sword_blade>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:large_sword_blade>.withTag({Material: "redstone_alloy"}),
    <tconstruct:large_sword_blade>.withTag({Material: "conductive_iron"}),
    <tconstruct:large_sword_blade>.withTag({Material: "pulsating_iron"}),
    <tconstruct:large_sword_blade>.withTag({Material: "dark_steel"}),
    <tconstruct:large_sword_blade>.withTag({Material: "soularium"}),
    <tconstruct:large_sword_blade>.withTag({Material: "end_steel"}),
    <tconstruct:large_sword_blade>.withTag({Material: "construction_alloy"}),
    <tconstruct:large_sword_blade>.withTag({Material: "stone"}),
    <tconstruct:large_sword_blade>.withTag({Material: "flint"}),
    <tconstruct:large_sword_blade>.withTag({Material: "cactus"}),
    <tconstruct:large_sword_blade>.withTag({Material: "bone"}),
    <tconstruct:large_sword_blade>.withTag({Material: "obsidian"}),
    <tconstruct:large_sword_blade>.withTag({Material: "prismarine"}),
    <tconstruct:large_sword_blade>.withTag({Material: "endstone"}),
    <tconstruct:large_sword_blade>.withTag({Material: "paper"}),
    <tconstruct:large_sword_blade>.withTag({Material: "sponge"}),
    <tconstruct:large_sword_blade>.withTag({Material: "firewood"}),
    <tconstruct:large_sword_blade>.withTag({Material: "iron"}),
    <tconstruct:large_sword_blade>.withTag({Material: "pigiron"}),
    <tconstruct:large_sword_blade>.withTag({Material: "knightslime"}),
    <tconstruct:large_sword_blade>.withTag({Material: "slime"}),
    <tconstruct:large_sword_blade>.withTag({Material: "blueslime"}),
    <tconstruct:large_sword_blade>.withTag({Material: "magmaslime"}),
    <tconstruct:large_sword_blade>.withTag({Material: "netherrack"}),
    <tconstruct:large_sword_blade>.withTag({Material: "cobalt"}),
    <tconstruct:large_sword_blade>.withTag({Material: "ardite"}),
    <tconstruct:large_sword_blade>.withTag({Material: "manyullyn"}),
    <tconstruct:large_sword_blade>.withTag({Material: "copper"}),
    <tconstruct:large_sword_blade>.withTag({Material: "bronze"}),
    <tconstruct:large_sword_blade>.withTag({Material: "lead"}),
    <tconstruct:large_sword_blade>.withTag({Material: "silver"}),
    <tconstruct:large_sword_blade>.withTag({Material: "electrum"}),
    <tconstruct:large_sword_blade>.withTag({Material: "steel"}),
    <tconstruct:large_sword_blade>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:large_sword_blade>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:large_sword_blade>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:large_sword_blade>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:large_sword_blade>.withTag({Material: "boron"}),
    <tconstruct:large_sword_blade>.withTag({Material: "tough"}),
    <tconstruct:large_sword_blade>.withTag({Material: "hard_carbon"}),
    <tconstruct:large_sword_blade>.withTag({Material: "boron_nitride"}),
    <tconstruct:large_sword_blade>.withTag({Material: "thorium"}),
    <tconstruct:large_sword_blade>.withTag({Material: "uranium"}),
    <tconstruct:large_sword_blade>.withTag({Material: "magnesium"}),
    <tconstruct:large_sword_blade>.withTag({Material: "chocolate"}),
    <tconstruct:large_sword_blade>.withTag({Material: "treatedwood"}),
    <tconstruct:large_sword_blade>.withTag({Material: "constantan"}),
    <tconstruct:large_sword_blade>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:large_sword_blade>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:large_sword_blade>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:large_sword_blade>.withTag({Material: "alumite"}),
    <tconstruct:large_sword_blade>.withTag({Material: "nickel"}),
    <tconstruct:large_sword_blade>.withTag({Material: "invar"}),
    <tconstruct:large_sword_blade>.withTag({Material: "iridium"}),
    <tconstruct:large_sword_blade>.withTag({Material: "sapphire"}),
    <tconstruct:large_sword_blade>.withTag({Material: "ruby"}),
 


];
for item in tcstage {
    mods.recipestages.Recipes.setRecipeStage("bettertools", item);
    mods.ItemStages.addItemStage("bettertools", item);
}

