import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;


val tcstage1 as IItemStack[] = [
    <tconstruct:tough_binding>.withTag({Material: "sapphire"}),
    <tconstruct:tough_binding>.withTag({Material: "ruby"}),
    <tconstruct:tough_binding>.withTag({Material: "peridot"}),
    <tconstruct:tough_binding>.withTag({Material: "osmium"}),
    <tconstruct:tough_binding>.withTag({Material: "refinedobsidian"}),
    <tconstruct:tough_binding>.withTag({Material: "refinedglowstone"}),
    <tconstruct:tough_binding>.withTag({Material: "osgloglas"}),
    <tconstruct:tough_binding>.withTag({Material: "osmiridium"}),
    <tconstruct:tough_binding>.withTag({Material: "lumium_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "signalum_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "platinum_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "enderium_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "mica"}),
    <tconstruct:tough_binding>.withTag({Material: "litherite"}),
    <tconstruct:tough_binding>.withTag({Material: "erodium"}),
    <tconstruct:tough_binding>.withTag({Material: "kyronite"}),
    <tconstruct:tough_binding>.withTag({Material: "pladium"}),
    <tconstruct:tough_binding>.withTag({Material: "ionite"}),
    <tconstruct:tough_binding>.withTag({Material: "aethium"}),
    <tconstruct:tough_binding>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "awakened_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "darkmatter"}),
    <tconstruct:tough_binding>.withTag({Material: "redmatter"}),
    <tconstruct:tough_binding>.withTag({Material: "emerald_plustic"}),
    <tconstruct:tough_binding>.withTag({Material: "wood"}),
    <tconstruct:wide_guard>.withTag({Material: "electrical_steel"}),
    <tconstruct:wide_guard>.withTag({Material: "energetic_alloy"}),
    <tconstruct:wide_guard>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:wide_guard>.withTag({Material: "obsidian"}),
    <tconstruct:wide_guard>.withTag({Material: "redstone_alloy"}),
    <tconstruct:wide_guard>.withTag({Material: "conductive_iron"}),
    <tconstruct:wide_guard>.withTag({Material: "pulsating_iron"}),
    <tconstruct:wide_guard>.withTag({Material: "dark_steel"}),
    <tconstruct:wide_guard>.withTag({Material: "soularium"}),
    <tconstruct:wide_guard>.withTag({Material: "end_steel"}),
    <tconstruct:wide_guard>.withTag({Material: "construction_alloy"}),
    <tconstruct:wide_guard>.withTag({Material: "stone"}),
    <tconstruct:wide_guard>.withTag({Material: "flint"}),
    <tconstruct:wide_guard>.withTag({Material: "cactus"}),
    <tconstruct:wide_guard>.withTag({Material: "bone"}),
    <tconstruct:wide_guard>.withTag({Material: "prismarine"}),
    <tconstruct:wide_guard>.withTag({Material: "endstone"}),
    <tconstruct:wide_guard>.withTag({Material: "paper"}),
    <tconstruct:wide_guard>.withTag({Material: "sponge"}),
    <tconstruct:wide_guard>.withTag({Material: "firewood"}),
    <tconstruct:wide_guard>.withTag({Material: "iron"}),
    <tconstruct:wide_guard>.withTag({Material: "pigiron"}),
    <tconstruct:wide_guard>.withTag({Material: "knightslime"}),
    <tconstruct:wide_guard>.withTag({Material: "slime"}),
    <tconstruct:wide_guard>.withTag({Material: "blueslime"}),
    <tconstruct:wide_guard>.withTag({Material: "magmaslime"}),
    <tconstruct:wide_guard>.withTag({Material: "netherrack"}),
    <tconstruct:wide_guard>.withTag({Material: "cobalt"}),
    <tconstruct:wide_guard>.withTag({Material: "ardite"}),
    <tconstruct:wide_guard>.withTag({Material: "manyullyn"}),
    <tconstruct:wide_guard>.withTag({Material: "copper"}),
    <tconstruct:wide_guard>.withTag({Material: "bronze"}),
    <tconstruct:wide_guard>.withTag({Material: "lead"}),
    <tconstruct:wide_guard>.withTag({Material: "silver"}),
    <tconstruct:wide_guard>.withTag({Material: "electrum"}),
    <tconstruct:wide_guard>.withTag({Material: "steel"}),
    <tconstruct:wide_guard>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:wide_guard>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:wide_guard>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:wide_guard>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:wide_guard>.withTag({Material: "boron"}),
    <tconstruct:wide_guard>.withTag({Material: "tough"}),
    <tconstruct:wide_guard>.withTag({Material: "hard_carbon"}),
    <tconstruct:wide_guard>.withTag({Material: "boron_nitride"}),
    <tconstruct:wide_guard>.withTag({Material: "thorium"}),
    <tconstruct:wide_guard>.withTag({Material: "uranium"}),
    <tconstruct:wide_guard>.withTag({Material: "magnesium"}),
    <tconstruct:wide_guard>.withTag({Material: "chocolate"}),
    <tconstruct:wide_guard>.withTag({Material: "treatedwood"}),
    <tconstruct:wide_guard>.withTag({Material: "constantan"}),
    <tconstruct:wide_guard>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:wide_guard>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:wide_guard>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:wide_guard>.withTag({Material: "alumite"}),
    <tconstruct:wide_guard>.withTag({Material: "nickel"}),
    <tconstruct:wide_guard>.withTag({Material: "invar"}),
    <tconstruct:wide_guard>.withTag({Material: "iridium"}),
    <tconstruct:wide_guard>.withTag({Material: "sapphire"}),
    <tconstruct:wide_guard>.withTag({Material: "ruby"}),
    <tconstruct:wide_guard>.withTag({Material: "peridot"}),
    <tconstruct:wide_guard>.withTag({Material: "osmium"}),
    <tconstruct:wide_guard>.withTag({Material: "refinedobsidian"}),
    <tconstruct:wide_guard>.withTag({Material: "refinedglowstone"}),
    <tconstruct:wide_guard>.withTag({Material: "osgloglas"}),
    <tconstruct:wide_guard>.withTag({Material: "osmiridium"}),
    <tconstruct:wide_guard>.withTag({Material: "lumium_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "signalum_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "platinum_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "enderium_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "mica"}),
    <tconstruct:wide_guard>.withTag({Material: "litherite"}),
    <tconstruct:wide_guard>.withTag({Material: "erodium"}),
    <tconstruct:wide_guard>.withTag({Material: "kyronite"}),
    <tconstruct:wide_guard>.withTag({Material: "pladium"}),
    <tconstruct:wide_guard>.withTag({Material: "ionite"}),
    <tconstruct:wide_guard>.withTag({Material: "aethium"}),
    <tconstruct:wide_guard>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "awakened_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "darkmatter"}),
    <tconstruct:wide_guard>.withTag({Material: "redmatter"}),
    <tconstruct:wide_guard>.withTag({Material: "emerald_plustic"}),
    <tconstruct:wide_guard>.withTag({Material: "wood"}),
    <tconstruct:hand_guard>.withTag({Material: "electrical_steel"}),
    <tconstruct:hand_guard>.withTag({Material: "energetic_alloy"}),
    <tconstruct:hand_guard>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:hand_guard>.withTag({Material: "redstone_alloy"}),
    <tconstruct:hand_guard>.withTag({Material: "conductive_iron"}),
    <tconstruct:hand_guard>.withTag({Material: "pulsating_iron"}),
    <tconstruct:hand_guard>.withTag({Material: "dark_steel"}),
    <tconstruct:hand_guard>.withTag({Material: "soularium"}),
    <tconstruct:hand_guard>.withTag({Material: "end_steel"}),
    <tconstruct:hand_guard>.withTag({Material: "construction_alloy"}),
    <tconstruct:hand_guard>.withTag({Material: "stone"}),
    <tconstruct:hand_guard>.withTag({Material: "flint"}),
    <tconstruct:hand_guard>.withTag({Material: "cactus"}),
    <tconstruct:hand_guard>.withTag({Material: "bone"}),
    <tconstruct:hand_guard>.withTag({Material: "obsidian"}),
    <tconstruct:hand_guard>.withTag({Material: "prismarine"}),
    <tconstruct:hand_guard>.withTag({Material: "endstone"}),
    <tconstruct:hand_guard>.withTag({Material: "paper"}),
    <tconstruct:hand_guard>.withTag({Material: "sponge"}),
    <tconstruct:hand_guard>.withTag({Material: "firewood"}),
    <tconstruct:hand_guard>.withTag({Material: "iron"}),
    <tconstruct:hand_guard>.withTag({Material: "pigiron"}),
    <tconstruct:hand_guard>.withTag({Material: "knightslime"}),
    <tconstruct:hand_guard>.withTag({Material: "slime"}),
    <tconstruct:hand_guard>.withTag({Material: "blueslime"}),
    <tconstruct:hand_guard>.withTag({Material: "magmaslime"}),
    <tconstruct:hand_guard>.withTag({Material: "netherrack"}),
    <tconstruct:hand_guard>.withTag({Material: "cobalt"}),
    <tconstruct:hand_guard>.withTag({Material: "ardite"}),
    <tconstruct:hand_guard>.withTag({Material: "manyullyn"}),
    <tconstruct:hand_guard>.withTag({Material: "copper"}),
    <tconstruct:hand_guard>.withTag({Material: "bronze"}),
    <tconstruct:hand_guard>.withTag({Material: "lead"}),
    <tconstruct:hand_guard>.withTag({Material: "silver"}),
    <tconstruct:hand_guard>.withTag({Material: "electrum"}),
    <tconstruct:hand_guard>.withTag({Material: "steel"}),
    <tconstruct:hand_guard>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:hand_guard>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:hand_guard>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:hand_guard>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:hand_guard>.withTag({Material: "boron"}),
    <tconstruct:hand_guard>.withTag({Material: "tough"}),
    <tconstruct:hand_guard>.withTag({Material: "hard_carbon"}),
    <tconstruct:hand_guard>.withTag({Material: "boron_nitride"}),
    <tconstruct:hand_guard>.withTag({Material: "thorium"}),
    <tconstruct:hand_guard>.withTag({Material: "uranium"}),
    <tconstruct:hand_guard>.withTag({Material: "magnesium"}),
    <tconstruct:hand_guard>.withTag({Material: "chocolate"}),
    <tconstruct:hand_guard>.withTag({Material: "treatedwood"}),
    <tconstruct:hand_guard>.withTag({Material: "constantan"}),
    <tconstruct:hand_guard>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:hand_guard>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:hand_guard>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:hand_guard>.withTag({Material: "alumite"}),
    <tconstruct:hand_guard>.withTag({Material: "nickel"}),
    <tconstruct:hand_guard>.withTag({Material: "invar"}),
    <tconstruct:hand_guard>.withTag({Material: "iridium"}),
    <tconstruct:hand_guard>.withTag({Material: "sapphire"}),
    <tconstruct:hand_guard>.withTag({Material: "ruby"}),
    <tconstruct:hand_guard>.withTag({Material: "peridot"}),
    <tconstruct:hand_guard>.withTag({Material: "osmium"}),
    <tconstruct:hand_guard>.withTag({Material: "refinedobsidian"}),
    <tconstruct:hand_guard>.withTag({Material: "refinedglowstone"}),
    <tconstruct:hand_guard>.withTag({Material: "osgloglas"}),
    <tconstruct:hand_guard>.withTag({Material: "osmiridium"}),
    <tconstruct:hand_guard>.withTag({Material: "lumium_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "signalum_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "platinum_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "enderium_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "mica"}),
    <tconstruct:hand_guard>.withTag({Material: "litherite"}),
    <tconstruct:hand_guard>.withTag({Material: "erodium"}),
    <tconstruct:hand_guard>.withTag({Material: "kyronite"}),
    <tconstruct:hand_guard>.withTag({Material: "pladium"}),
    <tconstruct:hand_guard>.withTag({Material: "ionite"}),
    <tconstruct:hand_guard>.withTag({Material: "aethium"}),
    <tconstruct:hand_guard>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "awakened_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "darkmatter"}),
    <tconstruct:hand_guard>.withTag({Material: "redmatter"}),
    <tconstruct:hand_guard>.withTag({Material: "emerald_plustic"}),
    <tconstruct:hand_guard>.withTag({Material: "wood"}),
    <tconstruct:cross_guard>.withTag({Material: "electrical_steel"}),
    <tconstruct:cross_guard>.withTag({Material: "energetic_alloy"}),
    <tconstruct:cross_guard>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:cross_guard>.withTag({Material: "redstone_alloy"}),
    <tconstruct:cross_guard>.withTag({Material: "conductive_iron"}),
    <tconstruct:cross_guard>.withTag({Material: "pulsating_iron"}),
    <tconstruct:cross_guard>.withTag({Material: "dark_steel"}),
    <tconstruct:cross_guard>.withTag({Material: "soularium"}),
    <tconstruct:cross_guard>.withTag({Material: "end_steel"}),
    <tconstruct:cross_guard>.withTag({Material: "construction_alloy"}),
    <tconstruct:cross_guard>.withTag({Material: "stone"}),
    <tconstruct:cross_guard>.withTag({Material: "flint"}),
    <tconstruct:cross_guard>.withTag({Material: "cactus"}),
    <tconstruct:cross_guard>.withTag({Material: "bone"}),
    <tconstruct:cross_guard>.withTag({Material: "obsidian"}),
    <tconstruct:cross_guard>.withTag({Material: "prismarine"}),
    <tconstruct:cross_guard>.withTag({Material: "endstone"}),
    <tconstruct:cross_guard>.withTag({Material: "paper"}),
    <tconstruct:cross_guard>.withTag({Material: "sponge"}),
    <tconstruct:cross_guard>.withTag({Material: "firewood"}),
    <tconstruct:cross_guard>.withTag({Material: "iron"}),
    <tconstruct:cross_guard>.withTag({Material: "pigiron"}),
    <tconstruct:cross_guard>.withTag({Material: "knightslime"}),
    <tconstruct:cross_guard>.withTag({Material: "slime"}),
    <tconstruct:cross_guard>.withTag({Material: "blueslime"}),
    <tconstruct:cross_guard>.withTag({Material: "magmaslime"}),
    <tconstruct:cross_guard>.withTag({Material: "netherrack"}),
    <tconstruct:cross_guard>.withTag({Material: "cobalt"}),
    <tconstruct:cross_guard>.withTag({Material: "ardite"}),
    <tconstruct:cross_guard>.withTag({Material: "manyullyn"}),
    <tconstruct:cross_guard>.withTag({Material: "copper"}),
    <tconstruct:cross_guard>.withTag({Material: "bronze"}),
    <tconstruct:cross_guard>.withTag({Material: "lead"}),
    <tconstruct:cross_guard>.withTag({Material: "silver"}),
    <tconstruct:cross_guard>.withTag({Material: "electrum"}),
    <tconstruct:cross_guard>.withTag({Material: "steel"}),
    <tconstruct:cross_guard>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:cross_guard>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:cross_guard>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:cross_guard>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:cross_guard>.withTag({Material: "boron"}),
    <tconstruct:cross_guard>.withTag({Material: "tough"}),
    <tconstruct:cross_guard>.withTag({Material: "hard_carbon"}),
    <tconstruct:cross_guard>.withTag({Material: "boron_nitride"}),
    <tconstruct:cross_guard>.withTag({Material: "thorium"}),
    <tconstruct:cross_guard>.withTag({Material: "uranium"}),
    <tconstruct:cross_guard>.withTag({Material: "magnesium"}),
    <tconstruct:cross_guard>.withTag({Material: "chocolate"}),
    <tconstruct:cross_guard>.withTag({Material: "treatedwood"}),
    <tconstruct:cross_guard>.withTag({Material: "constantan"}),
    <tconstruct:cross_guard>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:cross_guard>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:cross_guard>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:cross_guard>.withTag({Material: "alumite"}),
    <tconstruct:cross_guard>.withTag({Material: "nickel"}),
    <tconstruct:cross_guard>.withTag({Material: "invar"}),
    <tconstruct:cross_guard>.withTag({Material: "iridium"}),
    <tconstruct:cross_guard>.withTag({Material: "sapphire"}),
    <tconstruct:cross_guard>.withTag({Material: "ruby"}),
    <tconstruct:cross_guard>.withTag({Material: "peridot"}),
    <tconstruct:cross_guard>.withTag({Material: "osmium"}),
    <tconstruct:cross_guard>.withTag({Material: "refinedobsidian"}),
    <tconstruct:cross_guard>.withTag({Material: "refinedglowstone"}),
    <tconstruct:cross_guard>.withTag({Material: "osgloglas"}),
    <tconstruct:cross_guard>.withTag({Material: "osmiridium"}),
    <tconstruct:cross_guard>.withTag({Material: "lumium_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "signalum_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "platinum_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "enderium_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "mica"}),
    <tconstruct:cross_guard>.withTag({Material: "litherite"}),
    <tconstruct:cross_guard>.withTag({Material: "erodium"}),
    <tconstruct:cross_guard>.withTag({Material: "kyronite"}),
    <tconstruct:cross_guard>.withTag({Material: "pladium"}),
    <tconstruct:cross_guard>.withTag({Material: "ionite"}),
    <tconstruct:cross_guard>.withTag({Material: "aethium"}),
    <tconstruct:cross_guard>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "awakened_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "darkmatter"}),
    <tconstruct:cross_guard>.withTag({Material: "redmatter"}),
    <tconstruct:cross_guard>.withTag({Material: "emerald_plustic"}),
    <tconstruct:cross_guard>.withTag({Material: "wood"}),
    <tconstruct:large_plate>.withTag({Material: "electrical_steel"}),
    <tconstruct:large_plate>.withTag({Material: "energetic_alloy"}),
    <tconstruct:large_plate>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:large_plate>.withTag({Material: "redstone_alloy"}),
    <tconstruct:large_plate>.withTag({Material: "conductive_iron"}),
    <tconstruct:large_plate>.withTag({Material: "pulsating_iron"}),
    <tconstruct:large_plate>.withTag({Material: "dark_steel"}),
    <tconstruct:large_plate>.withTag({Material: "soularium"}),
    <tconstruct:large_plate>.withTag({Material: "end_steel"}),
    <tconstruct:large_plate>.withTag({Material: "construction_alloy"}),
    <tconstruct:large_plate>.withTag({Material: "stone"}),
    <tconstruct:large_plate>.withTag({Material: "flint"}),
    <tconstruct:large_plate>.withTag({Material: "cactus"}),
    <tconstruct:large_plate>.withTag({Material: "bone"}),
    <tconstruct:large_plate>.withTag({Material: "obsidian"}),
    <tconstruct:large_plate>.withTag({Material: "prismarine"}),
    <tconstruct:large_plate>.withTag({Material: "endstone"}),
    <tconstruct:large_plate>.withTag({Material: "paper"}),
    <tconstruct:large_plate>.withTag({Material: "sponge"}),
    <tconstruct:large_plate>.withTag({Material: "firewood"}),
    <tconstruct:large_plate>.withTag({Material: "iron"}),
    <tconstruct:large_plate>.withTag({Material: "pigiron"}),
    <tconstruct:large_plate>.withTag({Material: "knightslime"}),
    <tconstruct:large_plate>.withTag({Material: "slime"}),
    <tconstruct:large_plate>.withTag({Material: "blueslime"}),
    <tconstruct:large_plate>.withTag({Material: "magmaslime"}),
    <tconstruct:large_plate>.withTag({Material: "netherrack"}),
    <tconstruct:large_plate>.withTag({Material: "cobalt"}),
    <tconstruct:large_plate>.withTag({Material: "ardite"}),
    <tconstruct:large_plate>.withTag({Material: "manyullyn"}),
    <tconstruct:large_plate>.withTag({Material: "bronze"}),
    <tconstruct:large_plate>.withTag({Material: "lead"}),
    <tconstruct:large_plate>.withTag({Material: "silver"}),
    <tconstruct:large_plate>.withTag({Material: "electrum"}),
    <tconstruct:large_plate>.withTag({Material: "steel"}),
    <tconstruct:large_plate>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:large_plate>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:large_plate>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:large_plate>.withTag({Material: "copper"}),
    <tconstruct:large_plate>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:large_plate>.withTag({Material: "boron"}),
    <tconstruct:large_plate>.withTag({Material: "tough"}),
    <tconstruct:large_plate>.withTag({Material: "hard_carbon"}),
    <tconstruct:large_plate>.withTag({Material: "boron_nitride"}),
    <tconstruct:large_plate>.withTag({Material: "thorium"}),
    <tconstruct:large_plate>.withTag({Material: "uranium"}),
    <tconstruct:large_plate>.withTag({Material: "magnesium"}),
    <tconstruct:large_plate>.withTag({Material: "chocolate"}),
    <tconstruct:large_plate>.withTag({Material: "treatedwood"}),
    <tconstruct:large_plate>.withTag({Material: "constantan"}),
    <tconstruct:large_plate>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:large_plate>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:large_plate>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:large_plate>.withTag({Material: "alumite"}),
    <tconstruct:large_plate>.withTag({Material: "nickel"}),
    <tconstruct:large_plate>.withTag({Material: "invar"}),
    <tconstruct:large_plate>.withTag({Material: "iridium"}),
    <tconstruct:large_plate>.withTag({Material: "sapphire"}),
    <tconstruct:large_plate>.withTag({Material: "ruby"}),
    <tconstruct:large_plate>.withTag({Material: "peridot"}),
    <tconstruct:large_plate>.withTag({Material: "osmium"}),
    <tconstruct:large_plate>.withTag({Material: "refinedobsidian"}),
    <tconstruct:large_plate>.withTag({Material: "refinedglowstone"}),
    <tconstruct:large_plate>.withTag({Material: "osgloglas"}),
    <tconstruct:large_plate>.withTag({Material: "osmiridium"}),
    <tconstruct:large_plate>.withTag({Material: "lumium_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "signalum_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "platinum_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "enderium_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "mica"}),
    <tconstruct:large_plate>.withTag({Material: "litherite"}),
    <tconstruct:large_plate>.withTag({Material: "erodium"}),
    <tconstruct:large_plate>.withTag({Material: "kyronite"}),
    <tconstruct:large_plate>.withTag({Material: "pladium"}),
    <tconstruct:large_plate>.withTag({Material: "ionite"}),
    <tconstruct:large_plate>.withTag({Material: "aethium"}),
    <tconstruct:large_plate>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "awakened_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "darkmatter"}),
    <tconstruct:large_plate>.withTag({Material: "redmatter"}),
    <tconstruct:large_plate>.withTag({Material: "emerald_plustic"}),
    <tconstruct:large_plate>.withTag({Material: "wood"}),
    <tconstruct:knife_blade>.withTag({Material: "electrical_steel"}),
    <tconstruct:knife_blade>.withTag({Material: "energetic_alloy"}),
    <tconstruct:knife_blade>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:knife_blade>.withTag({Material: "redstone_alloy"}),
    <tconstruct:knife_blade>.withTag({Material: "conductive_iron"}),
    <tconstruct:knife_blade>.withTag({Material: "pulsating_iron"}),
    <tconstruct:knife_blade>.withTag({Material: "dark_steel"}),
    <tconstruct:knife_blade>.withTag({Material: "soularium"}),
    <tconstruct:knife_blade>.withTag({Material: "end_steel"}),
    <tconstruct:knife_blade>.withTag({Material: "construction_alloy"}),
    <tconstruct:knife_blade>.withTag({Material: "stone"}),
    <tconstruct:knife_blade>.withTag({Material: "flint"}),
    <tconstruct:knife_blade>.withTag({Material: "cactus"}),
    <tconstruct:knife_blade>.withTag({Material: "bone"}),
    <tconstruct:knife_blade>.withTag({Material: "obsidian"}),
    <tconstruct:knife_blade>.withTag({Material: "prismarine"}),
    <tconstruct:knife_blade>.withTag({Material: "endstone"}),
    <tconstruct:knife_blade>.withTag({Material: "paper"}),
    <tconstruct:knife_blade>.withTag({Material: "sponge"}),
    <tconstruct:knife_blade>.withTag({Material: "firewood"}),
    <tconstruct:knife_blade>.withTag({Material: "iron"}),
    <tconstruct:knife_blade>.withTag({Material: "pigiron"}),
    <tconstruct:knife_blade>.withTag({Material: "knightslime"}),
    <tconstruct:knife_blade>.withTag({Material: "slime"}),
    <tconstruct:knife_blade>.withTag({Material: "blueslime"}),
    <tconstruct:knife_blade>.withTag({Material: "magmaslime"}),
    <tconstruct:knife_blade>.withTag({Material: "netherrack"}),
    <tconstruct:knife_blade>.withTag({Material: "cobalt"}),
    <tconstruct:knife_blade>.withTag({Material: "ardite"}),
    <tconstruct:knife_blade>.withTag({Material: "manyullyn"}),
    <tconstruct:knife_blade>.withTag({Material: "copper"}),
    <tconstruct:knife_blade>.withTag({Material: "bronze"}),
    <tconstruct:knife_blade>.withTag({Material: "lead"}),
    <tconstruct:knife_blade>.withTag({Material: "silver"}),
    <tconstruct:knife_blade>.withTag({Material: "electrum"}),
    <tconstruct:knife_blade>.withTag({Material: "steel"}),
    <tconstruct:knife_blade>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:knife_blade>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:knife_blade>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:knife_blade>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:knife_blade>.withTag({Material: "boron"}),
    <tconstruct:knife_blade>.withTag({Material: "tough"}),
    <tconstruct:knife_blade>.withTag({Material: "hard_carbon"}),
    <tconstruct:knife_blade>.withTag({Material: "boron_nitride"}),
    <tconstruct:knife_blade>.withTag({Material: "thorium"}),
    <tconstruct:knife_blade>.withTag({Material: "uranium"}),
    <tconstruct:knife_blade>.withTag({Material: "magnesium"}),
    <tconstruct:knife_blade>.withTag({Material: "chocolate"}),
    <tconstruct:knife_blade>.withTag({Material: "treatedwood"}),
    <tconstruct:knife_blade>.withTag({Material: "constantan"}),
    <tconstruct:knife_blade>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:knife_blade>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:knife_blade>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:knife_blade>.withTag({Material: "alumite"}),
    <tconstruct:knife_blade>.withTag({Material: "nickel"}),
    <tconstruct:knife_blade>.withTag({Material: "invar"}),
    <tconstruct:knife_blade>.withTag({Material: "iridium"}),
    <tconstruct:knife_blade>.withTag({Material: "sapphire"}),
    <tconstruct:knife_blade>.withTag({Material: "ruby"}),
    <tconstruct:knife_blade>.withTag({Material: "peridot"}),
    <tconstruct:knife_blade>.withTag({Material: "osmium"}),
    <tconstruct:knife_blade>.withTag({Material: "refinedobsidian"}),
    <tconstruct:knife_blade>.withTag({Material: "refinedglowstone"}),
    <tconstruct:knife_blade>.withTag({Material: "osgloglas"}),
    <tconstruct:knife_blade>.withTag({Material: "osmiridium"}),
    <tconstruct:knife_blade>.withTag({Material: "lumium_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "signalum_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "platinum_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "enderium_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "mica"}),
    <tconstruct:knife_blade>.withTag({Material: "litherite"}),
    <tconstruct:knife_blade>.withTag({Material: "erodium"}),
    <tconstruct:knife_blade>.withTag({Material: "kyronite"}),
    <tconstruct:knife_blade>.withTag({Material: "pladium"}),
    <tconstruct:knife_blade>.withTag({Material: "ionite"}),
    <tconstruct:knife_blade>.withTag({Material: "aethium"}),
    <tconstruct:knife_blade>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "awakened_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "darkmatter"}),
    <tconstruct:knife_blade>.withTag({Material: "redmatter"}),
    <tconstruct:knife_blade>.withTag({Material: "emerald_plustic"}),
    <tconstruct:knife_blade>.withTag({Material: "wood"}),
    <tconstruct:bow_limb>.withTag({Material: "electrical_steel"}),
    <tconstruct:bow_limb>.withTag({Material: "energetic_alloy"}),
    <tconstruct:bow_limb>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:bow_limb>.withTag({Material: "redstone_alloy"}),
    <tconstruct:bow_limb>.withTag({Material: "conductive_iron"}),
    <tconstruct:bow_limb>.withTag({Material: "pulsating_iron"}),
    <tconstruct:bow_limb>.withTag({Material: "dark_steel"}),
    <tconstruct:bow_limb>.withTag({Material: "soularium"}),
    <tconstruct:bow_limb>.withTag({Material: "end_steel"}),
    <tconstruct:bow_limb>.withTag({Material: "construction_alloy"}),
    <tconstruct:bow_limb>.withTag({Material: "stone"}),
    <tconstruct:bow_limb>.withTag({Material: "flint"}),
    <tconstruct:bow_limb>.withTag({Material: "cactus"}),
    <tconstruct:bow_limb>.withTag({Material: "bone"}),
    <tconstruct:bow_limb>.withTag({Material: "obsidian"}),
    <tconstruct:bow_limb>.withTag({Material: "prismarine"}),
    <tconstruct:bow_limb>.withTag({Material: "endstone"}),
    <tconstruct:bow_limb>.withTag({Material: "paper"}),
    <tconstruct:bow_limb>.withTag({Material: "sponge"}),
    <tconstruct:bow_limb>.withTag({Material: "firewood"}),
    <tconstruct:bow_limb>.withTag({Material: "iron"}),
    <tconstruct:bow_limb>.withTag({Material: "pigiron"}),
    <tconstruct:bow_limb>.withTag({Material: "knightslime"}),
    <tconstruct:bow_limb>.withTag({Material: "slime"}),
    <tconstruct:bow_limb>.withTag({Material: "blueslime"}),
    <tconstruct:bow_limb>.withTag({Material: "magmaslime"}),
    <tconstruct:bow_limb>.withTag({Material: "netherrack"}),
    <tconstruct:bow_limb>.withTag({Material: "cobalt"}),
    <tconstruct:bow_limb>.withTag({Material: "ardite"}),
    <tconstruct:bow_limb>.withTag({Material: "manyullyn"}),
    <tconstruct:bow_limb>.withTag({Material: "copper"}),
    <tconstruct:bow_limb>.withTag({Material: "bronze"}),
    <tconstruct:bow_limb>.withTag({Material: "lead"}),
    <tconstruct:bow_limb>.withTag({Material: "silver"}),
    <tconstruct:bow_limb>.withTag({Material: "electrum"}),
    <tconstruct:bow_limb>.withTag({Material: "steel"}),
    <tconstruct:bow_limb>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:bow_limb>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:bow_limb>.withTag({Material: "boron"}),
    <tconstruct:bow_limb>.withTag({Material: "tough"}),
    <tconstruct:bow_limb>.withTag({Material: "hard_carbon"}),
    <tconstruct:bow_limb>.withTag({Material: "boron_nitride"}),
    <tconstruct:bow_limb>.withTag({Material: "thorium"}),
    <tconstruct:bow_limb>.withTag({Material: "uranium"}),
    <tconstruct:bow_limb>.withTag({Material: "magnesium"}),
    <tconstruct:bow_limb>.withTag({Material: "chocolate"}),
    <tconstruct:bow_limb>.withTag({Material: "treatedwood"}),
    <tconstruct:bow_limb>.withTag({Material: "constantan"}),
    <tconstruct:bow_limb>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:bow_limb>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:bow_limb>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:bow_limb>.withTag({Material: "alumite"}),
    <tconstruct:bow_limb>.withTag({Material: "nickel"}),
    <tconstruct:bow_limb>.withTag({Material: "invar"}),
    <tconstruct:bow_limb>.withTag({Material: "iridium"}),
    <tconstruct:bow_limb>.withTag({Material: "sapphire"}),
    <tconstruct:bow_limb>.withTag({Material: "ruby"}),
    <tconstruct:bow_limb>.withTag({Material: "peridot"}),
    <tconstruct:bow_limb>.withTag({Material: "osmium"}),
    <tconstruct:bow_limb>.withTag({Material: "refinedobsidian"}),
    <tconstruct:bow_limb>.withTag({Material: "refinedglowstone"}),
    <tconstruct:bow_limb>.withTag({Material: "osgloglas"}),
    <tconstruct:bow_limb>.withTag({Material: "osmiridium"}),
    <tconstruct:bow_limb>.withTag({Material: "lumium_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "signalum_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "platinum_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "enderium_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "mica"}),
    <tconstruct:bow_limb>.withTag({Material: "litherite"}),
    <tconstruct:bow_limb>.withTag({Material: "erodium"}),
    <tconstruct:bow_limb>.withTag({Material: "kyronite"}),
    <tconstruct:bow_limb>.withTag({Material: "pladium"}),
    <tconstruct:bow_limb>.withTag({Material: "ionite"}),
    <tconstruct:bow_limb>.withTag({Material: "aethium"}),
    <tconstruct:bow_limb>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "awakened_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "darkmatter"}),
    <tconstruct:bow_limb>.withTag({Material: "redmatter"}),
    <tconstruct:bow_limb>.withTag({Material: "emerald_plustic"}),
    <tconstruct:bow_limb>.withTag({Material: "wood"}),
    <tconstruct:bow_string>.withTag({Material: "soularium"}),
    <tconstruct:bow_string>.withTag({Material: "string"}),
    <tconstruct:bow_string>.withTag({Material: "slimevine_blue"}),
    <tconstruct:bow_string>.withTag({Material: "slimevine_purple"}),
    <tconstruct:bow_string>.withTag({Material: "vine"}),
    <tconstruct:bow_string>.withTag({Material: "hemp"}),
    <tconstruct:arrow_head>.withTag({Material: "electrical_steel"}),
    <tconstruct:arrow_head>.withTag({Material: "energetic_alloy"}),
    <tconstruct:arrow_head>.withTag({Material: "vibrant_alloy"}),
    <tconstruct:arrow_head>.withTag({Material: "redstone_alloy"}),
    <tconstruct:arrow_head>.withTag({Material: "conductive_iron"}),
    <tconstruct:arrow_head>.withTag({Material: "pulsating_iron"}),
    <tconstruct:arrow_head>.withTag({Material: "dark_steel"}),
    <tconstruct:arrow_head>.withTag({Material: "soularium"}),
    <tconstruct:arrow_head>.withTag({Material: "end_steel"}),
    <tconstruct:arrow_head>.withTag({Material: "construction_alloy"}),
    <tconstruct:arrow_head>.withTag({Material: "stone"}),
    <tconstruct:arrow_head>.withTag({Material: "flint"}),
    <tconstruct:arrow_head>.withTag({Material: "cactus"}),
    <tconstruct:arrow_head>.withTag({Material: "bone"}),
    <tconstruct:arrow_head>.withTag({Material: "obsidian"}),
    <tconstruct:arrow_head>.withTag({Material: "prismarine"}),
    <tconstruct:arrow_head>.withTag({Material: "endstone"}),
    <tconstruct:arrow_head>.withTag({Material: "paper"}),
    <tconstruct:arrow_head>.withTag({Material: "sponge"}),
    <tconstruct:arrow_head>.withTag({Material: "firewood"}),
    <tconstruct:arrow_head>.withTag({Material: "iron"}),
    <tconstruct:arrow_head>.withTag({Material: "pigiron"}),
    <tconstruct:arrow_head>.withTag({Material: "knightslime"}),
    <tconstruct:arrow_head>.withTag({Material: "slime"}),
    <tconstruct:arrow_head>.withTag({Material: "blueslime"}),
    <tconstruct:arrow_head>.withTag({Material: "magmaslime"}),
    <tconstruct:arrow_head>.withTag({Material: "netherrack"}),
    <tconstruct:arrow_head>.withTag({Material: "cobalt"}),
    <tconstruct:arrow_head>.withTag({Material: "ardite"}),
    <tconstruct:arrow_head>.withTag({Material: "manyullyn"}),
    <tconstruct:arrow_head>.withTag({Material: "copper"}),
    <tconstruct:arrow_head>.withTag({Material: "bronze"}),
    <tconstruct:arrow_head>.withTag({Material: "lead"}),
    <tconstruct:arrow_head>.withTag({Material: "silver"}),
    <tconstruct:arrow_head>.withTag({Material: "electrum"}),
    <tconstruct:arrow_head>.withTag({Material: "steel"}),
    <tconstruct:arrow_head>.withTag({Material: "xu_magical_wood"}),
    <tconstruct:arrow_head>.withTag({Material: "xu_evil_metal"}),
    <tconstruct:arrow_head>.withTag({Material: "xu_enchanted_metal"}),
    <tconstruct:arrow_head>.withTag({Material: "xu_demonic_metal"}),
    <tconstruct:arrow_head>.withTag({Material: "boron"}),
    <tconstruct:arrow_head>.withTag({Material: "tough"}),
    <tconstruct:arrow_head>.withTag({Material: "hard_carbon"}),
    <tconstruct:arrow_head>.withTag({Material: "boron_nitride"}),
    <tconstruct:arrow_head>.withTag({Material: "thorium"}),
    <tconstruct:arrow_head>.withTag({Material: "uranium"}),
    <tconstruct:arrow_head>.withTag({Material: "magnesium"}),
    <tconstruct:arrow_head>.withTag({Material: "chocolate"}),
    <tconstruct:arrow_head>.withTag({Material: "treatedwood"}),
    <tconstruct:arrow_head>.withTag({Material: "constantan"}),
    <tconstruct:arrow_head>.withTag({Material: "integrationforegoing.plastic"}),
    <tconstruct:arrow_head>.withTag({Material: "integrationforegoing.pink_slime"}),
    <tconstruct:arrow_head>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <tconstruct:arrow_head>.withTag({Material: "alumite"}),
    <tconstruct:arrow_head>.withTag({Material: "nickel"}),
    <tconstruct:arrow_head>.withTag({Material: "invar"}),
    <tconstruct:arrow_head>.withTag({Material: "iridium"}),
    <tconstruct:arrow_head>.withTag({Material: "sapphire"}),
    <tconstruct:arrow_head>.withTag({Material: "ruby"}),
    <tconstruct:arrow_head>.withTag({Material: "peridot"}),
    <tconstruct:arrow_head>.withTag({Material: "osmium"}),
    <tconstruct:arrow_head>.withTag({Material: "refinedobsidian"}),
    <tconstruct:arrow_head>.withTag({Material: "refinedglowstone"}),
    <tconstruct:arrow_head>.withTag({Material: "osgloglas"}),
    <tconstruct:arrow_head>.withTag({Material: "osmiridium"}),
    <tconstruct:arrow_head>.withTag({Material: "lumium_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "signalum_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "platinum_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "enderium_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "blackquartz_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "void_actadd_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "enori_actadd_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "palis_actadd_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "restonia_actadd_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "emeradic_actadd_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "diamatine_actadd_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "infinity_avaritia_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "certusquartz_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "fluixcrystal_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "mica"}),
    <tconstruct:arrow_head>.withTag({Material: "litherite"}),
    <tconstruct:arrow_head>.withTag({Material: "erodium"}),
    <tconstruct:arrow_head>.withTag({Material: "kyronite"}),
    <tconstruct:arrow_head>.withTag({Material: "pladium"}),
    <tconstruct:arrow_head>.withTag({Material: "ionite"}),
    <tconstruct:arrow_head>.withTag({Material: "aethium"}),
    <tconstruct:arrow_head>.withTag({Material: "wyvern_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "awakened_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "chaotic_plustic"}),
    <tconstruct:fletching>.withTag({Material: "leaf"}),
    <tconstruct:fletching>.withTag({Material: "slimeleaf_purple"}),
    <tconstruct:fletching>.withTag({Material: "slimeleaf_orange"}),
    <tconstruct:fletching>.withTag({Material: "slimeleaf_blue"}),
    <tconstruct:fletching>.withTag({Material: "feather"}),
    <tconstruct:fletching>.withTag({Material: "invar"}),
    <tconstruct:fletching>.withTag({Material: "nickel"}),
    <tconstruct:arrow_shaft>.withTag({Material: "treatedwood"}),
    <tconstruct:arrow_shaft>.withTag({Material: "tnt"}),
    <tconstruct:arrow_shaft>.withTag({Material: "enderium_plustic"}),
    <tconstruct:arrow_shaft>.withTag({Material: "wood"}),
    <tconstruct:arrow_head>.withTag({Material: "redmatter"}),
    <tconstruct:arrow_head>.withTag({Material: "darkmatter"}),
    <tconstruct:arrow_head>.withTag({Material: "emerald_plustic"}),
    <tconstruct:arrow_head>.withTag({Material: "wood"}),
    <tconstruct:arrow_shaft>.withTag({Material: "bone"}),
    <tconstruct:arrow_shaft>.withTag({Material: "blaze"}),
    <tconstruct:arrow_shaft>.withTag({Material: "reed"}),
    <tconstruct:arrow_shaft>.withTag({Material: "ice"}),
    <tconstruct:arrow_shaft>.withTag({Material: "endrod"}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "minecraft:planks", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "minecraft:planks", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "minecraft:planks", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "minecraft:planks", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "minecraft:planks", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "extrautils2:ironwood_planks", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "extrautils2:ironwood_planks", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "techreborn:rubber_planks", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 6 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 7 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 8 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 9 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 10 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 11 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 12 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 13 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-oak", Count: 1 as byte, Damage: 14 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 6 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 7 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 8 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 9 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 10 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 11 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 12 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 13 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-spruce", Count: 1 as byte, Damage: 14 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 6 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 7 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 8 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 9 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 10 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 11 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 12 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 13 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-birch", Count: 1 as byte, Damage: 14 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 6 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 7 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 8 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 9 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 10 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 11 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 12 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 13 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-jungle", Count: 1 as byte, Damage: 14 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 6 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 7 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 8 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 9 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 10 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 11 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 12 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 13 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-acacia", Count: 1 as byte, Damage: 14 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 6 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 7 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 8 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 9 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 10 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 11 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 12 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 13 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "chisel:planks-dark-oak", Count: 1 as byte, Damage: 14 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "quark:stained_planks", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "quark:vertical_planks", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:1>.withTag({textureBlock: {id: "quark:vertical_stained_planks", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:2>.withTag({textureBlock: {id: "minecraft:log", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:tooltables:2>.withTag({textureBlock: {id: "minecraft:log", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:tooltables:2>.withTag({textureBlock: {id: "minecraft:log", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:tooltables:2>.withTag({textureBlock: {id: "minecraft:log2", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:2>.withTag({textureBlock: {id: "minecraft:log2", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:tooltables:2>.withTag({textureBlock: {id: "extrautils2:ironwood_log", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:tooltables:2>.withTag({textureBlock: {id: "extrautils2:ironwood_log", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:tooltables:2>.withTag({textureBlock: {id: "techreborn:rubber_log", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 6 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 7 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 8 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 9 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy_endergy", Count: 1 as byte, Damage: 6 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "tconstruct:metal", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "tconstruct:metal", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "tconstruct:metal", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "chisel:blockcobalt", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "tconstruct:metal", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "tconstruct:metal", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "minecraft:gold_block", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "techreborn:storage", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "techreborn:storage", Count: 1 as byte, Damage: 8 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "nuclearcraft:ingot_block", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "nuclearcraft:ingot_block", Count: 1 as byte, Damage: 3 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "immersiveengineering:storage", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "nuclearcraft:ingot_block", Count: 1 as byte, Damage: 7 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "plustic:alumiteblock", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 7 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "mekanism:basicblock", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "mekanism:basicblock", Count: 1 as byte, Damage: 2 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "mekanism:basicblock", Count: 1 as byte, Damage: 4 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "plustic:osgloglasblock", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "plustic:osmiridiumblock", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 6 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 5 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage", Count: 1 as byte, Damage: 6 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "thermalfoundation:storage_alloy", Count: 1 as byte, Damage: 7 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "avaritia:block_resource", Count: 1 as byte, Damage: 1 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "nuclearcraft:ingot_block", Count: 1 as byte, Damage: 9 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "nuclearcraft:ingot_block", Count: 1 as byte, Damage: 11 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "minecraft:glowstone", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:toolforge>.withTag({textureBlock: {id: "minecraft:redstone_block", Count: 1 as byte, Damage: 0 as short}}),
    <tconstruct:cast>.withTag({PartType: "plustic:battery_cell"}),
    <tconstruct:cast>.withTag({PartType: "plustic:laser_medium"}),
    <tconstruct:cast>.withTag({PartType: "plustic:pipe_piece"}),
    <tconstruct:clay_cast>.withTag({PartType: "plustic:battery_cell"}),
    <tconstruct:clay_cast>.withTag({PartType: "plustic:laser_medium"}),
    <tconstruct:clay_cast>.withTag({PartType: "plustic:pipe_piece"}),
    <plustic:alumitenugget>,
    <plustic:alumiteingot>,
    <plustic:alumiteblock>,
    <plustic:osgloglasnugget>,
    <plustic:osgloglasingot>,
    <plustic:osgloglasblock>,
    <plustic:osmiridiumnugget>,
    <plustic:osmiridiumingot>,
    <plustic:osmiridiumblock>,
    <plustic:pipe_piece>.withTag({Material: "electrical_steel"}),
    <plustic:pipe_piece>.withTag({Material: "energetic_alloy"}),
    <plustic:pipe_piece>.withTag({Material: "vibrant_alloy"}),
    <plustic:pipe_piece>.withTag({Material: "redstone_alloy"}),
    <plustic:pipe_piece>.withTag({Material: "conductive_iron"}),
    <plustic:pipe_piece>.withTag({Material: "pulsating_iron"}),
    <plustic:pipe_piece>.withTag({Material: "dark_steel"}),
    <plustic:pipe_piece>.withTag({Material: "soularium"}),
    <plustic:pipe_piece>.withTag({Material: "end_steel"}),
    <plustic:pipe_piece>.withTag({Material: "construction_alloy"}),
    <plustic:pipe_piece>.withTag({Material: "stone"}),
    <plustic:pipe_piece>.withTag({Material: "flint"}),
    <plustic:pipe_piece>.withTag({Material: "cactus"}),
    <plustic:pipe_piece>.withTag({Material: "bone"}),
    <plustic:pipe_piece>.withTag({Material: "obsidian"}),
    <plustic:pipe_piece>.withTag({Material: "prismarine"}),
    <plustic:pipe_piece>.withTag({Material: "endstone"}),
    <plustic:pipe_piece>.withTag({Material: "paper"}),
    <plustic:pipe_piece>.withTag({Material: "sponge"}),
    <plustic:pipe_piece>.withTag({Material: "firewood"}),
    <plustic:pipe_piece>.withTag({Material: "iron"}),
    <plustic:pipe_piece>.withTag({Material: "pigiron"}),
    <plustic:pipe_piece>.withTag({Material: "knightslime"}),
    <plustic:pipe_piece>.withTag({Material: "slime"}),
    <plustic:pipe_piece>.withTag({Material: "blueslime"}),
    <plustic:pipe_piece>.withTag({Material: "magmaslime"}),
    <plustic:pipe_piece>.withTag({Material: "netherrack"}),
    <plustic:pipe_piece>.withTag({Material: "cobalt"}),
    <plustic:pipe_piece>.withTag({Material: "ardite"}),
    <plustic:pipe_piece>.withTag({Material: "manyullyn"}),
    <plustic:pipe_piece>.withTag({Material: "copper"}),
    <plustic:pipe_piece>.withTag({Material: "bronze"}),
    <plustic:pipe_piece>.withTag({Material: "lead"}),
    <plustic:pipe_piece>.withTag({Material: "silver"}),
    <plustic:pipe_piece>.withTag({Material: "electrum"}),
    <plustic:pipe_piece>.withTag({Material: "steel"}),
    <plustic:pipe_piece>.withTag({Material: "xu_magical_wood"}),
    <plustic:pipe_piece>.withTag({Material: "xu_evil_metal"}),
    <plustic:pipe_piece>.withTag({Material: "xu_enchanted_metal"}),
    <plustic:pipe_piece>.withTag({Material: "xu_demonic_metal"}),
    <plustic:pipe_piece>.withTag({Material: "boron"}),
    <plustic:pipe_piece>.withTag({Material: "tough"}),
    <plustic:pipe_piece>.withTag({Material: "hard_carbon"}),
    <plustic:pipe_piece>.withTag({Material: "boron_nitride"}),
    <plustic:pipe_piece>.withTag({Material: "thorium"}),
    <plustic:pipe_piece>.withTag({Material: "uranium"}),
    <plustic:pipe_piece>.withTag({Material: "magnesium"}),
    <plustic:pipe_piece>.withTag({Material: "chocolate"}),
    <plustic:pipe_piece>.withTag({Material: "treatedwood"}),
    <plustic:pipe_piece>.withTag({Material: "constantan"}),
    <plustic:pipe_piece>.withTag({Material: "integrationforegoing.plastic"}),
    <plustic:pipe_piece>.withTag({Material: "integrationforegoing.pink_slime"}),
    <plustic:pipe_piece>.withTag({Material: "integrationforegoing.reinforced_pink_slime"}),
    <plustic:pipe_piece>.withTag({Material: "alumite"}),
    <plustic:pipe_piece>.withTag({Material: "nickel"}),
    <plustic:pipe_piece>.withTag({Material: "invar"}),
    <plustic:pipe_piece>.withTag({Material: "iridium"}),
    <plustic:pipe_piece>.withTag({Material: "sapphire"}),
    <plustic:pipe_piece>.withTag({Material: "ruby"}),
    <plustic:pipe_piece>.withTag({Material: "peridot"}),
    <plustic:pipe_piece>.withTag({Material: "osmium"}),
    <plustic:pipe_piece>.withTag({Material: "refinedobsidian"}),
    <plustic:pipe_piece>.withTag({Material: "refinedglowstone"}),
    <plustic:pipe_piece>.withTag({Material: "osgloglas"}),
    <plustic:pipe_piece>.withTag({Material: "osmiridium"}),
    <plustic:pipe_piece>.withTag({Material: "lumium_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "signalum_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "platinum_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "enderium_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "blackquartz_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "void_actadd_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "enori_actadd_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "palis_actadd_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "restonia_actadd_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "emeradic_actadd_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "diamatine_actadd_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "infinity_avaritia_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "certusquartz_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "fluixcrystal_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "mica"}),
    <plustic:pipe_piece>.withTag({Material: "litherite"}),
    <plustic:pipe_piece>.withTag({Material: "erodium"}),
    <plustic:pipe_piece>.withTag({Material: "kyronite"}),
    <plustic:pipe_piece>.withTag({Material: "pladium"}),
    <plustic:pipe_piece>.withTag({Material: "ionite"}),
    <plustic:pipe_piece>.withTag({Material: "aethium"}),
    <plustic:pipe_piece>.withTag({Material: "wyvern_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "awakened_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "chaotic_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "darkmatter"}),
    <plustic:pipe_piece>.withTag({Material: "redmatter"}),
    <plustic:pipe_piece>.withTag({Material: "emerald_plustic"}),
    <plustic:pipe_piece>.withTag({Material: "wood"}),
    <plustic:laser_medium>.withTag({Material: "stone"}),
    <plustic:laser_medium>.withTag({Material: "prismarine"}),
    <plustic:laser_medium>.withTag({Material: "blaze"}),
    <plustic:laser_medium>.withTag({Material: "endrod"}),
    <plustic:laser_medium>.withTag({Material: "refinedobsidian"}),
    <plustic:laser_medium>.withTag({Material: "refinedglowstone"}),
    <plustic:laser_medium>.withTag({Material: "palis_actadd_plustic"}),
    <plustic:laser_medium>.withTag({Material: "emeradic_actadd_plustic"}),
    <plustic:laser_medium>.withTag({Material: "diamatine_actadd_plustic"}),
    <plustic:laser_medium>.withTag({Material: "infinity_avaritia_plustic"}),
    <plustic:laser_medium>.withTag({Material: "certusquartz_plustic"}),
    <plustic:laser_medium>.withTag({Material: "fluixcrystal_plustic"}),
    <plustic:laser_medium>.withTag({Material: "chaotic_plustic"}),
    <plustic:laser_medium>.withTag({Material: "darkmatter"}),
    <plustic:battery_cell>.withTag({Material: "stone"}),
    <plustic:battery_cell>.withTag({Material: "manyullyn"}),
    <plustic:battery_cell>.withTag({Material: "copper"}),
    <plustic:battery_cell>.withTag({Material: "silver"}),
    <plustic:battery_cell>.withTag({Material: "blaze"}),
    <plustic:battery_cell>.withTag({Material: "endrod"}),
    <plustic:battery_cell>.withTag({Material: "nickel"}),
    <plustic:battery_cell>.withTag({Material: "osmium"}),
    <plustic:battery_cell>.withTag({Material: "enori_actadd_plustic"}),
    <plustic:battery_cell>.withTag({Material: "restonia_actadd_plustic"}),
    <plustic:battery_cell>.withTag({Material: "fluixcrystal_plustic"}),
    <plustic:centrifuge>,
    <plustic:centrifuge:1>

];

for item in tcstage1 {
    mods.recipestages.Recipes.setRecipeStage("bettertools", item);
    mods.ItemStages.addItemStage("bettertools", item);
}